// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { api, apiBlob, APIError } from '../lib/api';
import type { UserView } from '../auth-types';
import type { AdminCommandInput, AdminPage } from '../lib/admin-types';
import type { AdminFile, AdminMessage, AdminReportDetail, AdminSettings } from '../lib/admin-s2-types';
import { AdminShell } from './AdminShell';
import { AdminActionDialog } from './AdminActionDialog';
import { AdminContext, type ActionRequest } from './AdminShared';
import { FileContent } from './FilesPage';

vi.mock('../lib/api', async (original) => ({ ...await original<typeof import('../lib/api')>(), api: vi.fn(), apiBlob: vi.fn() }));
const requestApi = vi.mocked(api); const requestBlob = vi.mocked(apiBlob);
const actor: UserView = { id: 'admin', username: 'admin', nickname: '超管', bio: '', siteRole: 'super_admin', status: 'active', createdAt: 1, preferences: { invisible: false, readReceipts: true, doNotDisturb: false } };
const owner = { id: 'u1', username: 'owner_one', nickname: '文件所有者' };
const page = <T,>(items: T[], nextCursor: string | null = null): AdminPage<T> => ({ items, nextCursor, total: items.length + (nextCursor ? 1 : 0) });
const file: AdminFile = { id: 'f1', name: '证据文件.png', owner, conversationId: 'c1', messageId: 'm1', purpose: 'message', kind: 'image', mime: 'image/png', size: 2048, sha256: 'abc123', state: 'ready', scanStatus: 'clean', governance: 'available', governanceReason: '', chargedBytes: 2048, createdAt: 1, expiresAt: Date.now() + 3600000, version: 1, contentAvailable: true, previewAvailable: true, cleanupReason: null };
const message: AdminMessage = { id: 'm1', conversationId: 'c1', seq: '10', conversation: { id: 'c1', title: '被举报会话', kind: 'direct', status: 'active' }, sender: owner, kind: 'user', text: '受控正文', status: 'sent', moderationKind: null, createdAt: 1, removedAt: null, removedReason: null, retained: true, canRestore: false, attachments: [file], replyToMessageId: null, reviewedAt: null, reviewedBy: null, version: 1 };
const report: AdminReportDetail = { report: { id: 'r1', reporter: { id: 'reporter', nickname: '举报者', username: 'reporter' }, targetKind: 'message', targetId: 'm1', category: 'harassment', status: 'open', assignedTo: null, version: 1, createdAt: 1, updatedAt: 2, description: '需要理由读取的举报说明', feedback: null }, target: message, events: [] };
const settings: AdminSettings = { version: 3, values: { maintenance: false, capacity: 100, name: '同频', registrationMode: 'closed' }, fields: [{ key: 'maintenance', label: '维护模式', group: '运行策略', type: 'boolean', help: '立即用于后续请求' }, { key: 'capacity', label: '群容量', group: '群聊', type: 'integer', min: 2, max: 1000, help: '新加入时校验' }, { key: 'name', label: '站点名称', group: '运营', type: 'string', max: 100, help: '用户可见名称' }, { key: 'registrationMode', label: '注册模式', group: '运营', type: 'enum', options: [{ value: 'closed', label: '关闭注册' }, { value: 'open', label: '开放注册' }], help: '开放前检查运营信息' }], appliedAt: 1, effect: 'immediate', environment: 'development', readOnly: ['部署扫描安全下限只读'] };
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((finish) => { resolve = finish; }); return { promise, resolve }; }
function mount(path: string) { window.history.replaceState({}, '', path); return render(<AdminShell user={actor} onSignOut={vi.fn()} signOutBusy={false} signOutError="" />); }
function readReason(container: HTMLElement | typeof screen = screen, value = '核实用户举报事实') { const target = container === screen ? screen : within(container as HTMLElement); fireEvent.change(target.getByLabelText('读取理由'), { target: { value } }); }
function installCommands(read: (path: string, init: Parameters<typeof api>[1]) => unknown | Promise<unknown> = () => { throw new Error('Unexpected read'); }) {
  let input: AdminCommandInput; const paths: string[] = [];
  requestApi.mockImplementation(async (path, init = {}) => { paths.push(path); if (path.endsWith('/commands/preview')) { input = init.body as AdminCommandInput; return { operationId: input.operationId, action: input.action, reason: input.reason, targetCount: input.targetIds.length, targets: input.targetIds.map((id) => ({ id, label: `目标 ${id}`, detail: 'active' })), impacts: ['服务器确认的真实影响'], expiresAt: Date.now() + 60000, requiresReauthentication: true }; } if (path.endsWith('/reauth')) return { reauthToken: 'ephemeral' }; if (path.endsWith('/commands/execute')) return { operationId: input.operationId, action: input.action, status: 'completed', total: 1, succeeded: 1, failed: 0, pending: 0, items: [{ id: input.targetIds[0], label: '目标', status: 'succeeded', code: null, message: null }], createdAt: 1, updatedAt: 2, jobId: null, secretAvailable: input.action === 'site_invite.create' }; if (path.endsWith('/secret')) return { credential: 'PRIVATE-INVITE-CODE', expiresAt: Date.now() + 86400000, username: '', kind: 'site_invite' }; return read(path, init); });
  return { input: () => input!, paths };
}
async function preview() { fireEvent.change(screen.getByLabelText('操作理由'), { target: { value: '经核实后执行管理操作' } }); fireEvent.click(screen.getByRole('button', { name: '预览目标与影响' })); await screen.findByRole('heading', { name: '服务端操作预览' }); }
async function execute() { fireEvent.change(screen.getByLabelText('管理员当前密码'), { target: { value: 'secret-password' } }); fireEvent.click(screen.getByRole('button', { name: '验证身份并执行' })); await screen.findByRole('heading', { name: '执行结果：已完成' }); }
beforeEach(() => { requestApi.mockReset(); requestBlob.mockReset(); Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function (this: HTMLDialogElement) { this.open = true; } }); Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value: function (this: HTMLDialogElement) { this.open = false; } }); Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:private-ui-test') }); Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); window.history.replaceState({}, '', '/'); });

describe('S2 sensitive content and files', () => {
  it('requires a reason before POST search and keeps query/reason only in memory across pagination', async () => {
    const storage = vi.spyOn(Storage.prototype, 'setItem'); requestApi.mockImplementation(async (_path, init) => page([{ ...message, id: (init?.body as { after?: string }).after ? 'm2' : 'm1' }], (init?.body as { after?: string }).after ? null : 'opaque+next'));
    mount('/admin/content?status=moderated&senderId=u1'); expect(requestApi).not.toHaveBeenCalled(); expect(screen.getByLabelText('消息状态')).toHaveValue('moderated'); fireEvent.change(screen.getByLabelText('正文搜索词'), { target: { value: 'PRIVATE-QUERY' } }); readReason(screen, 'PRIVATE-READ-REASON'); fireEvent.click(screen.getByRole('button', { name: '搜索消息' })); await screen.findByText('受控正文');
    expect(requestApi.mock.calls[0]).toMatchObject(['/api/v1/admin/content/search', { method: 'POST', body: { query: 'PRIVATE-QUERY', reason: 'PRIVATE-READ-REASON', status: 'moderated', senderId: 'u1', limit: 50 } }]); expect(window.location.href).not.toMatch(/PRIVATE|reason|query/); expect(window.location.search).toContain('status=moderated'); fireEvent.click(screen.getByRole('checkbox', { name: '选择消息 m1' })); fireEvent.click(screen.getByRole('button', { name: '下一页消息' })); await screen.findByRole('checkbox', { name: '选择消息 m2' }); expect(screen.getByText('当前页已选 0 / 1 条')).toBeInTheDocument(); expect(requestApi.mock.calls[1][1]?.body).toMatchObject({ after: 'opaque+next', query: 'PRIVATE-QUERY', reason: 'PRIVATE-READ-REASON' }); expect(storage).not.toHaveBeenCalled();
  });
  it('does not read bookmarked content details until a fresh reason is submitted', async () => {
    requestApi.mockResolvedValue({ message: { ...message, text: null, retained: false, canRestore: false, status: 'purged' }, items: [], hasBefore: false, hasAfter: false }); mount('/admin/content?id=m1'); expect(requestApi).not.toHaveBeenCalled(); const panel = screen.getByRole('heading', { name: '消息上下文 · m1' }).parentElement!; readReason(panel); fireEvent.click(within(panel).getByRole('button', { name: '读取消息上下文' })); await screen.findByText('正文已不在保留期内或已清除'); expect(screen.getByRole('button', { name: '恢复管理处置' })).toBeDisabled(); expect(requestApi.mock.calls[0][1]?.body).toEqual({ reason: '核实用户举报事实' });
  });
  it('discards sensitive responses when navigating away and requires new input on returning', async () => {
    const pending = deferred<unknown>(); requestApi.mockImplementation((path) => path.includes('/content/search') ? pending.promise : Promise.resolve({ window: '24h', from: 1, to: 2, generatedAt: 2, metrics: [], trends: [], processStartedAt: 1 })); mount('/admin/content'); readReason(); fireEvent.change(screen.getByLabelText('正文搜索词'), { target: { value: 'PRIVATE-QUERY' } }); fireEvent.click(screen.getByRole('button', { name: '搜索消息' })); const signal = requestApi.mock.calls[0][1]?.signal; fireEvent.click(screen.getByRole('link', { name: '运营概览' })); expect(signal?.aborted).toBe(true); await act(async () => pending.resolve(page([message]))); expect(screen.queryByText('受控正文')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('link', { name: '消息治理' })); expect(screen.getByLabelText('正文搜索词')).toHaveValue(''); expect(screen.getByLabelText('读取理由')).toHaveValue('');
  });
  it('clears the sensitive page and cancels on downgraded permissions', async () => { requestApi.mockRejectedValue(new APIError(403, { code: 'ADMIN_REQUIRED', message: '无权限' })); mount('/admin/content'); readReason(); fireEvent.click(screen.getByRole('button', { name: '搜索消息' })); await screen.findByRole('heading', { name: '管理权限已失效' }); expect(screen.queryByLabelText('读取理由')).not.toBeInTheDocument(); await waitFor(() => expect(requestApi.mock.calls[0][1]?.signal?.aborted).toBe(true)); });
  it('filters file governance and uses the submitted reason for current-page detail reads', async () => {
    requestApi.mockImplementation(async (path) => path.endsWith('/search') ? page([file]) : { file }); mount('/admin/files?governance=quarantined&ownerId=u1'); readReason(); fireEvent.change(screen.getByLabelText('文件名搜索词'), { target: { value: 'PRIVATE-FILENAME' } }); fireEvent.click(screen.getByRole('button', { name: '搜索文件' })); await screen.findByText('证据文件.png'); expect(requestApi.mock.calls[0][1]?.body).toMatchObject({ governance: 'quarantined', ownerId: 'u1', query: 'PRIVATE-FILENAME' }); fireEvent.click(screen.getByRole('button', { name: '查看文件' })); await screen.findByRole('button', { name: '读取受控预览' }); expect(requestApi.mock.calls[1][0]).toBe('/api/v1/admin/files/f1/read'); expect(requestApi.mock.calls[1][1]?.body).toEqual({ reason: '核实用户举报事实' }); expect(window.location.href).not.toContain('PRIVATE'); expect(window.location.search).toContain('id=f1');
  });
  it.each(['preview', 'content'] as const)('retrieves private %s bytes via apiBlob and revokes the URL on unmount', async (variant) => { requestBlob.mockResolvedValue(new Blob(['binary'], { type: 'image/png' })); const view = render(<FileContent file={file} reason="核实附件举报" variant={variant} onClose={vi.fn()} />); if (variant === 'preview') expect(await screen.findByRole('img')).toHaveAttribute('src', 'blob:private-ui-test'); else expect(await screen.findByRole('link', { name: '保存文件到设备' })).toHaveAttribute('download', file.name); expect(requestBlob.mock.calls[0]).toMatchObject(['/api/v1/admin/files/f1/content', { body: { reason: '核实附件举报', variant } }]); const signal = requestBlob.mock.calls[0][1].signal; view.unmount(); expect(signal?.aborted).toBe(true); expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:private-ui-test'); });
  it('never creates a Blob URL for late bytes after identity removal', async () => { const pending = deferred<Blob>(); requestBlob.mockReturnValue(pending.promise); const view = render(<FileContent file={file} reason="核实附件举报" variant="preview" onClose={vi.fn()} />); view.unmount(); await act(async () => pending.resolve(new Blob(['late']))); expect(URL.createObjectURL).not.toHaveBeenCalled(); });
  it('carries file-state filters and the same in-memory reason through file pagination', async () => { requestApi.mockImplementation(async (_path, init) => page([{ ...file, id: (init?.body as { after?: string }).after ? 'f2' : 'f1' }], (init?.body as { after?: string }).after ? null : 'file-next')); mount('/admin/files?state=uploading&governance=quarantined'); readReason(); fireEvent.click(screen.getByRole('button', { name: '搜索文件' })); await screen.findByRole('checkbox', { name: '选择文件 f1' }); fireEvent.click(screen.getByRole('checkbox', { name: '选择文件 f1' })); fireEvent.click(screen.getByRole('button', { name: '下一页文件' })); await screen.findByRole('checkbox', { name: '选择文件 f2' }); expect(screen.getByText('当前页已选 0 / 1 件')).toBeInTheDocument(); expect(requestApi.mock.calls[1][1]?.body).toMatchObject({ reason: '核实用户举报事实', state: 'uploading', governance: 'quarantined', after: 'file-next' }); });
  it('revokes acquired preview bytes when the real page close control is used', async () => { requestApi.mockResolvedValue({ file }); requestBlob.mockResolvedValue(new Blob(['private'])); mount('/admin/files?id=f1'); const detail = screen.getByRole('heading', { name: '文件详情 · f1' }).parentElement!; readReason(detail); fireEvent.click(within(detail).getByRole('button', { name: '读取文件详情' })); fireEvent.click(await screen.findByRole('button', { name: '读取受控预览' })); await screen.findByRole('img'); fireEvent.click(screen.getByRole('button', { name: '关闭并释放文件' })); expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:private-ui-test'); expect(screen.queryByRole('img')).not.toBeInTheDocument(); });
  it('clears all sensitive page state after binary authorization fails', async () => { requestApi.mockResolvedValue({ file }); requestBlob.mockRejectedValue(new APIError(403, { code: 'ADMIN_REQUIRED', message: '管理权限已收回' })); mount('/admin/files?id=f1'); const detail = screen.getByRole('heading', { name: '文件详情 · f1' }).parentElement!; readReason(detail); fireEvent.click(within(detail).getByRole('button', { name: '读取文件详情' })); fireEvent.click(await screen.findByRole('button', { name: '读取受控预览' })); await screen.findByRole('heading', { name: '管理权限已失效' }); expect(screen.queryByText(file.name)).not.toBeInTheDocument(); await waitFor(() => expect(requestBlob.mock.calls[0][1].signal?.aborted).toBe(true)); expect(URL.createObjectURL).not.toHaveBeenCalled(); });
  it('uses the latest safe URL filters when a command completion remounts a sensitive page', async () => { installCommands(() => page([message])); mount('/admin/content?status=sent'); fireEvent.change(screen.getByLabelText('消息状态'), { target: { value: 'moderated' } }); readReason(); fireEvent.click(screen.getByRole('button', { name: '搜索消息' })); fireEvent.click(await screen.findByRole('checkbox', { name: '选择消息 m1' })); fireEvent.click(screen.getByRole('button', { name: '审阅所选' })); await preview(); await execute(); expect(screen.getByLabelText('消息状态')).toHaveValue('moderated'); expect(screen.getByLabelText('读取理由')).toHaveValue(''); expect(window.location.search).toContain('status=moderated'); });
});

describe('S2 report context and command parameters', () => {
  it('filters safe report metadata and only reads sensitive description after a reason', async () => { requestApi.mockImplementation(async (path) => path.endsWith('/read') ? report : page([report.report], 'report-next')); mount('/admin/reports?status=open&category=harassment&assigned=mine&id=r1'); await screen.findByRole('link', { name: 'r1' }); expect(screen.queryByText(report.report.description)).not.toBeInTheDocument(); expect(requestApi.mock.calls[0][0]).toContain('assigned=mine'); readReason(); fireEvent.click(screen.getByRole('button', { name: '读取举报证据' })); await screen.findByText(report.report.description); expect(requestApi.mock.calls.at(-1)?.[1]?.body).toEqual({ reason: '核实用户举报事实' }); });
  it('builds a report resolution only from its actual sender and fixes parameters before preview/reauth', async () => { const commands = installCommands((path) => path.endsWith('/read') ? report : page([report.report])); mount('/admin/reports?id=r1'); readReason(); fireEvent.click(screen.getByRole('button', { name: '读取举报证据' })); await screen.findByText(report.report.description); fireEvent.change(screen.getByLabelText('给举报者的反馈'), { target: { value: '已核实并处理' } }); fireEvent.change(screen.getByLabelText('可选关联处置'), { target: { value: 'sender-ban' } }); fireEvent.click(screen.getByRole('button', { name: '预览处理方案' })); expect(screen.getByText('封禁消息发送者 文件所有者 (@owner_one)', { selector: 'dd' })).toBeInTheDocument(); await preview(); expect(commands.input()).toMatchObject({ action: 'report.resolve', targetIds: ['r1'], parameters: { feedback: '已核实并处理', disposition: { action: 'user.ban', targetId: 'u1' } } }); expect(commands.paths.filter((path) => path.endsWith('/execute'))).toHaveLength(0); await execute(); expect(commands.paths.indexOf('/api/v1/auth/reauth')).toBeGreaterThan(commands.paths.indexOf('/api/v1/admin/commands/preview')); });
  it('does not offer unrelated disposition targets when report object ID mismatches', async () => { requestApi.mockImplementation(async (path) => path.endsWith('/read') ? { ...report, target: { ...message, id: 'unrelated-message' } } : page([report.report])); mount('/admin/reports?id=r1'); readReason(); fireEvent.click(screen.getByRole('button', { name: '读取举报证据' })); await screen.findByText('当前未取得匹配的举报对象，不能追加关联处置。'); expect(within(screen.getByLabelText('可选关联处置')).getAllByRole('option')).toHaveLength(1); expect(screen.queryByText('受控正文')).not.toBeInTheDocument(); });
  it('shows reopening for resolved reports without offering another resolve form', async () => { requestApi.mockImplementation(async (path) => path.endsWith('/read') ? { ...report, report: { ...report.report, status: 'resolved', feedback: '已处理' } } : page([])); mount('/admin/reports?id=r1'); readReason(); fireEvent.click(screen.getByRole('button', { name: '读取举报证据' })); await screen.findByRole('button', { name: '重开工单' }); expect(screen.queryByLabelText('给举报者的反馈')).not.toBeInTheDocument(); });
  it('snapshots supplied parameters independently of later object changes', async () => { const commands = installCommands(); const parameters = { expectedVersion: 3, values: { maintenance: true } }; const request: ActionRequest = { action: 'settings.update', targetIds: ['instance'], labels: ['站点策略'], parameters, parameterSummary: [{ label: '维护模式', value: '关闭 → 开启' }] }; render(<AdminActionDialog request={request} onClose={vi.fn()} onChanged={vi.fn()} />); parameters.values.maintenance = false; await preview(); expect(commands.input().parameters).toEqual({ expectedVersion: 3, values: { maintenance: true } }); });
});

describe('S2 policy versions, quota and invitations', () => {
  function policyReads(path: string) { if (path === '/api/v1/admin/settings') return settings; if (path.includes('/versions')) return page([{ version: 2, actor: null, reason: '旧版本', createdAt: 1, values: { ...settings.values, capacity: 80 } }], 'history-next'); if (path.includes('/site-invites')) return page([]); throw new Error(path); }
  it('renders typed Chinese policy fields and previews complete values with expectedVersion', async () => { const commands = installCommands(policyReads); mount('/admin/settings'); await screen.findByLabelText('维护模式'); fireEvent.click(screen.getByLabelText('维护模式')); fireEvent.change(screen.getByLabelText('群容量'), { target: { value: '120' } }); fireEvent.click(screen.getByRole('button', { name: '预览配置变更' })); expect(screen.getAllByText('关闭 → 开启').length).toBeGreaterThan(0); await preview(); expect(commands.input().parameters).toEqual({ expectedVersion: 3, values: { ...settings.values, maintenance: true, capacity: 120 } }); expect(screen.queryByRole('textbox', { name: /JSON/ })).not.toBeInTheDocument(); });
  it('shows actual historical differences and fixes both versions for rollback', async () => { const commands = installCommands(policyReads); mount('/admin/settings'); fireEvent.click(await screen.findByRole('button', { name: '比较版本 2' })); expect(screen.getByText('100 → 80')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '预览回滚版本 2' })); await preview(); expect(commands.input()).toMatchObject({ action: 'settings.rollback', parameters: { expectedVersion: 3, version: 2 } }); });
  it('stops a conflicting configuration preview before reauthentication and asks for refreshed values', async () => { requestApi.mockImplementation(async (path) => { if (path.endsWith('/preview')) throw new APIError(409, { code: 'VERSION_CONFLICT', message: '配置版本已变化' }); return policyReads(path); }); mount('/admin/settings'); fireEvent.click(await screen.findByLabelText('维护模式')); fireEvent.click(screen.getByRole('button', { name: '预览配置变更' })); fireEvent.change(screen.getByLabelText('操作理由'), { target: { value: '核实站点运行策略' } }); fireEvent.click(screen.getByRole('button', { name: '预览目标与影响' })); await screen.findByText(/请关闭窗口并刷新运行配置/); expect(requestApi.mock.calls.some(([path]) => path.endsWith('/reauth') || path.endsWith('/execute'))).toBe(false); });
  it('creates an invite with its own one-time secret instructions rather than password reset text', async () => { const storage = vi.spyOn(Storage.prototype, 'setItem'); const commands = installCommands(policyReads); mount('/admin/settings'); fireEvent.change(await screen.findByLabelText('最多使用次数'), { target: { value: '3' } }); fireEvent.click(screen.getByRole('button', { name: '预览创建邀请码' })); await preview(); expect(commands.input().parameters).toEqual({ maxUses: 3, expiresInHours: 24 }); await execute(); fireEvent.click(screen.getByRole('button', { name: '显示一次性站点邀请码' })); await screen.findByText('PRIVATE-INVITE-CODE'); expect(screen.getByText(/受邀者在同频注册页/)).toBeInTheDocument(); expect(screen.queryByText(/使用用户名与此恢复凭据设置新密码/)).not.toBeInTheDocument(); expect(storage).not.toHaveBeenCalled(); });
  it('offers a null quota to restore the site default through normal controls', async () => { const commands = installCommands(); render(<AdminActionDialog request={{ action: 'user.quota', targetIds: ['u1'], labels: ['文件所有者'], initial: { quotaBytes: 2048 } }} onClose={vi.fn()} onChanged={vi.fn()} />); expect(screen.getByLabelText('附件配额（字节）')).toHaveValue(2048); fireEvent.click(screen.getByLabelText('恢复站点默认配额')); await preview(); expect(commands.input().parameters).toEqual({ quotaBytes: null }); });
  it('keeps history and invite cursors separate while navigating policy history', async () => { installCommands(policyReads); mount('/admin/settings?invitesAfter=invite-cursor'); await screen.findByRole('button', { name: '比较版本 2' }); const history = screen.getByRole('region', { name: '策略版本历史' }).parentElement!; fireEvent.click(within(history).getByRole('link', { name: '下一页' })); await waitFor(() => expect(requestApi.mock.calls.some(([path]) => path.includes('/versions?after=history-next'))).toBe(true)); expect(new URLSearchParams(window.location.search).get('invitesAfter')).toBe('invite-cursor'); expect(new URLSearchParams(window.location.search).get('historyAfter')).toBe('history-next'); });
});
