// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { api, APIError } from '../lib/api';
import type { AdminCommandInput, AdminPage } from '../lib/admin-types';
import type { AdminGroupTasks, AdminTaskDetail, AdminTaskReport, AdminTaskReportDetail } from '../lib/admin-tasks-types';
import type { UserView } from '../auth-types';
import { AdminContext } from './AdminShared';
import { AdminShell } from './AdminShell';
import { TasksPage } from './TasksPage';
import { MessageEvidence } from './ContentPage';
import type { AdminMessage } from '../lib/admin-s2-types';
vi.mock('../lib/api', async (original) => ({ ...await original<typeof import('../lib/api')>(), api: vi.fn() }));
const requestApi = vi.mocked(api);
const actor: UserView = { id: 'admin1', username: 'admin_one', nickname: '管理员', bio: '', siteRole: 'super_admin', status: 'active', createdAt: 1, preferences: { invisible: false, readReceipts: true, doNotDisturb: false } };
const task = { id: 'task1', groupId: 'group1', title: '群任务标题', status: 'todo' as const, priority: 'normal' as const, dueOn: null, deletedAt: null, moderatedDeleted: false, canRestore: false, version: 1, createdAt: 1 };
const groupPage: AdminGroupTasks = { group: { id: 'group1', name: '已核对的群', status: 'active', createPolicy: 'members', quota: 500 }, items: [task], nextCursor: null, total: 1 };
const detail: AdminTaskDetail = { task: { ...task, description: 'GROUP-CURRENT-DESCRIPTION', creator: actor, assignee: null, checks: [{ id: 'check1', text: '核对检查项', done: 0 }] }, comments: { items: [{ id: 'comment1', text: 'CURRENT-COMMENT-TEXT', removed: false, author: actor, createdAt: 1 }], nextCursor: null, total: 1 } };
const report: AdminTaskReport = { id: 'report1', category: 'harassment', status: 'open', createdAt: 1, closedAt: null, version: 1 };
const reportDetail: AdminTaskReportDetail = { report: { ...report, description: '举报人说明', feedback: null, reporter: actor }, submitted: { title: 'REPORTED-PRIVATE-SNAPSHOT', scope: 'personal', groupId: null, description: 'SUBMITTED-DESCRIPTION', comment: 'SUBMITTED-COMMENT', commentId: 'private-comment1' }, targetState: { available: true, deleted: false, moderatedDeleted: false, hasComment: true, commentRemoved: false } };
const page = <T,>(items: T[], nextCursor: string | null = null): AdminPage<T> => ({ items, nextCursor, total: items.length });
function context() { return { navigate: vi.fn(), openAction: vi.fn(), deny: vi.fn(), revision: 0 }; }
function mount() { const ctx = context(); const view = render(<AdminContext.Provider value={ctx}><TasksPage /></AdminContext.Provider>); return { ctx, ...view }; }
function install() { requestApi.mockImplementation(async (path) => { if (path === '/api/v1/admin/tasks/search') return groupPage; if (path === '/api/v1/admin/tasks/task1/read') return detail; if (path.startsWith('/api/v1/admin/task-reports?')) return page([report]); if (path === '/api/v1/admin/task-reports/report1/read') return reportDetail; if (path.startsWith('/api/v1/admin/groups?')) return page([{ id: 'group1', name: '已核对的群', status: 'active' }]); throw new Error('Unexpected scoped task request'); }); }
async function searchGroup() { const form = screen.getByRole('region', { name: '群待办受控搜索' }); fireEvent.change(within(form).getByLabelText('群编号'), { target: { value: 'group1' } }); fireEvent.change(within(form).getByLabelText('待办标题关键词'), { target: { value: '限定标题关键词' } }); fireEvent.change(within(form).getByLabelText('读取理由'), { target: { value: '核对群内投诉的读取理由' } }); fireEvent.click(within(form).getByRole('button', { name: '按理由搜索群待办' })); await screen.findByRole('button', { name: '核对待办详情' }); }
async function readTask() { await searchGroup(); fireEvent.click(screen.getByRole('button', { name: '核对待办详情' })); const panel = screen.getByRole('region', { name: '群待办详情' }); fireEvent.change(within(panel).getByLabelText('读取理由'), { target: { value: '核对任务与评论的理由' } }); fireEvent.click(within(panel).getByRole('button', { name: '按理由读取待办详情' })); await within(panel).findByText('GROUP-CURRENT-DESCRIPTION'); return panel; }
async function readReport() { fireEvent.click(screen.getByRole('button', { name: '待办举报工单' })); fireEvent.click(await screen.findByRole('button', { name: '填写理由核对举报材料' })); const panel = screen.getByRole('region', { name: '待办举报提交材料' }); fireEvent.change(within(panel).getByLabelText('读取理由'), { target: { value: '核对这份举报的提交材料' } }); fireEvent.click(within(panel).getByRole('button', { name: '按理由读取举报材料' })); await within(panel).findByText('REPORTED-PRIVATE-SNAPSHOT'); return panel; }
beforeEach(() => { requestApi.mockReset(); Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function (this: HTMLDialogElement) { this.open = true; } }); Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value: function (this: HTMLDialogElement) { this.open = false; } }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); window.history.replaceState({}, '', '/'); });

describe('V3 task governance controlled reading', () => {
  it('does not request a global personal list and sends title/reason only in POST body', async () => {
    install(); const storage = vi.spyOn(Storage.prototype, 'setItem'); const view = mount(); expect(requestApi).not.toHaveBeenCalled(); await searchGroup(); expect(requestApi).toHaveBeenCalledWith('/api/v1/admin/tasks/search', expect.objectContaining({ method: 'POST', body: { groupId: 'group1', query: '限定标题关键词', reason: '核对群内投诉的读取理由', status: '', deleted: '', limit: 30 } })); expect(window.location.search).toBe(''); expect(storage).not.toHaveBeenCalled(); expect(view.ctx.navigate).not.toHaveBeenCalled(); expect(requestApi.mock.calls.every(([path]) => !path.includes('限定标题') && !path.includes('读取理由'))).toBe(true);
  });
  it('lists only report metadata until an explicit reason reads the submitted snapshot', async () => {
    install(); mount(); fireEvent.click(screen.getByRole('button', { name: '待办举报工单' })); await screen.findByText('工单 report1'); expect(screen.queryByText('REPORTED-PRIVATE-SNAPSHOT')).not.toBeInTheDocument(); expect(screen.queryByText('private-comment1')).not.toBeInTheDocument(); expect(requestApi.mock.calls.some(([path]) => path.endsWith('/read'))).toBe(false); fireEvent.click(screen.getByRole('button', { name: '填写理由核对举报材料' })); const panel = screen.getByRole('region', { name: '待办举报提交材料' }); fireEvent.change(within(panel).getByLabelText('读取理由'), { target: { value: '明确核对举报材料' } }); fireEvent.click(within(panel).getByRole('button', { name: '按理由读取举报材料' })); await screen.findByText('REPORTED-PRIVATE-SNAPSHOT'); expect(requestApi).toHaveBeenLastCalledWith('/api/v1/admin/task-reports/report1/read', expect.objectContaining({ method: 'POST', body: { reason: '明确核对举报材料' } })); expect(screen.queryByText('private-comment1')).not.toBeInTheDocument();
  });
  it('retains the original reason and filters for each audited search page', async () => {
    requestApi.mockResolvedValue({ ...groupPage, nextCursor: 'task-page2' }); mount(); await searchGroup(); fireEvent.click(screen.getByRole('button', { name: '按同一理由读取下一页待办' })); await waitFor(() => expect(requestApi).toHaveBeenCalledTimes(2)); expect(requestApi.mock.calls[1][1]?.body).toEqual({ groupId: 'group1', query: '限定标题关键词', reason: '核对群内投诉的读取理由', status: '', deleted: '', limit: 30, after: 'task-page2' }); expect(requestApi.mock.calls[1][0]).toBe('/api/v1/admin/tasks/search');
  });
  it('audits each comment page with its own original detail reason', async () => {
    install(); requestApi.mockImplementation(async (path) => path === '/api/v1/admin/tasks/search' ? groupPage : { ...detail, comments: { ...detail.comments, nextCursor: 'comment-page2' } }); mount(); await readTask(); fireEvent.click(screen.getByRole('button', { name: '按同一理由读取下一页评论' })); await waitFor(() => expect(requestApi).toHaveBeenLastCalledWith('/api/v1/admin/tasks/task1/read', expect.objectContaining({ body: { reason: '核对任务与评论的理由', limit: 30, after: 'comment-page2' } })));
  });
  it('aborts sensitive search on tab switch and does not display a late response', async () => {
    let resolve!: (value: unknown) => void; requestApi.mockImplementation((path) => path === '/api/v1/admin/tasks/search' ? new Promise((done) => { resolve = done; }) : Promise.resolve(page([]))); mount(); const form = screen.getByRole('region', { name: '群待办受控搜索' }); fireEvent.change(within(form).getByLabelText('群编号'), { target: { value: 'group1' } }); fireEvent.change(within(form).getByLabelText('读取理由'), { target: { value: '读取后切换栏目' } }); fireEvent.click(within(form).getByRole('button', { name: '按理由搜索群待办' })); const signal = requestApi.mock.calls[0][1]!.signal!; fireEvent.click(screen.getByRole('button', { name: '待办举报工单' })); expect(signal.aborted).toBe(true); await act(async () => resolve({ ...groupPage, items: [{ ...task, title: 'LATE-SENSITIVE-TITLE' }] })); expect(screen.queryByText('LATE-SENSITIVE-TITLE')).not.toBeInTheDocument();
  });
  it('clears all displayed group and report content if a sensitive read loses authorization', async () => {
    install(); const { ctx } = mount(); await searchGroup(); requestApi.mockRejectedValueOnce(new APIError(403, { code: 'ADMIN_REVOKED', message: '管理权限改变' })); fireEvent.click(screen.getByRole('button', { name: '核对待办详情' })); const panel = screen.getByRole('region', { name: '群待办详情' }); fireEvent.change(within(panel).getByLabelText('读取理由'), { target: { value: '再次核对任务内容' } }); fireEvent.click(within(panel).getByRole('button', { name: '按理由读取待办详情' })); await screen.findByText('待办治理权限已失效'); expect(ctx.deny).toHaveBeenCalledTimes(1); expect(screen.queryByText('群任务标题')).not.toBeInTheDocument(); expect(screen.queryByLabelText('读取理由')).not.toBeInTheDocument();
  });
  it('distinguishes an empty result from a failed read and keeps explicit retry in the reason form', async () => {
    requestApi.mockRejectedValueOnce(new APIError(500, { message: '任务读取暂时失败' })).mockResolvedValue({ ...groupPage, items: [], total: 0 }); mount(); const form = screen.getByRole('region', { name: '群待办受控搜索' }); fireEvent.change(within(form).getByLabelText('群编号'), { target: { value: 'group1' } }); fireEvent.change(within(form).getByLabelText('读取理由'), { target: { value: '本次明确读取理由' } }); fireEvent.click(within(form).getByRole('button', { name: '按理由搜索群待办' })); await screen.findByText(/任务读取暂时失败/); expect(screen.queryByText('当前群内没有符合这些筛选条件的待办。')).not.toBeInTheDocument(); fireEvent.click(within(form).getByRole('button', { name: '按理由搜索群待办' })); await screen.findByText('当前群内没有符合这些筛选条件的待办。');
  });
  it('loads selectable groups from the real paged group metadata contract', async () => {
    requestApi.mockResolvedValueOnce(page([{ id: 'group1', name: '第一群', status: 'active' }], 'group2')).mockResolvedValueOnce(page([{ id: 'group2', name: '第二群', status: 'active' }])); mount(); fireEvent.click(screen.getByRole('button', { name: '查找可管理群编号' })); await screen.findByText('第一群'); fireEvent.click(screen.getByRole('button', { name: '下一页群列表' })); await screen.findByText('第二群'); fireEvent.click(screen.getByRole('button', { name: '选择此群' })); expect(screen.getByLabelText('群编号')).toHaveValue('group2'); expect(requestApi).toHaveBeenLastCalledWith('/api/v1/admin/groups?after=group2&limit=20', expect.any(Object));
  });
});

describe('V3 task governance command boundaries', () => {
  it('freezes group policy parameters for the existing action dialog', async () => {
    install(); const { ctx } = mount(); await searchGroup(); fireEvent.change(screen.getByLabelText('群待办创建策略'), { target: { value: 'managers' } }); fireEvent.click(screen.getByRole('button', { name: '预览群策略调整' })); const sent = ctx.openAction.mock.calls[0][0]; fireEvent.change(screen.getByLabelText('群待办创建策略'), { target: { value: 'members' } }); expect(sent).toMatchObject({ action: 'task.group.policy', targetIds: ['group1'], parameters: { createPolicy: 'managers' } }); expect(requestApi.mock.calls.some(([path]) => path.includes('/execute'))).toBe(false);
  });
  it('uses report IDs and frozen feedback/disposition, never a raw private task target', async () => {
    install(); const { ctx } = mount(); await readReport(); fireEvent.change(screen.getByLabelText('给举报人的处理反馈'), { target: { value: '已核实并处理被举报评论' } }); fireEvent.change(screen.getByLabelText('举报对象处置'), { target: { value: 'delete_comment' } }); fireEvent.click(screen.getByRole('button', { name: '预览反馈并关闭工单' })); fireEvent.change(screen.getByLabelText('给举报人的处理反馈'), { target: { value: '后续编辑未进入前次预览' } }); expect(ctx.openAction.mock.calls[0][0]).toMatchObject({ action: 'task_report.close', targetIds: ['report1'], parameters: { feedback: '已核实并处理被举报评论', disposition: 'delete_comment' } });
  });
  it('allows only feedback when the preserved report points to an unavailable target', async () => {
    install(); requestApi.mockImplementation(async (path) => path.endsWith('/read') ? { ...reportDetail, targetState: { available: false, deleted: true, moderatedDeleted: true, hasComment: true, commentRemoved: false } } : page([report])); const { ctx } = mount(); await readReport(); const select = screen.getByLabelText('举报对象处置'); for (const label of ['管理删除被举报待办', '管理删除被举报评论', '恢复管理删除的待办']) expect(within(select).getByRole('option', { name: label })).toBeDisabled(); expect(within(select).getByRole('option', { name: '仅反馈，不改变任务' })).toBeEnabled(); fireEvent.change(screen.getByLabelText('给举报人的处理反馈'), { target: { value: '对象不可处置，已核对保留材料' } }); fireEvent.click(screen.getByRole('button', { name: '预览反馈并关闭工单' })); expect(ctx.openAction).toHaveBeenCalledWith(expect.objectContaining({ parameters: { feedback: '对象不可处置，已核对保留材料', disposition: 'none' } }));
  });
  it('hides old bodies after deletion and obeys authoritative canRestore=false for preserved shells', async () => {
    install(); mount(); const panel = await readTask(); requestApi.mockResolvedValue({ ...detail, task: { ...detail.task, deletedAt: Date.now(), moderatedDeleted: true, canRestore: false }, comments: detail.comments }); fireEvent.click(within(panel).getByRole('button', { name: '按理由读取待办详情' })); expect(screen.queryByText('GROUP-CURRENT-DESCRIPTION')).not.toBeInTheDocument(); await screen.findByText('此待办已删除，旧正文已隐藏'); expect(screen.queryByText('CURRENT-COMMENT-TEXT')).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: '预览恢复管理删除' })).toBeDisabled(); expect(screen.getByRole('button', { name: '预览管理删除待办' })).toBeDisabled();
  });
  it('clears sensitive evidence on an AdminContext command revision change', async () => {
    install(); const { ctx, rerender } = mount(); await readTask(); rerender(<AdminContext.Provider value={{ ...ctx, revision: 1 }}><TasksPage /></AdminContext.Provider>); expect(screen.queryByText('GROUP-CURRENT-DESCRIPTION')).not.toBeInTheDocument(); expect(screen.queryByText('群任务标题')).not.toBeInTheDocument(); expect(screen.getByLabelText('读取理由')).toHaveValue('');
  });
  it('routes closed reports only to the standard reopen preview', async () => {
    requestApi.mockImplementation(async (path) => path.endsWith('/read') ? { ...reportDetail, report: { ...reportDetail.report, status: 'closed', feedback: '已处理' } } : page([{ ...report, status: 'closed' }])); const { ctx } = mount(); await readReport(); expect(screen.queryByRole('button', { name: '预览反馈并关闭工单' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '预览重新打开工单' })); expect(ctx.openAction).toHaveBeenCalledWith({ action: 'task_report.reopen', targetIds: ['report1'], labels: ['待办举报 report1'], parameters: {} });
  });
  it('requires the actual server preview and administrator reauthentication before executing a task command', async () => {
    let saved!: AdminCommandInput; requestApi.mockImplementation(async (path, options = {}) => {
      if (path === '/api/v1/admin/tasks/search') return groupPage;
      if (path.endsWith('/preview')) { saved = structuredClone(options.body) as AdminCommandInput; return { ...saved, targetCount: 1, targets: [{ id: 'group1', label: '已核对的群', detail: '改为仅群管理者创建' }], impacts: ['仅影响群任务创建策略'], expiresAt: Date.now() + 60000, requiresReauthentication: true }; }
      if (path.endsWith('/reauth')) return { reauthToken: 'ephemeral-task-command' };
      if (path.endsWith('/execute')) return { operationId: saved.operationId, action: saved.action, status: 'completed', total: 1, succeeded: 1, failed: 0, pending: 0, items: [{ id: 'group1', label: '已核对的群', status: 'succeeded', code: null, message: null }], createdAt: 1, updatedAt: 2, jobId: null, secretAvailable: false };
      throw new Error('Unexpected task command path');
    }); window.history.replaceState({}, '', '/admin/tasks'); render(<AdminShell user={actor} onSignOut={vi.fn()} signOutBusy={false} signOutError="" />); await searchGroup(); fireEvent.change(screen.getByLabelText('群待办创建策略'), { target: { value: 'managers' } }); fireEvent.click(screen.getByRole('button', { name: '预览群策略调整' })); expect(requestApi.mock.calls.some(([path]) => path.endsWith('/execute'))).toBe(false); fireEvent.change(screen.getByLabelText('操作理由'), { target: { value: '按当前群治理要求调整' } }); fireEvent.click(screen.getByRole('button', { name: '预览目标与影响' })); await screen.findByRole('heading', { name: '服务端操作预览' }); expect(saved).toMatchObject({ action: 'task.group.policy', targetIds: ['group1'], parameters: { createPolicy: 'managers' } }); expect(requestApi.mock.calls.some(([path]) => path.endsWith('/execute'))).toBe(false); fireEvent.change(screen.getByLabelText('管理员当前密码'), { target: { value: 'local-test-password' } }); fireEvent.click(screen.getByRole('button', { name: '验证身份并执行' })); await waitFor(() => expect(requestApi.mock.calls.some(([path]) => path.endsWith('/execute'))).toBe(true)); const executed = requestApi.mock.calls.find(([path]) => path.endsWith('/execute'))![1]!.body; expect(executed).toEqual({ operationId: saved.operationId, reauthToken: 'ephemeral-task-command' });
  });
});
it('reviews only shared card evidence and links live references to an explicit group without fetching task bodies', () => {
  const value = { id: 'message1', seq: '1', conversation: { title: '对话' }, sender: actor, text: 'STALE-FALLBACK-TEXT', status: 'sent', createdAt: 1, retained: true, attachments: [], removedReason: null, reviewedAt: null } as unknown as AdminMessage;
  const ctx = context(); const view = render(<AdminContext.Provider value={ctx}><MessageEvidence message={{ ...value, taskCard: { kind: 'snapshot', snapshot: { title: '已发送静态标题', description: '已发送静态描述', priority: 'high', dueOn: '2026-09-13', dueTimezone: 'Asia/Shanghai' } } }} /></AdminContext.Provider>); expect(screen.getByText('已发送静态描述')).toBeInTheDocument(); expect(screen.queryByText('STALE-FALLBACK-TEXT')).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: /原任务/ })).not.toBeInTheDocument();
  view.rerender(<AdminContext.Provider value={ctx}><MessageEvidence message={{ ...value, taskCard: { kind: 'live', taskId: 'task-live', groupId: 'group-one' } }} /></AdminContext.Provider>); expect(screen.queryByText('已发送静态描述')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('link', { name: '前往指定群待办治理' })); expect(ctx.navigate).toHaveBeenCalledWith('/admin/tasks?groupId=group-one'); expect(requestApi).not.toHaveBeenCalled();
  view.rerender(<MessageEvidence message={{ ...value, taskCard: { kind: 'unavailable' } }} />); expect(screen.getByText('此待办卡片当前不可用。')).toBeInTheDocument(); view.rerender(<MessageEvidence message={{ ...value, retained: false, taskCard: { kind: 'snapshot', snapshot: { title: 'EXPIRED-PRIVATE-CARD', priority: 'normal', dueOn: null, dueTimezone: 'Asia/Shanghai' } } }} />); expect(screen.queryByText('EXPIRED-PRIVATE-CARD')).not.toBeInTheDocument(); expect(screen.queryByText('STALE-FALLBACK-TEXT')).not.toBeInTheDocument();
});