import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react';
import { api, APIError } from '../lib/api';
import type { AdminAction, AdminIdentity, AdminPage, AdminThresholds } from '../lib/admin-types';

export type ActionRequest = { action: AdminAction; targetIds: string[]; labels: string[]; initial?: { uploadDisabled?: boolean; groupCreationDisabled?: boolean; role?: 'admin' | 'member'; quotaBytes?: number; values?: AdminThresholds }; groupId?: string; parameters?: Record<string, unknown>; parameterSummary?: { label: string; value: string }[] };
export const AdminContext = createContext<{ navigate: (url: string) => void; openAction: (request: ActionRequest) => void; deny: () => void; revision: number }>({ navigate: () => {}, openAction: () => {}, deny: () => {}, revision: 0 });
export const dateText = (value: number | null | undefined) => value == null ? '未知' : new Date(value).toLocaleString('zh-CN');
export const numberText = (value: number | null | undefined) => value == null ? '未知' : value.toLocaleString('zh-CN', { maximumFractionDigits: 2 });
export const bytesText = (value: number | null | undefined) => value == null ? '未知' : value >= 1073741824 ? `${numberText(value / 1073741824)} GiB` : value >= 1048576 ? `${numberText(value / 1048576)} MiB` : `${numberText(value)} B`;
export const errorText = (cause: unknown) => cause instanceof APIError ? [cause.message, ...Object.values(cause.fieldErrors || {})].join(' ') : cause instanceof Error ? cause.message : '请求失败，请重试。';
export const identityText = (value: AdminIdentity) => `${value.nickname} (@${value.username})`;
const statusLabels: Record<string, string> = { active: '正常', available: '可用', reserved: '已预留', uploading: '上传中', not_scanned: '未扫描', quarantined: '已隔离', ready: '已就绪', clean: '扫描通过', infected: '检测到风险', unknown: '未知', processing: '处理中', sent: '已发送', recalled: '已撤回', moderated: '管理处置', purged: '已清除', hidden: '已隐藏', open: '待领取', claimed: '处理中', spam: '垃圾信息', harassment: '骚扰', illegal: '违法内容', other: '其他', message: '消息', group: '群聊', banned: '已封禁', deleting: '注销冷静期', deleted: '已注销', frozen: '已冻结', dissolved: '已解散', pending: '待处理', approved: '已通过', accepted: '已接受', rejected: '已拒绝', cancelled: '已取消', expired: '已到期', revoked: '已撤销', exhausted: '已用尽', resolved: '已恢复', completed: '已完成', partial: '部分成功', failed: '失败', queued: '排队中', running: '执行中', succeeded: '成功', owner: '群主', admin: '群管理员', member: '成员', user: '普通用户', super_admin: '超级管理员' };
// Translate only a complete known enum, leaving free-form descriptions untouched.
export const statusText = (value: string) => Object.hasOwn(statusLabels, value) ? statusLabels[value] : value;
export function queryPath(path: string, values: URLSearchParams | Record<string, string>) { const params = new URLSearchParams(values); for (const [key, value] of params) if (!value) params.delete(key); return `${path}${params.size ? `?${params}` : ''}`; }
export function useResource<T>(path: string) {
  const { deny, revision } = useContext(AdminContext); const [attempt, setAttempt] = useState(0);
  const [state, setState] = useState<{ path: string; revision: number; data?: T; error?: string }>({ path, revision });
  useEffect(() => { const controller = new AbortController(); setState({ path, revision }); void api<T>(path, { signal: controller.signal }).then((data) => { if (!controller.signal.aborted) setState({ path, revision, data }); }).catch((cause) => { if (controller.signal.aborted) return; if (cause instanceof APIError && (cause.status === 401 || cause.status === 403)) deny(); else setState({ path, revision, error: errorText(cause) }); }); return () => controller.abort(); }, [path, revision, attempt, deny]);
  const current = state.path === path && state.revision === revision ? state : { path, revision };
  return { ...current, retry: useCallback(() => setAttempt((value) => value + 1), []) };
}
export function ResourceState({ data, error, retry }: { data?: unknown; error?: string; retry: () => void }) { return error ? <div className="admin-error" role="alert"><p>{error}</p><button className="secondary-button" onClick={retry}>重新加载</button></div> : data === undefined ? <p role="status">正在读取管理数据…</p> : null; }
export function AdminLink({ href, children, className }: { href: string; children: ReactNode; className?: string }) { const { navigate } = useContext(AdminContext); return <a href={href} className={className} onClick={(event) => { if (event.button === 0 && !event.ctrlKey && !event.metaKey && !event.shiftKey && !event.altKey && href.startsWith('/admin')) { event.preventDefault(); navigate(href); } }}>{children}</a>; }
export function PageHeading({ title, description, children }: { title: string; description: string; children?: ReactNode }) { return <header className="admin-heading"><div><p className="eyebrow">同频管理</p><h1 tabIndex={-1}>{title}</h1><p>{description}</p></div>{children}</header>; }
export function DataTable({ caption, headings, children }: { caption: string; headings: string[]; children: ReactNode }) { return <div className="admin-table-scroll" role="region" aria-label={caption} tabIndex={0}><table className="admin-table"><caption>{caption}</caption><thead><tr>{headings.map((heading) => <th scope="col" key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export function Pagination({ page, params, path, cursorKey = 'after' }: { page: AdminPage<unknown>; params: URLSearchParams; path: string; cursorKey?: string }) { const next = new URLSearchParams(params); next.set(cursorKey, page.nextCursor || ''); const first = new URLSearchParams(params); first.delete(cursorKey); return <div className="admin-pagination"><span>共 {numberText(page.total)} 条 · 本页 {page.items.length} 条</span>{params.has(cursorKey) && <AdminLink href={queryPath(path, first)}>回到首页</AdminLink>}{page.nextCursor && <AdminLink href={queryPath(path, next)}>下一页</AdminLink>}</div>; }
export function FilterForm({ path, children }: { path: string; children: ReactNode }) { const { navigate } = useContext(AdminContext); return <form className="admin-filters" onSubmit={(event) => { event.preventDefault(); const params = new URLSearchParams(); for (const [key, value] of new FormData(event.currentTarget)) if (typeof value === 'string' && value.trim()) params.set(key, value.trim()); navigate(queryPath(path, params)); }}><fieldset>{children}<button className="primary-button">应用筛选</button><AdminLink href={path}>重置</AdminLink></fieldset></form>; }
export function SelectFilter({ name, label, value, options }: { name: string; label: string; value: string; options: [string, string][] }) { return <label className="admin-filter"><span>{label}</span><select name={name} defaultValue={value}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
export function ActionButton({ request, children, disabled = false }: { request: ActionRequest; children: ReactNode; disabled?: boolean }) { const { openAction } = useContext(AdminContext); return <button className="secondary-button" disabled={disabled || request.targetIds.length === 0} onClick={() => openAction(request)}>{children}</button>; }
export function EmptyRow({ count }: { count: number }) { return <tr><td colSpan={count}>没有符合条件的记录。</td></tr>; }
export function useSelection() { const [selected, setSelected] = useState<string[]>([]); return { selected, toggle: (id: string, checked: boolean) => setSelected((current) => checked ? [...new Set([...current, id])].slice(0, 100) : current.filter((value) => value !== id)), clear: () => setSelected([]) }; }
