import { useContext, useState } from 'react';
import type { AdminPage } from '../lib/admin-types';
import type { AdminAnnouncement, AnnouncementParameters } from '../lib/admin-s3-types';
import { ActionButton, AdminContext, DataTable, dateText, EmptyRow, FilterForm, identityText, PageHeading, Pagination, queryPath, ResourceState, SelectFilter, statusText, useResource } from './AdminShared';

export function AnnouncementsPage({ params }: { params: URLSearchParams }) {
  const { openAction } = useContext(AdminContext);
  const resource = useResource<AdminPage<AdminAnnouncement>>(queryPath('/api/v1/admin/announcements', { status: params.get('status') || '', after: params.get('after') || '', limit: '50' }));
  const [kind, setKind] = useState<AnnouncementParameters['kind']>('announcement'); const [audience, setAudience] = useState<AnnouncementParameters['audience']>('all');
  const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [users, setUsers] = useState(''); const [groupId, setGroupId] = useState(''); const [scheduled, setScheduled] = useState(false); const [publishAt, setPublishAt] = useState(''); const [error, setError] = useState('');
  return <><PageHeading title="公告与系统通知" description="以系统身份发送；名单在预览时由服务器核定，已接受的任务不代表全部送达。" />
    <section className="admin-panel"><h2>创建公告</h2><form className="admin-s3-form" onSubmit={(event) => { event.preventDefault(); setError(''); const userIds = [...new Set(users.split(/[\s,，]+/).filter(Boolean))]; const at = scheduled ? new Date(publishAt).getTime() : null; if ([...title.trim()].length < 1 || [...title.trim()].length > 100 || [...body.trim()].length < 1 || [...body.trim()].length > 4000) { setError('标题需为 1–100 个字符，正文需为 1–4000 个字符。'); return; } if (audience === 'users' && (!userIds.length || userIds.length > 100)) { setError('请输入 1–100 个不同的账号 ID。'); return; } if (scheduled && (!Number.isFinite(at) || at! <= Date.now() || at! > Date.now() + 30 * 86400000)) { setError('计划时间需在未来 30 天内。'); return; } const parameters: AnnouncementParameters = { kind, title: title.trim(), body: body.trim(), audience, userIds: audience === 'users' ? userIds : [], groupId: audience === 'group' ? groupId.trim() : '', publishAt: at }; openAction({ action: 'announcement.create', targetIds: ['instance'], labels: ['系统公告发送任务'], parameters: { ...parameters }, parameterSummary: [{ label: '标题', value: parameters.title }, { label: '正文', value: parameters.body }, { label: '发送时间', value: at === null ? '立即排队发送' : dateText(at) }, { label: '受众', value: audience === 'all' ? '全站有效账号' : audience === 'users' ? userIds.join('、') : groupId }] }); }}>
      <label>类型<select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="announcement">公告</option><option value="notification">系统通知</option></select></label>
      <label>公告标题<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>公告正文<textarea required rows={5} value={body} onChange={(event) => setBody(event.target.value)} /></label>
      <label>发送对象<select value={audience} onChange={(event) => setAudience(event.target.value as typeof audience)}><option value="all">全站</option><option value="users">指定账号名单</option><option value="group">指定群当前成员</option></select></label>
      {audience === 'users' && <label>账号 ID 名单<textarea required value={users} onChange={(event) => setUsers(event.target.value)} placeholder="使用空格、换行或逗号分隔，最多 100 个" /></label>}{audience === 'group' && <label>群 ID<input required value={groupId} onChange={(event) => setGroupId(event.target.value)} /></label>}
      <label className="admin-check"><input type="checkbox" checked={scheduled} onChange={(event) => setScheduled(event.target.checked)} />定时发布</label>{scheduled && <label>计划发布时间<input aria-label="计划发布时间" required type="datetime-local" value={publishAt} onChange={(event) => setPublishAt(event.target.value)} /><small>按当前设备时区，最多未来 30 天。</small></label>}
      {error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button">预览公告发送</button>
    </form></section>
    <FilterForm path="/admin/announcements"><SelectFilter name="status" label="公告状态" value={params.get('status') || ''} options={['', 'scheduled', 'sending', 'published', 'withdrawn', 'failed'].map((s) => [s, s ? statusText(s) : '全部'])} /></FilterForm><ResourceState {...resource} />
    {resource.data && <><DataTable caption="公告发送记录" headings={['公告', '发布者 / 时间', '真实送达进度', '状态', '操作']}>{resource.data.items.length ? resource.data.items.map((item) => <tr key={item.id}><th scope="row">{item.title}<small>{item.id}</small><details><summary>公告详情</summary><p className="admin-preserve-text">{item.status === 'withdrawn' ? '公告已撤回，正文不再显示。' : item.body}</p><p>受众：{item.audience} · {item.groupId}</p><p>任务：{item.jobId}</p></details></th><td>{identityText(item.creator)}<br />计划 {dateText(item.publishAt)}<br />发布 {dateText(item.publishedAt)}</td><td>{item.deliveredCount} / {item.recipientCount} 人</td><td>{statusText(item.status)}{item.errorCode && <p>{item.errorCode}</p>}</td><td><ActionButton disabled={item.status === 'withdrawn'} request={{ action: 'announcement.withdraw', targetIds: [item.id], labels: [item.title], parameters: {} }}>撤回公告</ActionButton></td></tr>) : <EmptyRow count={5} />}</DataTable><Pagination page={resource.data} params={params} path="/admin/announcements" /><button className="secondary-button" onClick={resource.retry}>刷新发送记录</button></>}
  </>;
}
