import { useContext, useState, type FormEvent } from 'react';
import type { AdminAction, AdminGroup, AdminIdentity, AdminPage } from '../lib/admin-types';
import type { AdminMessage, AdminReportDetail, AdminReportSummary } from '../lib/admin-s2-types';
import { ActionButton, AdminContext, AdminLink, DataTable, dateText, EmptyRow, FilterForm, identityText, PageHeading, Pagination, queryPath, ResourceState, SelectFilter, statusText, useResource } from './AdminShared';
import { MessageEvidence } from './ContentPage';
import { SensitiveReadForm, SensitiveState, useSensitiveRead } from './SensitiveRead';

function ReportResolution({ detail }: { detail: AdminReportDetail }) {
  const { openAction } = useContext(AdminContext); const [feedback, setFeedback] = useState(''); const [choice, setChoice] = useState(''); const [until, setUntil] = useState(''); const [error, setError] = useState('');
  const { report, target } = detail; const matched = target?.id === report.targetId;
  const message = matched && report.targetKind === 'message' && target && 'conversationId' in target && 'text' in target ? target as AdminMessage : null;
  const account = matched && report.targetKind === 'user' && target && 'username' in target ? target as AdminIdentity : null;
  const group = matched && report.targetKind === 'group' && target && 'owner' in target ? target as AdminGroup : null;
  const choices: { key: string; action: AdminAction; targetId: string; label: string }[] = [];
  if (message) { choices.push({ key: 'message-hide', action: 'message.hide', targetId: message.id, label: '隐藏此举报消息' }, { key: 'message-delete', action: 'message.delete', targetId: message.id, label: '管理删除此举报消息' }); if (message.sender) choices.push({ key: 'sender-ban', action: 'user.ban', targetId: message.sender.id, label: `封禁消息发送者 ${identityText(message.sender)}` }, { key: 'sender-mute', action: 'user.mute', targetId: message.sender.id, label: `禁言消息发送者 ${identityText(message.sender)}` }); if (message.conversationId === message.conversation.id) choices.push({ key: 'conversation-freeze', action: 'conversation.freeze', targetId: message.conversationId, label: `冻结消息所属会话 ${message.conversation.title}` }); }
  if (account) choices.push({ key: 'target-ban', action: 'user.ban', targetId: account.id, label: `封禁举报账号 ${identityText(account)}` }, { key: 'target-mute', action: 'user.mute', targetId: account.id, label: `禁言举报账号 ${identityText(account)}` });
  if (group) choices.push({ key: 'group-freeze', action: 'conversation.freeze', targetId: group.id, label: `冻结被举报群 ${group.name}` });
  const chosen = choices.find((item) => item.key === choice);
  function submit(event: FormEvent, reject = false) { event.preventDefault(); if (!feedback.trim()) { setError('请填写发送给举报者的反馈。'); return; } const parameters: Record<string, unknown> = { feedback: feedback.trim() }; if (!reject && chosen) { const disposition: Record<string, unknown> = { action: chosen.action, targetId: chosen.targetId }; if (chosen.action === 'user.mute') { const end = new Date(until).getTime(); if (!Number.isFinite(end) || end <= Date.now() || end > Date.now() + 30 * 86400000) { setError('禁言时间须在未来 30 天内。'); return; } disposition.until = end; } parameters.disposition = disposition; } setError(''); openAction({ action: reject ? 'report.reject' : 'report.resolve', targetIds: [report.id], labels: [`举报工单 ${report.id}`], parameters, parameterSummary: [{ label: '举报者反馈', value: feedback.trim() }, { label: '关联处置', value: reject ? '无（驳回）' : chosen?.label || '无' }, ...(chosen?.action === 'user.mute' && !reject ? [{ label: '禁言截止', value: dateText(new Date(until).getTime()) }] : [])] }); }
  const closed = ['resolved', 'rejected'].includes(report.status);
  return <><section><h3>当前对象证据</h3>{message ? <MessageEvidence message={message} /> : account ? <p>{identityText(account)}</p> : group ? <p>{group.name} · 群主 {identityText(group.owner)} · {statusText(group.status)}</p> : <p className="warning-note">当前未取得匹配的举报对象，不能追加关联处置。</p>}</section><div className="admin-actions">{report.status === 'open' && <ActionButton request={{ action: 'report.claim', targetIds: [report.id], labels: [`举报 ${report.id}`] }}>领取工单</ActionButton>}{closed && <ActionButton request={{ action: 'report.reopen', targetIds: [report.id], labels: [`举报 ${report.id}`] }}>重开工单</ActionButton>}</div>{!closed && <form className="admin-resolution-form" onSubmit={(event) => submit(event)}><label className="form-field">给举报者的反馈<textarea required value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><label className="form-field">可选关联处置<select value={choice} onChange={(event) => setChoice(event.target.value)}><option value="">只处理工单，不追加处置</option>{choices.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>{chosen?.action === 'user.mute' && <label className="form-field">关联禁言截止时间<input type="datetime-local" required value={until} onChange={(event) => setUntil(event.target.value)} /></label>}<p>关联处置只针对当前举报对象及其发送者、所属会话。处置成功后才完成工单。</p>{error && <p role="alert" className="form-error">{error}</p>}<div className="admin-actions"><button className="primary-button">预览处理方案</button><button type="button" className="secondary-button" onClick={(event) => submit(event, true)}>预览驳回反馈</button></div></form>}</>;
}
export function ReportsPage({ params }: { params: URLSearchParams }) {
  const filters = new URLSearchParams(params); filters.delete('id'); filters.set('limit', '50'); const list = useResource<AdminPage<AdminReportSummary>>(queryPath('/api/v1/admin/reports', filters)); const detail = useSensitiveRead<AdminReportDetail>(); const id = params.get('id');
  return <><PageHeading title="举报工单" description="列表只显示元数据，填写读取理由后查看举报说明、对象证据与处理历史。" /><FilterForm path="/admin/reports"><SelectFilter label="工单状态" name="status" value={params.get('status') || ''} options={ [['', '全部'], ['open', '待领取'], ['claimed', '处理中'], ['resolved', '已处理'], ['rejected', '已驳回']] } /><SelectFilter label="举报类别" name="category" value={params.get('category') || ''} options={ [['', '全部'], ['spam', '垃圾信息'], ['harassment', '骚扰'], ['illegal', '违法内容'], ['other', '其他']] } /><SelectFilter label="分派" name="assigned" value={params.get('assigned') || 'all'} options={ [['all', '全部'], ['mine', '分派给我'], ['unassigned', '未分派']] } /></FilterForm><ResourceState {...list} />{list.data && <><DataTable caption="举报工单列表" headings={['工单', '举报者 / 对象', '类别', '状态 / 经办人', '创建 / 更新时间']}>{list.data.items.length ? list.data.items.map((report) => { const next = new URLSearchParams(params); next.set('id', report.id); return <tr key={report.id}><th scope="row"><AdminLink href={queryPath('/admin/reports', next)}>{report.id}</AdminLink></th><td>{identityText(report.reporter)}<small>{statusText(report.targetKind)} · {report.targetId}</small></td><td>{statusText(report.category)}</td><td>{statusText(report.status)}<small>{report.assignedTo ? identityText(report.assignedTo) : '未分派'}</small></td><td>{dateText(report.createdAt)}<br />{dateText(report.updatedAt)}</td></tr>; }) : <EmptyRow count={5} />}</DataTable><Pagination page={list.data} params={filters} path="/admin/reports" /></>}{id && <section className="admin-panel"><h2>举报详情 · {id}</h2><SensitiveReadForm busy={detail.busy} label="读取举报证据" onSubmit={(body) => { void detail.read(`/api/v1/admin/reports/${encodeURIComponent(id)}/read`, { reason: body.reason }); }} /><SensitiveState {...detail} />{detail.data && <><p className="admin-message-text">{detail.data.report.description}</p><p>状态：{statusText(detail.data.report.status)}</p>{detail.data.report.feedback && <p>现有反馈：{detail.data.report.feedback}</p>}<ReportResolution key={`${detail.data.report.id}:${detail.data.report.version}`} detail={detail.data} /><h3>近期处理记录</h3><ol>{detail.data.events.map((event) => <li key={event.id}><strong>{identityText(event.actor)} · {statusText(event.action)}</strong><p>{event.reason}</p><small>{dateText(event.createdAt)}</small></li>)}</ol><button className="text-button" onClick={detail.clear}>清除已读取证据</button></>}</section>}</>;
}
