import { useContext, useState } from 'react';
import type { AdminPage } from '../lib/admin-types';
import type { AdminPolicyVersion, AdminSettings, AdminSiteInvite, PolicyField, PolicyValues } from '../lib/admin-s2-types';
import { ActionButton, AdminContext, DataTable, dateText, EmptyRow, identityText, PageHeading, Pagination, queryPath, ResourceState, statusText, useResource } from './AdminShared';

function policyText(field: PolicyField, value: unknown) { if (value === undefined) return '未设置'; if (typeof value === 'boolean') return value ? '开启' : '关闭'; return field.options?.find((option) => option.value === value)?.label || String(value); }
function PolicyEditor({ settings }: { settings: AdminSettings }) {
  const { openAction } = useContext(AdminContext); const [values, setValues] = useState<PolicyValues>(() => Object.fromEntries(settings.fields.map((field) => [field.key, settings.values[field.key]])));
  const groups = [...new Set(settings.fields.map((field) => field.group))]; const changed = settings.fields.filter((field) => values[field.key] !== settings.values[field.key]);
  return <form onSubmit={(event) => { event.preventDefault(); openAction({ action: 'settings.update', targetIds: ['instance'], labels: ['当前站点策略'], parameters: { expectedVersion: settings.version, values }, parameterSummary: [{ label: '基于版本', value: String(settings.version) }, ...changed.map((field) => ({ label: field.label, value: `${policyText(field, settings.values[field.key])} → ${policyText(field, values[field.key])}` }))] }); }}>
    {groups.map((group) => <fieldset className="admin-panel admin-policy-group" key={group}><legend>{group}</legend><div className="admin-policy-fields">{settings.fields.filter((field) => field.group === group).map((field) => <label className={`form-field ${field.type === 'boolean' ? 'admin-policy-toggle' : ''}`} key={field.key}><span>{field.label}</span>{field.type === 'boolean' ? <input aria-label={field.label} aria-describedby={`policy-help-${field.key}`} type="checkbox" checked={Boolean(values[field.key])} onChange={(event) => setValues({ ...values, [field.key]: event.target.checked })} /> : field.type === 'enum' ? <select aria-label={field.label} aria-describedby={`policy-help-${field.key}`} value={String(values[field.key])} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : field.type === 'integer' ? <input aria-label={field.label} aria-describedby={`policy-help-${field.key}`} type="number" required step={1} min={field.min} max={field.max} value={values[field.key] as number} onChange={(event) => setValues({ ...values, [field.key]: event.target.valueAsNumber })} /> : <textarea aria-label={field.label} aria-describedby={`policy-help-${field.key}`} minLength={field.min} maxLength={field.max} value={String(values[field.key] ?? '')} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} />}<small id={`policy-help-${field.key}`}>{field.help}</small></label>)}</div></fieldset>)}
    <section className="admin-panel"><h2>待提交差异</h2>{changed.length ? <dl className="admin-facts">{changed.map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{policyText(field, settings.values[field.key])} → {policyText(field, values[field.key])}</dd></div>)}</dl> : <p>尚未修改配置。</p>}<p>保存前会核验运行版本并显示服务器预览。缩短保留期不会立即删除数据。</p><button className="primary-button" disabled={!changed.length}>预览配置变更</button></section>
  </form>;
}
function PolicyHistory({ settings, params }: { settings: AdminSettings; params: URLSearchParams }) {
  const resource = useResource<AdminPage<AdminPolicyVersion>>(queryPath('/api/v1/admin/settings/versions', { after: params.get('historyAfter') || '', limit: '50' })); const [selected, setSelected] = useState<AdminPolicyVersion | null>(null);
  const differences = selected ? settings.fields.filter((field) => selected.values[field.key] !== settings.values[field.key]) : [];
  return <section className="admin-panel"><h2>策略版本历史</h2><ResourceState {...resource} />{resource.data && <><DataTable caption="策略版本历史" headings={['版本', '操作者', '时间', '理由', '比较']}>{resource.data.items.length ? resource.data.items.map((version) => <tr key={version.version}><th scope="row">{version.version}</th><td>{version.actor ? identityText(version.actor) : '系统'}</td><td>{dateText(version.createdAt)}</td><td>{version.reason}</td><td><button className="secondary-button" onClick={() => setSelected(version)}>比较版本 {version.version}</button></td></tr>) : <EmptyRow count={5} />}</DataTable><Pagination page={resource.data} params={params} path="/admin/settings" cursorKey="historyAfter" /></>}{selected && <div className="admin-preview"><h3>当前版本 {settings.version} → 历史版本 {selected.version}</h3>{differences.length ? <dl className="admin-facts">{differences.map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{policyText(field, settings.values[field.key])} → {policyText(field, selected.values[field.key])}</dd></div>)}</dl> : <p>可编辑字段没有差异。</p>}<p>回滚会按当前字段规则重新校验并创建新版本，历史版本不会删除。</p><ActionButton disabled={!differences.length} request={{ action: 'settings.rollback', targetIds: ['instance'], labels: ['站点策略回滚'], parameters: { expectedVersion: settings.version, version: selected.version }, parameterSummary: [{ label: '当前版本', value: String(settings.version) }, { label: '回滚来源版本', value: String(selected.version) }, ...differences.map((field) => ({ label: field.label, value: `${policyText(field, settings.values[field.key])} → ${policyText(field, selected.values[field.key])}` }))] }}>预览回滚版本 {selected.version}</ActionButton></div>}</section>;
}
function SiteInvites({ params }: { params: URLSearchParams }) {
  const { openAction } = useContext(AdminContext); const resource = useResource<AdminPage<AdminSiteInvite>>(queryPath('/api/v1/admin/site-invites', { after: params.get('invitesAfter') || '', limit: '50' })); const [uses, setUses] = useState(1); const [hours, setHours] = useState(24);
  return <section className="admin-panel"><h2>站点邀请码</h2><form className="admin-filters" onSubmit={(event) => { event.preventDefault(); openAction({ action: 'site_invite.create', targetIds: ['instance'], labels: ['创建站点注册邀请码'], parameters: { maxUses: uses, expiresInHours: hours }, parameterSummary: [{ label: '最多使用次数', value: String(uses) }, { label: '有效小时数', value: String(hours) }] }); }}><fieldset><label className="admin-filter">最多使用次数<input type="number" min={1} step={1} required value={uses} onChange={(event) => setUses(event.target.valueAsNumber)} /></label><label className="admin-filter">有效小时数<input type="number" min={1} step={1} required value={hours} onChange={(event) => setHours(event.target.valueAsNumber)} /></label><button className="primary-button">预览创建邀请码</button></fieldset></form><p>新邀请码只允许当前管理会话在生成后 5 分钟内领取一次，实际到期时间在领取后显示。</p><ResourceState {...resource} />{resource.data && <><DataTable caption="站点邀请码元数据" headings={['编号', '创建者', '已用 / 上限', '状态', '创建 / 到期', '操作']}>{resource.data.items.length ? resource.data.items.map((invite) => <tr key={invite.id}><th scope="row">{invite.id}</th><td>{invite.createdBy ? identityText(invite.createdBy) : '系统'}</td><td>{invite.used} / {invite.maxUses}</td><td>{statusText(invite.status)}</td><td>{dateText(invite.createdAt)}<br />{dateText(invite.expiresAt)}</td><td><ActionButton disabled={invite.status !== 'active'} request={{ action: 'site_invite.revoke', targetIds: [invite.id], labels: [`站点邀请码 ${invite.id}`] }}>撤销邀请码</ActionButton></td></tr>) : <EmptyRow count={6} />}</DataTable><Pagination page={resource.data} params={params} path="/admin/settings" cursorKey="invitesAfter" /></>}</section>;
}
export function SettingsPage({ params }: { params: URLSearchParams }) {
  const resource = useResource<AdminSettings>('/api/v1/admin/settings'); const data = resource.data;
  return <><PageHeading title="站点策略" description="按服务器给出的可编辑字段修改策略，预览差异后验证身份并应用。"><button className="secondary-button" onClick={resource.retry}>刷新运行配置</button></PageHeading><ResourceState {...resource} />{data && <><p className="admin-meta">当前运行版本 {data.version} · 生效时间 {dateText(data.appliedAt)} · 环境 {data.environment} · 后续请求即时生效</p><section className="admin-panel"><h2>部署与安全只读说明</h2><ul>{data.readOnly.map((text, index) => <li key={index}>{text}</li>)}</ul></section><PolicyEditor key={data.version} settings={data} /><PolicyHistory settings={data} params={params} /><SiteInvites params={params} /></>}</>;
}
