import { useCallback, useContext, useState } from 'react';
import type { AdminGroup, AdminPage } from '../lib/admin-types';
import type { AdminGroupTasks, AdminTaskDetail, AdminTaskReport, AdminTaskReportDetail, AdminTaskSearch } from '../lib/admin-tasks-types';
import { ActionButton, AdminContext, dateText, identityText, PageHeading, queryPath, ResourceState, statusText, useResource } from './AdminShared';
import { SensitiveReadForm, SensitiveState, useSensitiveRead } from './SensitiveRead';

const taskStatuses = { todo: '未开始', doing: '进行中', done: '已完成' };
const taskPriorities = { low: '低', normal: '普通', high: '高' };

export function TasksPage({ initialGroupId = '' }: { initialGroupId?: string } = {}) {
  const parent = useContext(AdminContext); const [denied, setDenied] = useState(false);
  const deny = useCallback(() => { setDenied(true); parent.deny(); }, [parent.deny]);
  if (denied) return <section role="alert"><h1>待办治理权限已失效</h1><p>群待办与举报材料已关闭，请重新验证管理身份。</p></section>;
  return <AdminContext.Provider value={{ ...parent, deny }}><TaskConsole key={parent.revision} initialGroupId={initialGroupId} /></AdminContext.Provider>;
}
function TaskConsole({ initialGroupId }: { initialGroupId: string }) {
  const [tab, setTab] = useState<'groups' | 'reports'>('groups');
  return <div className="admin-tasks-page"><PageHeading title="待办治理" description="群待办按明确群范围和读取理由查询；个人待办仅能从举报提交材料核对。管理处置均先预览目标，再验证身份执行。" /><div className="admin-task-tabs" role="group" aria-label="待办治理范围"><button className="secondary-button" aria-pressed={tab === 'groups'} onClick={() => setTab('groups')}>群待办治理</button><button className="secondary-button" aria-pressed={tab === 'reports'} onClick={() => setTab('reports')}>待办举报工单</button></div>{tab === 'groups' ? <GroupTaskGovernance initialGroupId={initialGroupId} /> : <TaskReportGovernance />}</div>;
}
function GroupPicker({ onSelect }: { onSelect: (group: AdminGroup) => void }) {
  const [query, setQuery] = useState(''); const [after, setAfter] = useState(''); const resource = useResource<AdminPage<AdminGroup>>(queryPath('/api/v1/admin/groups', { q: query, after, limit: '20' }));
  return <section className="admin-task-group-picker" aria-label="查找群编号"><h2>查找群编号</h2><form className="admin-task-inline-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setQuery(String(form.get('groupName') || '').trim()); setAfter(''); }}><label className="form-field">群名关键词<input name="groupName" /></label><button className="secondary-button">查找群</button></form><ResourceState {...resource} />{resource.data && <><ul className="admin-task-records">{resource.data.items.map((group) => <li key={group.id}><div><strong>{group.name}</strong><small>{group.id} · {statusText(group.status)}</small></div><button className="secondary-button" onClick={() => onSelect(group)}>选择此群</button></li>)}</ul>{!resource.data.items.length && <p>没有符合条件的群，请调整群名或输入已知群编号。</p>}<div className="admin-pagination"><span>共 {resource.data.total} 个群</span>{after && <button className="text-button" onClick={() => setAfter('')}>群列表首页</button>}{resource.data.nextCursor && <button className="secondary-button" onClick={() => setAfter(resource.data!.nextCursor!)}>下一页群列表</button>}</div></>}</section>;
}
function GroupTaskGovernance({ initialGroupId }: { initialGroupId: string }) {
  const list = useSensitiveRead<AdminGroupTasks>(); const [groupId, setGroupId] = useState(initialGroupId); const [picker, setPicker] = useState(false); const [search, setSearch] = useState<AdminTaskSearch | null>(null); const [after, setAfter] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState('');
  function load(body: Record<string, unknown>, cursor = '') {
    const group = String(body.groupId || '').trim(); const reason = String(body.reason || '').trim();
    if (!group || reason.length < 3) { setError('请提供明确群编号和至少 3 个字符的读取理由。'); return; }
    const payload: AdminTaskSearch = { groupId: group, reason, query: String(body.query || '').trim(), status: String(body.status || '') as AdminTaskSearch['status'], deleted: String(body.deleted || '') as AdminTaskSearch['deleted'], limit: 30, ...(cursor ? { after: cursor } : {}) };
    setError(''); setSelected(null); setAfter(cursor); setSearch(payload); void list.read('/api/v1/admin/tasks/search', payload as unknown as Record<string, unknown>);
  }
  return <><p className="warning-note">此搜索仅适用于指定群，不提供个人待办列表。标题关键词与读取理由不会写入地址栏或本机存储。</p><button className="secondary-button" aria-expanded={picker} onClick={() => setPicker((value) => !value)}>查找可管理群编号</button>{picker && <GroupPicker onSelect={(group) => { setGroupId(group.id); setPicker(false); }} />}<section aria-label="群待办受控搜索"><SensitiveReadForm busy={list.busy} label="按理由搜索群待办" onSubmit={load}><div className="admin-filters-grid"><label className="form-field">群编号<input name="groupId" required value={groupId} onChange={(event) => setGroupId(event.target.value)} autoComplete="off" /></label><label className="form-field">待办标题关键词<input name="query" autoComplete="off" /></label><label className="form-field">待办状态<select name="status" defaultValue=""><option value="">全部状态</option>{Object.entries(taskStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="form-field">删除状态<select name="deleted" defaultValue=""><option value="">未删除</option><option value="only">仅已删除</option><option value="all">包含已删除</option></select></label></div></SensitiveReadForm>{error && <p role="alert" className="form-error">{error}</p>}<SensitiveState {...list} /></section><div className="admin-task-columns"><section className="admin-panel" aria-label="群待办搜索结果"><h2>群待办搜索结果</h2>{!list.data && !list.busy && !list.error && <p>填写指定群和读取理由后显示结果。</p>}{list.data && <><header><h3>{list.data.group.name}</h3><p>{list.data.group.id} · {statusText(list.data.group.status)} · 群配额 {list.data.group.quota}</p></header><GroupPolicy key={`${list.data.group.id}:${list.data.group.createPolicy}`} group={list.data.group} /><ul className="admin-task-records">{list.data.items.map((task) => <li key={task.id}><div><strong>{task.deletedAt !== null ? '已删除待办' : task.title}</strong><small>{task.id} · {taskStatuses[task.status]} · {taskPriorities[task.priority]}优先级 · 截止 {task.dueOn || '无'}</small>{task.deletedAt !== null && <small>{task.moderatedDeleted ? '管理删除' : '用户删除'} · {dateText(task.deletedAt)}</small>}</div><button className="secondary-button" onClick={() => setSelected(task.id)}>核对待办详情</button></li>)}</ul>{!list.data.items.length && <p>当前群内没有符合这些筛选条件的待办。</p>}<div className="admin-pagination"><span>共 {list.data.total} 条，本页 {list.data.items.length} 条</span>{after && <button className="text-button" disabled={list.busy} onClick={() => load(search! as unknown as Record<string, unknown>)}>群待办首页</button>}{list.data.nextCursor && <button className="secondary-button" disabled={list.busy} onClick={() => load(search! as unknown as Record<string, unknown>, list.data!.nextCursor!)}>按同一理由读取下一页待办</button>}<button className="text-button" onClick={() => { list.clear(); setSelected(null); setSearch(null); }}>清除已读取群待办</button></div></>}</section>{selected && <GroupTaskDetail key={selected} id={selected} onClose={() => setSelected(null)} />}</div></>;
}
function GroupPolicy({ group }: { group: AdminGroupTasks['group'] }) {
  const { openAction } = useContext(AdminContext); const [choice, setChoice] = useState(group.createPolicy);
  return <form className="admin-task-inline-form" onSubmit={(event) => { event.preventDefault(); if (choice === group.createPolicy || group.status === 'dissolved') return; openAction({ action: 'task.group.policy', targetIds: [group.id], labels: [group.name], parameters: { createPolicy: choice }, parameterSummary: [{ label: '允许创建任务的人', value: choice === 'members' ? '当前群成员' : '仅群主和管理员' }] }); }}><label className="form-field">群待办创建策略<select value={choice} disabled={group.status === 'dissolved'} onChange={(event) => setChoice(event.target.value as typeof choice)}><option value="members">当前群成员</option><option value="managers">仅群主和管理员</option></select></label><button className="secondary-button" disabled={choice === group.createPolicy || group.status === 'dissolved'}>预览群策略调整</button></form>;
}
function GroupTaskDetail({ id, onClose }: { id: string; onClose: () => void }) {
  const detail = useSensitiveRead<AdminTaskDetail>(); const [reason, setReason] = useState(''); const [after, setAfter] = useState(''); const task = detail.data?.task;
  function read(value: string, cursor = '') { setReason(value); setAfter(cursor); void detail.read(`/api/v1/admin/tasks/${encodeURIComponent(id)}/read`, { reason: value, after: cursor, limit: 30 }); }
  return <section className="admin-panel admin-task-detail" aria-label="群待办详情"><header className="admin-task-section-heading"><h2>群待办详情 · {id}</h2><button className="text-button" onClick={onClose}>关闭群待办详情</button></header><SensitiveReadForm busy={detail.busy} label="按理由读取待办详情" onSubmit={(body) => read(String(body.reason))} /><SensitiveState {...detail} />{task && <><h3>{task.deletedAt !== null ? '此待办已删除，旧正文已隐藏' : task.title}</h3><dl className="admin-facts"><div><dt>状态</dt><dd>{taskStatuses[task.status]} · {taskPriorities[task.priority]}优先级</dd></div><div><dt>所属群</dt><dd>{task.groupId}</dd></div><div><dt>负责人</dt><dd>{task.assignee ? identityText(task.assignee) : '待认领'}</dd></div><div><dt>创建人</dt><dd>{identityText(task.creator)}</dd></div><div><dt>截止日期</dt><dd>{task.dueOn || '无'}</dd></div><div><dt>版本</dt><dd>{task.version}</dd></div></dl>{task.deletedAt === null ? <><h4>描述</h4><p className="admin-message-text">{task.description || '没有描述。'}</p><h4>检查项</h4>{task.checks.length ? <ul className="admin-task-checks">{task.checks.map((item) => <li key={item.id}><span>{item.done ? '已勾选' : '未勾选'}</span>{item.text}</li>)}</ul> : <p>没有检查项。</p>}<h4>任务评论</h4><ul className="admin-task-comments">{detail.data!.comments.items.map((comment) => <li key={comment.id}><header><strong>{identityText(comment.author)}</strong><time>{dateText(comment.createdAt)}</time></header><p className="admin-message-text">{comment.removed ? '评论已删除，正文不再展示。' : comment.text}</p>{!comment.removed && <ActionButton request={{ action: 'task.comment.delete', targetIds: [comment.id], labels: [`群待办评论 ${comment.id}`] }}>预览删除此评论</ActionButton>}</li>)}</ul>{!detail.data!.comments.items.length && <p>当前页没有评论。</p>}<div className="admin-pagination"><span>评论共 {detail.data!.comments.total} 条</span>{after && <button className="text-button" disabled={detail.busy} onClick={() => read(reason)}>评论首页</button>}{detail.data!.comments.nextCursor && <button className="secondary-button" disabled={detail.busy} onClick={() => read(reason, detail.data!.comments.nextCursor!)}>按同一理由读取下一页评论</button>}</div></> : <p className="warning-note">{task.moderatedDeleted ? '这是管理删除的待办。仅在 30 天恢复期限内允许申请恢复。' : '这是用户自行删除的待办，不能通过管理操作改变其删除意愿。'}</p>}<div className="admin-actions"><ActionButton disabled={task.deletedAt !== null} request={{ action: 'task.delete', targetIds: [task.id], labels: [`群待办 ${task.id}`] }}>预览管理删除待办</ActionButton><ActionButton disabled={!task.canRestore} request={{ action: 'task.restore', targetIds: [task.id], labels: [`群待办 ${task.id}`] }}>预览恢复管理删除</ActionButton><button className="text-button" onClick={detail.clear}>清除已读取任务正文</button></div><p className="field-hint">上述按钮仅打开服务端预览，尚未执行处置；下一步仍需再次验证管理身份。</p></>}</section>;
}
function TaskReportGovernance() {
  const [status, setStatus] = useState<'open' | 'closed'>('open'); const [after, setAfter] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  const list = useResource<AdminPage<AdminTaskReport>>(queryPath('/api/v1/admin/task-reports', { status, after, limit: '30' }));
  return <><p className="warning-note">工单列表仅包含编号、类别、状态与时间，不展示私人任务标题、原任务编号或个人待办列表。读取后仅显示举报提交时的最小材料。</p><label className="form-field">待办举报状态<select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setAfter(''); setSelected(null); }}><option value="open">待处理</option><option value="closed">已关闭</option></select></label><ResourceState {...list} /><div className="admin-task-columns"><section className="admin-panel" aria-label="待办举报元数据"><h2>待办举报工单</h2>{list.data && <><ul className="admin-task-records">{list.data.items.map((report) => <li key={report.id}><div><strong>工单 {report.id}</strong><small>{statusText(report.category)} · {report.status === 'open' ? '待处理' : '已关闭'} · {dateText(report.createdAt)}</small>{report.closedAt !== null && <small>关闭于 {dateText(report.closedAt)}</small>}</div><button className="secondary-button" onClick={() => setSelected(report.id)}>填写理由核对举报材料</button></li>)}</ul>{!list.data.items.length && <p>当前没有{status === 'open' ? '待处理' : '已关闭'}的待办举报。</p>}<div className="admin-pagination"><span>共 {list.data.total} 个工单</span>{after && <button className="text-button" onClick={() => { setAfter(''); setSelected(null); }}>举报首页</button>}{list.data.nextCursor && <button className="secondary-button" onClick={() => { setAfter(list.data!.nextCursor!); setSelected(null); }}>下一页待办举报</button>}</div></>}</section>{selected && <TaskReportDetail key={selected} id={selected} onClose={() => setSelected(null)} />}</div></>;
}
function TaskReportDetail({ id, onClose }: { id: string; onClose: () => void }) {
  const detail = useSensitiveRead<AdminTaskReportDetail>();
  return <section className="admin-panel" aria-label="待办举报提交材料"><header className="admin-task-section-heading"><h2>举报提交材料 · {id}</h2><button className="text-button" onClick={onClose}>关闭举报材料</button></header><SensitiveReadForm busy={detail.busy} label="按理由读取举报材料" onSubmit={(body) => { void detail.read(`/api/v1/admin/task-reports/${encodeURIComponent(id)}/read`, { reason: body.reason }); }} /><SensitiveState {...detail} />{detail.data && <><p>举报人：{identityText(detail.data.report.reporter)} · {statusText(detail.data.report.category)}</p><h3>举报说明</h3><p className="admin-message-text">{detail.data.report.description || '未补充说明。'}</p><section className="admin-task-submitted" aria-label="举报时提交的最小材料"><h3>{detail.data.submitted.title}</h3><p>{detail.data.submitted.scope === 'personal' ? '个人待办的举报材料；不因此开放该账号其他任务。' : '群待办举报材料。'}</p>{detail.data.submitted.description && <p className="admin-message-text">{detail.data.submitted.description}</p>}{detail.data.submitted.comment && <><h4>被举报评论</h4><p className="admin-message-text">{detail.data.submitted.comment}</p></>}<p className="field-hint">这是举报时提交的材料，不代表原任务现在的全部内容。</p></section><ReportDisposition key={`${detail.data.report.id}:${detail.data.report.version}`} detail={detail.data} /><button className="text-button" onClick={detail.clear}>清除已读取举报材料</button></>}</section>;
}
function ReportDisposition({ detail }: { detail: AdminTaskReportDetail }) {
  const { openAction } = useContext(AdminContext); const [feedback, setFeedback] = useState(''); const [disposition, setDisposition] = useState<'none' | 'delete_task' | 'delete_comment' | 'restore_task'>('none');
  const state = detail.targetState; const choices = [ ['none', '仅反馈，不改变任务', true], ['delete_task', '管理删除被举报待办', state.available && !state.deleted], ['delete_comment', '管理删除被举报评论', state.available && !state.deleted && state.hasComment && !state.commentRemoved], ['restore_task', '恢复管理删除的待办', state.available && state.deleted && state.moderatedDeleted] ] as const;
  return <section className="admin-task-resolution"><h3>当前可处置状态</h3><p>{!state.available ? '原对象当前不可处置；仍可记录反馈。' : state.deleted ? state.moderatedDeleted ? '原任务处于管理删除状态，恢复期限由服务端预览核对。' : '原任务已由用户删除，不允许管理恢复。' : '原任务当前可用。'}{state.hasComment && (state.commentRemoved ? ' 被举报评论已删除。' : ' 被举报评论尚未删除。')}</p>{detail.report.feedback && <p className="admin-message-text">已有反馈：{detail.report.feedback}</p>}{detail.report.status === 'closed' ? <ActionButton request={{ action: 'task_report.reopen', targetIds: [detail.report.id], labels: [`待办举报 ${detail.report.id}`], parameters: {} }}>预览重新打开工单</ActionButton> : <form onSubmit={(event) => { event.preventDefault(); if (!feedback.trim() || !choices.some(([key, , enabled]) => key === disposition && enabled)) return; openAction({ action: 'task_report.close', targetIds: [detail.report.id], labels: [`待办举报 ${detail.report.id}`], parameters: { feedback: feedback.trim(), disposition }, parameterSummary: [{ label: '处理反馈', value: feedback.trim() }, { label: '对象处置', value: choices.find(([key]) => key === disposition)![1] }] }); }}><label className="form-field">给举报人的处理反馈<textarea required rows={4} maxLength={1000} value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><label className="form-field">举报对象处置<select value={disposition} onChange={(event) => setDisposition(event.target.value as typeof disposition)}>{choices.map(([key, label, enabled]) => <option key={key} value={key} disabled={!enabled}>{label}</option>)}</select></label><p className="field-hint">处理选择会固定在接下来的预览中，确认目标后再验证身份执行。</p><button className="primary-button" disabled={!feedback.trim()}>预览反馈并关闭工单</button></form>}</section>;
}