import { actor, actorId, state, uid, now, save, publish, summary, page, must, matches, audit, DemoError, type Row } from './state';
import { adminUser, adminGroup, adminFile, adminMessage, memberView, inviteView, applicationView, fileBlob } from './models';
import { zipText, sha256 } from './archive';

import policyCatalog from '../data/policy.json';
const policyFields = policyCatalog.fields;

const operationBlob = (op: Row) => zipText({ 'DEMO-README.txt': '此归档仅含浏览器演示数据，不是可恢复到正式服务器的生产备份。\n', 'demo-data.json': op.archiveText || JSON.stringify({ demo: true, operation: op.id }, null, 2) });
function adminTask(t: Row) { return { ...t, groupId: t.groupId, moderatedDeleted: !!t.moderatedDeleted, canRestore: !!t.deletedAt, creator: summary(t.creatorId), assignee: summary(t.assigneeId), checks: t.checkItems.map((c: Row) => ({ ...c, done: Number(c.done) })) }; }
function reportView(r: Row) { return { ...r, reporter: summary(r.reporterId), assignedTo: summary(r.assignedToId) }; }
function changedGroup(cid: string) { const c = state.conversations.find(c => c.id === cid); if (c) { c.version++; c.updatedAt = now(); publish('conversation.updated', cid, cid); } }
function genericFilter(items: Row[], q: URLSearchParams | Row) { const get = (key: string) => q instanceof URLSearchParams ? q.get(key) : q[key]; return items.filter(i => matches(i, get('q') || get('query') || '') && (!get('status') || get('status') === 'all' || i.status === get('status'))); }
async function applyCommand(command: Row) {
  const { action, targetIds: ids, parameters: p, reason } = command.input;
  for (const id of ids.length ? ids : ['site']) {
    const u = state.users.find(u => u.id === id); const c = state.conversations.find(c => c.id === id); const m = state.messages.find(m => m.id === id); const f = state.files.find(f => f.id === id); const t = state.tasks.find(t => t.id === id);
    if (action === 'user.ban' && u) { u.status = 'banned'; u.statusReason = reason; }
    if (action === 'user.unban' && u || action === 'user.restore' && u) { u!.status = 'active'; u!.statusReason = ''; }
    if (action === 'user.mute' && u) { u.restrictions.mutedUntil = p.until || p.mutedUntil || now() + (p.minutes || 60) * 60000; u.restrictions.muteReason = reason; }
    if (action === 'user.unmute' && u) { u.restrictions.mutedUntil = null; u.restrictions.muteReason = ''; }
    if (action === 'user.restrict' && u) Object.assign(u.restrictions, p, { reason });
    if (action === 'user.quota' && u) u.quotaBytes = p.bytes || p.quotaBytes;
    if (action === 'user.password_reset' && u) { u.manualRecoveryCode = 'DEMO-MANUAL-' + uid('recovery'); command.secret = { credential: u.manualRecoveryCode, expiresAt: now() + 600000, username: u.username, kind: 'manual_password_reset' }; command.secretAvailable = true; }
    if (action === 'session.revoke') state.sessions.filter(s => s.id === id).forEach(s => s.revokedAt = now());
    if (action === 'user.logout_all') state.sessions.filter(s => s.userId === id).forEach(s => s.revokedAt = now());
    if (action === 'relationship.remove') { const parts = id.replace(/^relation_/, '').split('~'); if (parts.length === 2) for (const [a, b] of [parts, parts.toReversed()]) state.contacts[a] = (state.contacts[a] || []).filter(x => x !== b); publish('contacts.changed', id); }
    if (action === 'friend_request.cancel') { const r = state.requests.find(r => r.id === id); if (r) r.status = 'cancelled'; publish('contacts.changed', id); }
    if (action === 'conversation.freeze' && c) c.status = 'frozen';
    if (action === 'conversation.unfreeze' && c) c.status = 'active';
    if (action === 'group.dissolve' && c) { c.status = 'dissolved'; publish('access.revoked', c.id, c.id, (state.members[c.id] || []).map(m => m.userId)); }
    if (action.startsWith('group.member.') || action === 'group.owner.change') {
      const cid = p.groupId || p.conversationId || c?.id || Object.keys(state.members).find(cid => state.members[cid].some(m => m.periodId === id));
      const target = p.userId || p.targetUserId || p.memberId || (c ? null : id); const members = state.members[cid] || []; const member = members.find(m => m.userId === target || m.periodId === target);
      if (member) { if (action === 'group.member.role') member.role = p.role; if (action === 'group.member.mute') member.mutedUntil = p.mutedUntil || p.until || now() + 3600000; if (action === 'group.member.unmute') member.mutedUntil = null; if (action === 'group.member.remove') { state.members[cid] = members.filter(m => m !== member); publish('access.revoked', cid, cid, [member.userId]); } if (action === 'group.owner.change') { members.forEach(m => { if (m.role === 'owner') m.role = 'member'; }); member.role = 'owner'; } changedGroup(cid); }
    }
    if (action === 'group.invite.revoke') { const i = state.invitations.find(i => i.id === id); if (i) { i.revokedAt = now(); changedGroup(i.conversationId); } }
    if (action.startsWith('message.') && m) { if (action === 'message.review') { m.reviewedAt = now(); m.reviewedById = actorId(); } if (['message.hide','message.delete'].includes(action)) { m.status = 'moderated'; m.moderationKind = action === 'message.hide' ? 'hidden' : 'deleted'; m.removedReason = reason; m.removedAt = now(); } if (action === 'message.restore') { m.status = 'sent'; m.moderationKind = null; } m.version = (m.version || 1) + 1; publish('message.updated', m.id, m.conversationId); }
    if (action.startsWith('file.') && f) { f.governance = action === 'file.release' ? 'available' : action === 'file.revoke' ? 'revoked' : 'quarantined'; f.governanceReason = reason; f.state = f.governance === 'available' ? 'ready' : 'quarantined'; f.version++; publish('message.updated', f.messageId || f.id, f.conversationId); }
    if (action.startsWith('report.')) { const r = state.reports.find(r => r.id === id); if (r) { r.status = ({ 'report.claim': 'claimed', 'report.reopen': 'open', 'report.reject': 'rejected', 'report.resolve': 'resolved' } as Row)[action]; r.assignedToId = action === 'report.claim' ? actorId() : r.assignedToId; r.feedback = p.feedback || reason; r.updatedAt = now(); r.version++; r.events.push({ id: uid('reportevent'), actor: summary(actorId()), action, reason, createdAt: now() }); } }
    if (action === 'task.delete' && t) { t.deletedAt = now(); t.moderatedDeleted = true; t.version++; publish('task.deleted', t.id, t.groupId); }
    if (action === 'task.restore' && t) { t.deletedAt = null; t.moderatedDeleted = false; t.version++; publish('task.restored', t.id, t.groupId); }
    if (action === 'task.comment.delete') { for (const [tid, comments] of Object.entries(state.comments)) for (const comment of comments) if (comment.id === id) { comment.removed = true; comment.text = ''; publish('task.updated', tid, state.tasks.find(t => t.id === tid)?.groupId); } }
    if (action === 'task.group.policy') { state.taskPolicies[p.groupId || id] = p.createPolicy; publish('task.policy.changed', p.groupId || id, p.groupId || id); }
    if (action.startsWith('task_report.')) { const r = state.taskReports.find(r => r.id === id); if (r) { r.status = action.endsWith('reopen') ? 'open' : 'closed'; r.feedback = p.feedback || reason; r.closedAt = r.status === 'closed' ? now() : null; r.version++; } }
    if (u) { u.version++; publish('account.changed', u.id, null, [u.id]); }
    if (c) changedGroup(c.id);
    audit(action, id, reason, p);
  }
  if (action === 'settings.update') { state.policyVersions.unshift({ version: state.policy.version, actor: summary(actorId()), reason, createdAt: now(), values: { ...state.policy } }); Object.assign(state.policy, p.values || p.changes || p); state.policy.version++; publish('task.policy.changed', 'site'); }
  if (action === 'settings.rollback') { const v = must(state.policyVersions.find(v => v.version === (p.version || p.targetVersion))); const next = state.policy.version + 1; Object.assign(state.policy, v.values); state.policy.version = next; publish('task.policy.changed', 'site'); }
  if (action === 'monitoring.thresholds') { state.policy.monitoring_thresholds = { ...state.policy.monitoring_thresholds, ...(p.values || p.thresholds || p) }; state.policy.version++; }
  if (action === 'site_invite.create') { const i = { id: uid('siteinvite'), createdBy: summary(actorId()), createdAt: now(), expiresAt: now() + (p.expiresHours || 24) * 3600000, maxUses: p.maxUses || 1, used: 0, revokedAt: null, status: 'active' }; Object.assign(i, { code: 'DEMO-SITE-INVITE-' + i.id }); state.siteInvites.unshift(i); command.secret = { credential: 'DEMO-SITE-INVITE-' + i.id, expiresAt: i.expiresAt, username: '', kind: 'site_invite' }; command.secretAvailable = true; }
  if (action === 'site_invite.revoke') state.siteInvites.filter(i => ids.includes(i.id)).forEach(i => { i.revokedAt = now(); i.status = 'revoked'; });
  if (action === 'announcement.create') { const a = { ...p, id: uid('announcement'), kind: p.kind || 'announcement', creator: summary(actorId()), status: p.publishAt && p.publishAt > now() ? 'scheduled' : 'published', recipientCount: state.users.length, deliveredCount: state.users.length, publishAt: p.publishAt || now(), publishedAt: now(), withdrawnAt: null, createdAt: now(), errorCode: null, version: 1, jobId: uid('job') }; state.announcements.unshift(a); state.notifications.unshift({ id: uid('n'), userId: '*', type: 'system.notice', entityRef: a.id, text: a.title, createdAt: now(), readBy: [] }); publish('notification.created', a.id); }
  if (action === 'announcement.withdraw') { state.announcements.filter(a => ids.includes(a.id)).forEach(a => { a.status = 'withdrawn'; a.withdrawnAt = now(); a.body = ''; }); publish('notification.updated', ids[0]); }
  if (action === 'administrator.invite' || action === 'administrator.factor_reset') { const userId = p.userId || ids[0]; state.adminInvitations.unshift({ id: uid('admininvite'), userId, inviterId: actorId(), purpose: action.endsWith('factor_reset') ? 'factor_reset' : 'grant', status: 'pending', createdAt: now(), expiresAt: now() + 86400000 }); }
  if (action === 'administrator.cancel') state.adminInvitations.filter(i => ids.includes(i.id)).forEach(i => i.status = 'cancelled');
  if (action === 'administrator.revoke') { if (state.users.filter(u => u.siteRole === 'super_admin' && !ids.includes(u.id)).length === 0) throw new DemoError(409, 'LAST_ADMINISTRATOR', '必须保留至少一位可用演示管理员。'); state.users.filter(u => ids.includes(u.id)).forEach(u => { u.siteRole = 'user'; publish('account.changed', u.id, null, [u.id]); }); }
  if (['backup.create','backup.verify','backup.drill','export.create','storage.cleanup'].includes(action)) {
    const op = { id: uid('operation'), kind: action, status: 'running', creator: summary(actorId()), createdAt: now(), updatedAt: now(), expiresAt: now() + 86400000, progress: 0, total: 100, bytes: 0, message: '正在处理浏览器演示数据', errorCode: null, result: {}, jobId: uid('job'), requestId: uid('req'), canCancel: true, canRetry: false, canDownload: false, sha256: null, backupClass: p.backupClass || null, archiveText: JSON.stringify({ demo: true, generatedAt: now(), kind: action, users: state.users.map(u => ({ ...u, password: undefined })), conversations: state.conversations, messages: state.messages, tasks: state.tasks, audit: state.audit }, null, 2) } as Row;
    state.operations.unshift(op); command.jobId = op.jobId;
    for (const [delay, progress] of [[700,25],[1400,60],[2100,100]]) setTimeout(() => { void (async () => { if (op.status === 'cancelled') return; op.progress = progress; op.updatedAt = now(); if (progress === 100) { op.status = 'completed'; op.canCancel = false; op.message = action === 'backup.drill' ? '演示恢复演练完成，未写入任何服务器' : action === 'backup.verify' ? '演示清单核对完成' : '演示操作完成'; op.canDownload = ['backup.create','export.create'].includes(action); op.result = { demo: true, integrity: 'ok', activationAllowed: false, verifiedFiles: state.files.length, rows: state.messages.length, message: '仅处理浏览器内演示数据' }; if (op.canDownload) { const blob = operationBlob(op); op.bytes = blob.size; op.sha256 = await sha256(blob); } } save(); })(); }, delay);
  }
  if (action === 'operation.cancel') state.operations.filter(o => ids.includes(o.id)).forEach(o => { o.status = 'cancelled'; o.canCancel = false; o.canRetry = true; o.message = '演示任务已取消'; });
  if (action === 'operation.retry' || action === 'job.retry') state.operations.filter(o => ids.includes(o.id) || ids.includes(o.jobId)).forEach(o => { o.status = 'completed'; o.progress = o.total; o.canRetry = false; o.message = '演示重试完成'; });
  command.status = 'completed'; command.succeeded = command.total; command.failed = 0; command.pending = 0; command.updatedAt = now(); command.items.forEach((i: Row) => { i.status = 'succeeded'; }); save();
}

export async function adminRoute(path: string, method: string, body: Row, q: URLSearchParams): Promise<any> {
  if (!path.startsWith('/admin')) return undefined;
  const me = actor(); if (me.siteRole !== 'super_admin') throw new DemoError(403, 'FORBIDDEN', '请在演示控制中切换到管理员身份。');
  const sub = path.slice(6);
  if (sub === '/auth') return { user: { ...me, password: undefined } };
  if (sub === '/commands/preview') {
    if (!String(body.reason || '').trim()) throw new DemoError(422, 'REASON_REQUIRED', '请填写操作理由。');
    state.commands[body.operationId] = { operationId: body.operationId, action: body.action, status: 'queued', total: Math.max(1, body.targetIds.length), succeeded: 0, failed: 0, pending: Math.max(1, body.targetIds.length), items: (body.targetIds.length ? body.targetIds : ['site']).map((id: string) => ({ id, label: summary(id)?.nickname || state.conversations.find(c => c.id === id)?.title || id, status: 'pending', code: null, message: null })), createdAt: now(), updatedAt: now(), jobId: null, secretAvailable: false, input: body };
    save(); return { operationId: body.operationId, action: body.action, reason: body.reason, targetCount: Math.max(1, body.targetIds.length), targets: state.commands[body.operationId].items.map((i: Row) => ({ ...i, detail: '当前浏览器中的演示对象' })), impacts: ['将更新本地演示数据，相关演示页面会反映结果。', '不会连接真实后台，可通过演示控制恢复初始数据。'], expiresAt: now() + 300000, requiresReauthentication: true };
  }
  if (sub === '/commands/execute') { const c = must(state.commands[body.operationId]); if (c.status !== 'completed') await applyCommand(c); return c; }
  const command = sub.match(/^\/commands\/([^/]+)(?:\/(secret))?$/); if (command) { const c = must(state.commands[command[1]]); if (command[2]) return must(c.secret); return c; }
  if (sub === '/overview') { const metrics = [ ['users','注册用户',state.users.length,'人','/admin/users'], ['active','活跃用户',5,'人','/admin/sessions'], ['messages','聊天消息',state.messages.length,'条','/admin/content'], ['groups','活跃群聊',state.conversations.filter(c => c.kind === 'group' && c.status === 'active').length,'个','/admin/groups'], ['uploads','附件数量',state.files.length,'个','/admin/files'], ['reports','待处理举报',state.reports.filter(r => ['open','claimed'].includes(r.status)).length,'件','/admin/reports'] ]; return { window: q.get('window') || '24h', from: now() - 86400000, to: now(), generatedAt: now(), metrics: metrics.map(([key,label,value,unit,href]) => ({ key,label,value,unit,href,description: '演示数据汇总' })), trends: Array.from({ length: 12 }, (_, i) => ({ at: now() - (11-i)*7200000, registrations: i%3, messages: 4 + (i*7)%19, uploads: i%4 })), processStartedAt: now() - 7200000 }; }
  if (sub === '/monitoring') { const samples = Array.from({ length: 12 }, (_, i) => ({ sampledAt: now() - (11-i)*10000, uptimeSeconds: 7200 + i*10, rssBytes: (82+i%4)*1048576, cpuPercent: 2.1+i%5, threads: 8, requests: 340+i*8, serverErrors: 0, clientErrors: 0, latencyP95Ms: 12+i%6, wsRequests: 200+i*4, wsErrors: 0, wsLatencyP95Ms: 8, dbWaitP95Ms: 1, dbWrites: 180+i*4, dbWriteErrors: 0 })); return { processStartedAt: now()-7200000, sampledAt: now(), latest: samples.at(-1), samples, storage: { totalBytes: 107374182400, freeBytes: 75161927680, usedPercent: 30, databaseBytes: 2097152, walBytes: 32768, attachmentBytes: state.files.reduce((s,f) => s+f.size,0), chargedBytes: state.files.reduce((s,f) => s+f.size,0) }, queues: { pending: 0, running: state.operations.filter(o => o.status === 'running').length, completed: state.operations.filter(o => o.status === 'completed').length, failed: 0, oldestPendingAt: null }, alerts: page([]), thresholds: { cpuPercent: 85, memoryMiB: 1024, diskPercent: 90, httpP95Ms: 500, dbWaitMs: 200, failedJobs: 5, pendingJobs: 100, ...state.policy.monitoring_thresholds }, policyVersion: state.policy.version }; }
  if (sub === '/alerts' || sub === '/logs') return page([]);
  if (sub === '/users') return page(genericFilter(state.users.map(adminUser), q), q);
  if (/^\/users\/[^/]+$/.test(sub)) { const u = must(state.users.find(u => u.id === sub.split('/')[2])); return { user: adminUser(u), ownedGroups: page(state.conversations.filter(c => state.members[c.id]?.some(m => m.userId === u.id && m.role === 'owner')).map(adminGroup)) }; }
  if (sub === '/sessions') return page(state.sessions.filter(s => !q.get('userId') || s.userId === q.get('userId')).map(s => ({ ...s, user: summary(s.userId), active: !s.revokedAt, current: s.id === 'session_' + me.id, connectionCount: s.revokedAt ? 0 : 1 })), q);
  if (sub === '/connections') return page(state.sessions.filter(s => !s.revokedAt && (!q.get('userId') || s.userId === q.get('userId'))).map(s => ({ id: 'conn_' + s.id, userId: s.userId, sessionId: s.id, connectedAt: s.lastSeenAt })), q);
  if (sub === '/relations') { const pairs = new Set<string>(); for (const [a, ids] of Object.entries(state.contacts)) for (const b of ids) pairs.add([a,b].sort().join('~')); return page(genericFilter([...pairs].map(pair => ({ id: 'relation_' + pair, kind: 'friendship', users: pair.split('~').map(summary), status: 'active', createdAt: now()-86400000, updatedAt: now(), conversationId: state.conversations.find(c => c.kind === 'direct' && pair.split('~').every(id => c.userIds.includes(id)))?.id || null, version: 1 })), q), q); }
  if (sub === '/groups') return page(genericFilter(state.conversations.filter(c => c.kind === 'group').map(adminGroup), q), q);
  const group = sub.match(/^\/groups\/([^/]+)(?:\/(members|invites|applications))?$/);
  if (group) { const c = must(state.conversations.find(c => c.id === group[1])); const members = (state.members[c.id] || []).map(m => ({ ...memberView(m), id: m.periodId, visibleFromSeq: '1', writeVersion: c.version })); const invites = state.invitations.filter(i => i.conversationId === c.id).map(i => ({ ...inviteView(i), status: i.revokedAt ? 'revoked' : 'active' })); const applications = state.applications.filter(a => a.conversationId === c.id).map(applicationView); if (group[2]) return page(({ members, invites, applications } as Record<string, Row[]>)[group[2]], q); return { group: adminGroup(c), members: page(members), invites: page(invites), applications: page(applications) }; }
  if (sub === '/content/search') { audit('message.search', body.conversationId || null, body.reason); save(); return page(genericFilter(state.messages.filter(m => (!body.conversationId || m.conversationId === body.conversationId) && (!body.senderId || m.senderId === body.senderId) && (!body.kind || state.conversations.find(c => c.id === m.conversationId)?.kind === body.kind)).map(adminMessage), body), body); }
  const content = sub.match(/^\/content\/([^/]+)\/read$/); if (content) { const m = must(state.messages.find(m => m.id === content[1])); audit('message.read', m.id, body.reason); save(); return { message: adminMessage(m), items: state.messages.filter(x => x.conversationId === m.conversationId).map(adminMessage), hasBefore: false, hasAfter: false }; }
  if (sub === '/files/search') { audit('file.search', null, body.reason); save(); return page(genericFilter(state.files.filter(f => (!body.kind || f.kind === body.kind) && (!body.ownerId || f.ownerId === body.ownerId) && (!body.governance || f.governance === body.governance)).map(adminFile), body), body); }
  const file = sub.match(/^\/files\/([^/]+)\/(read|content)$/); if (file) { const f = must(state.files.find(f => f.id === file[1])); audit('file.' + file[2], f.id, body.reason); save(); return file[2] === 'content' ? fileBlob(f.id) : { file: adminFile(f) }; }
  if (sub === '/reports') return page(genericFilter(state.reports.map(reportView), q), q);
  const report = sub.match(/^\/reports\/([^/]+)\/read$/); if (report) { const r = must(state.reports.find(r => r.id === report[1])); const m = state.messages.find(m => m.id === r.targetId); audit('report.read', r.id, body.reason); save(); return { report: reportView(r), events: r.events || [], target: m ? adminMessage(m) : summary(r.targetId) }; }
  if (sub === '/settings') return { version: state.policy.version, values: Object.fromEntries(policyFields.map(f => [f.key, state.policy[f.key]])), fields: policyFields, appliedAt: now(), effect: 'immediate', environment: '浏览器演示', readOnly: ['运行指标为示例数据', '演示内容不会写入真实后台'] };
  if (sub === '/settings/versions') return page(state.policyVersions, q);
  if (sub === '/site-invites') return page(state.siteInvites, q);
  if (sub === '/announcements') return page(genericFilter(state.announcements, q), q);
  if (sub === '/administrators') return { administrators: page(state.users.filter(u => u.siteRole === 'super_admin').map(u => ({ user: summary(u.id), status: u.status, usable: u.status === 'active', hasSecondFactor: true, sessionCount: state.sessions.filter(s => s.userId === u.id && !s.revokedAt).length, lastSeenAt: now(), version: u.version })), q), invitations: state.adminInvitations.map(i => ({ ...i, user: summary(i.userId), inviter: summary(i.inviterId) })) };
  if (sub === '/audit') return page(state.audit.filter(a => (!q.get('actorId') || a.actor?.id === q.get('actorId')) && (!q.get('action') || a.action.includes(q.get('action')!)) && (!q.get('subjectId') || a.subjectId === q.get('subjectId'))), q);
  if (sub === '/operations') return page(genericFilter(state.operations, q), q);
  if (sub === '/jobs') return page(state.operations.map(o => ({ id: o.jobId, kind: o.kind, entityId: o.id, status: o.status, attempts: 1, createdAt: o.createdAt, runAfter: o.createdAt, leaseUntil: null, completedAt: o.status === 'completed' ? o.updatedAt : null, errorCode: o.errorCode, operationId: o.id, canRetry: o.canRetry, limitation: '仅演示任务，不执行系统操作' })), q);
  const operation = sub.match(/^\/operations\/([^/]+)\/download$/); if (operation) { const op = must(state.operations.find(o => o.id === operation[1])); if (!op.canDownload) throw new DemoError(409, 'NOT_READY', '演示归档尚未完成。'); audit('operation.download', op.id, body.reason); save(); return operationBlob(op); }
  if (sub === '/tasks/search') { const c = must(state.conversations.find(c => c.id === body.groupId), '请选择一个演示群。'); audit('task.search', c.id, body.reason); save(); const rows = state.tasks.filter(t => t.groupId === c.id && (body.deleted === 'only' ? !!t.deletedAt : body.deleted === 'all' ? true : !t.deletedAt)); return { ...page(genericFilter(rows.map(adminTask), body), body), group: { id: c.id, name: c.title, status: c.status, createPolicy: state.taskPolicies[c.id] || 'members', quota: 1000 } }; }
  const task = sub.match(/^\/tasks\/([^/]+)\/read$/); if (task) { const t = must(state.tasks.find(t => t.id === task[1])); return { task: adminTask(t), comments: page((state.comments[t.id] || []).map(c => ({ ...c, author: summary(c.authorId) })), body) }; }
  if (sub === '/task-reports') return page(genericFilter(state.taskReports, q), q);
  const taskReport = sub.match(/^\/task-reports\/([^/]+)\/read$/); if (taskReport) { const r = must(state.taskReports.find(r => r.id === taskReport[1])); const t = state.tasks.find(t => t.id === r.taskId); return { report: { ...r, reporter: summary(r.reporterId), feedback: r.feedback || null }, submitted: { title: t?.title || '已移除的任务', scope: t?.scope || 'group', groupId: t?.groupId || null, description: r.description }, targetState: { available: !!t, deleted: !!t?.deletedAt, moderatedDeleted: !!t?.moderatedDeleted, hasComment: !!r.commentId, commentRemoved: false } }; }
  return undefined;
}
