import { useEffect, useState } from 'react';
import { SlidersHorizontal, X, RotateCcw, ShieldCheck, Wifi, WifiOff, UserRound } from 'lucide-react';
import { actorId, state, setIdentity, setOffline, offline, resetState, PASSWORD, storageWarning } from './state';
import { autoReply, setAutoReply } from './core';
import { navigate } from './navigation';
import './controls.css';
export function Controls() {
  const [open, setOpen] = useState(false); const [, refresh] = useState(0); const [reset, setReset] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { const update = () => refresh(x => x+1); const show = (e: Event) => setNotice((e as CustomEvent).detail); window.addEventListener('demo:state', update); window.addEventListener('demo:notice', show); return () => { window.removeEventListener('demo:state', update); window.removeEventListener('demo:notice', show); }; }, []);
  function identity(id: string | null, path = '/') { setIdentity(id); setOffline(false); navigate(path); window.dispatchEvent(new Event('demo:identity')); refresh(x=>x+1); }
  return <div className="demo-control-root"><button className="demo-control-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><span className="demo-dot"/><SlidersHorizontal size={15}/>演示控制</button>{open && <section className="demo-control-panel" aria-label="演示控制台"><header><div><strong>完整前端演示</strong><small>只在当前浏览器保存 · 无后台通信</small></div><button onClick={() => setOpen(false)} aria-label="关闭演示控制"><X size={18}/></button></header><label htmlFor="demo-identity">切换演示身份</label><select id="demo-identity" value={actorId() || ''} onChange={e => identity(e.target.value || null)}><option value="">未登录 · 登录与注册</option>{state.users.filter(u => u.status !== 'deleted').map(u => <option key={u.id} value={u.id}>{u.nickname} · {u.siteRole === 'super_admin' ? '超级管理员' : u.username}</option>)}</select><div className="demo-control-actions"><button onClick={() => identity('u_lin')}><UserRound size={15}/>聊天与协作</button><button onClick={() => identity('u_admin', '/admin')}><ShieldCheck size={15}/>管理后台</button><button onClick={() => { setOffline(!offline); refresh(x=>x+1); }}>{offline ? <WifiOff size={15}/> : <Wifi size={15}/>} {offline ? '恢复演示联网' : '模拟离线'}</button><button onClick={() => setReset(true)}><RotateCcw size={15}/>恢复初始数据</button></div><label className="demo-check"><input type="checkbox" checked={autoReply} onChange={e => { setAutoReply(e.target.checked); refresh(x=>x+1); }}/>私聊对象自动回复</label><p>演示密码：<code>{PASSWORD}</code><br/>验证码：<code>1234</code>　动态码：<code>123456</code></p><p className="demo-hint">监控、通知授权、扫描与备份均为本地演示。聊天、资料、任务等修改可刷新保留；下载会生成真实本地文件。</p>{(notice || storageWarning) && <p role="status">{storageWarning || notice}</p>}{reset && <div className="demo-reset"><p>恢复初始人物、消息、待办和管理记录？只清理本演示的数据。</p><button onClick={() => { resetState(); for (const key of Object.keys(localStorage)) if (key.startsWith('tongpin-demo-')) localStorage.removeItem(key); indexedDB.deleteDatabase('tongpin-demo-local-v1'); indexedDB.deleteDatabase('tongpin-demo.attachments.v1'); window.location.hash = '#/'; window.location.reload(); }}>确认恢复演示数据</button><button onClick={() => setReset(false)}>取消</button></div>}</section>}</div>;
}
