// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { api, APIError } from './lib/api';
import type { UserView } from './auth-types';
import { AdminEnrollmentPanel } from './AdminEnrollmentPanel';

vi.mock('./lib/api', async (original) => ({ ...await original<typeof import('./lib/api')>(), api: vi.fn() }));
const requestApi = vi.mocked(api); const user: UserView = { id: 'u1', username: 'one', nickname: '本人', bio: '', siteRole: 'user', status: 'active', createdAt: 1, preferences: { invisible: false, readReceipts: true, doNotDisturb: false } };
const invitation = { id: 'invite1', purpose: 'grant', expiresAt: Date.now() + 86400000, inviter: { id: 'admin', username: 'admin', nickname: '邀请者' } };
const enrollment = { enrollmentId: 'enroll1', secret: 'PRIVATE-TOTP-SECRET', uri: 'otpauth://totp/private', expiresAt: Date.now() + 600000 };
beforeEach(() => { requestApi.mockReset(); }); afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });
async function start() { fireEvent.change(await screen.findByLabelText('绑定验证密码'), { target: { value: 'private-password' } }); fireEvent.click(screen.getByRole('button', { name: '验证密码并开始绑定' })); await screen.findByText(enrollment.secret); }
function responses() { requestApi.mockImplementation(async (path) => path.endsWith('/reauth') ? { reauthToken: 'ephemeral-token' } : path.endsWith('/start') ? enrollment : path.endsWith('/finish') ? { user: { ...user, siteRole: 'super_admin' }, recoveryCodes: Array.from({ length: 8 }, (_, i) => `INDEPENDENT-CODE-${i}`) } : { invitation }); }
it('verifies password then TOTP, shows 8 independent codes once and updates identity only after saved', async () => {
  responses(); const storage = vi.spyOn(Storage.prototype, 'setItem'); const onUserChange = vi.fn(); render(<AdminEnrollmentPanel user={user} onUserChange={onUserChange} />); await start(); expect(requestApi.mock.calls.find(([path]) => path.endsWith('/reauth'))?.[1]?.body).toEqual({ password: 'private-password', action: 'administrator.enroll' }); expect(requestApi.mock.calls.find(([path]) => path.endsWith('/start'))?.[1]?.body).toEqual({ reauthToken: 'ephemeral-token' }); expect(onUserChange).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('验证器当前动态码'), { target: { value: '123456' } }); fireEvent.click(screen.getByRole('button', { name: '验证动态码并完成绑定' })); await screen.findByRole('heading', { name: '保存独立第二因素恢复码' }); expect(requestApi.mock.calls.find(([path]) => path.endsWith('/finish'))?.[1]?.body).toEqual({ enrollmentId: 'enroll1', code: '123456' }); expect(screen.queryByText(enrollment.secret)).not.toBeInTheDocument(); expect(screen.getAllByText(/INDEPENDENT-CODE-/)).toHaveLength(8); expect(screen.getByRole('button', { name: '已保存，更新管理身份' })).toBeDisabled(); expect(onUserChange).not.toHaveBeenCalled(); fireEvent.click(screen.getByLabelText('我已安全保存全部第二因素恢复码')); fireEvent.click(screen.getByRole('button', { name: '已保存，更新管理身份' })); expect(onUserChange).toHaveBeenCalledWith(expect.objectContaining({ siteRole: 'super_admin' })); expect(screen.queryByText('INDEPENDENT-CODE-0')).not.toBeInTheDocument(); expect(storage).not.toHaveBeenCalled();
});
it('keeps a real invalid TOTP failure from granting role or showing recovery codes', async () => {
  responses(); const original = requestApi.getMockImplementation()!; requestApi.mockImplementation(async (path, options) => { if (path.endsWith('/finish')) throw new APIError(400, { code: 'INVALID_SECOND_FACTOR', message: '动态码验证失败' }); return original(path, options); }); const changed = vi.fn(); render(<AdminEnrollmentPanel user={user} onUserChange={changed} />); await start(); fireEvent.change(screen.getByLabelText('验证器当前动态码'), { target: { value: '000000' } }); fireEvent.click(screen.getByRole('button', { name: '验证动态码并完成绑定' })); await screen.findByText('动态码验证失败'); expect(changed).not.toHaveBeenCalled(); expect(screen.queryByText(/INDEPENDENT-CODE-/)).not.toBeInTheDocument(); expect(screen.getByLabelText('验证器当前动态码')).toHaveValue('');
});
it('removes secrets on identity change and aborts late finish results', async () => {
  responses(); let resolve!: (value: unknown) => void; const late = new Promise((done) => { resolve = done; }); const original = requestApi.getMockImplementation()!; requestApi.mockImplementation(async (path, options) => path.endsWith('/finish') ? late : original(path, options)); const changed = vi.fn(); const view = render(<AdminEnrollmentPanel user={user} onUserChange={changed} />); await start(); fireEvent.change(screen.getByLabelText('验证器当前动态码'), { target: { value: '123456' } }); fireEvent.click(screen.getByRole('button', { name: '验证动态码并完成绑定' })); await waitFor(() => expect(requestApi.mock.calls.some(([path]) => path.endsWith('/finish'))).toBe(true)); const signal = requestApi.mock.calls.find(([path]) => path.endsWith('/finish'))![1]!.signal!; view.rerender(<AdminEnrollmentPanel user={{ ...user, id: 'u2' }} onUserChange={changed} />); expect(signal.aborted).toBe(true); expect(screen.queryByText(enrollment.secret)).not.toBeInTheDocument(); await act(async () => { resolve({ user: { ...user, siteRole: 'super_admin' }, recoveryCodes: ['LATE-SECRET'] }); }); expect(screen.queryByText('LATE-SECRET')).not.toBeInTheDocument(); expect(changed).not.toHaveBeenCalled();
});
it('expires a displayed challenge and discards its secret', async () => {
  responses(); render(<AdminEnrollmentPanel user={user} onUserChange={vi.fn()} />); await start(); vi.useFakeTimers(); // Trigger a fresh challenge with a timer in the fake clock.
  fireEvent.click(screen.getByRole('button', { name: '隐藏秘密并重新开始' })); fireEvent.change(screen.getByLabelText('绑定验证密码'), { target: { value: 'private-password' } }); await act(async () => { fireEvent.click(screen.getByRole('button', { name: '验证密码并开始绑定' })); }); expect(screen.getByText(enrollment.secret)).toBeInTheDocument(); await act(async () => { await vi.advanceTimersByTimeAsync(610000); }); expect(screen.queryByText(enrollment.secret)).not.toBeInTheDocument(); expect(screen.getByRole('alert')).toHaveTextContent('绑定挑战已到期');
});
