// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { AttachmentList } from './AttachmentViews';

type AttachmentView = Parameters<typeof AttachmentList>[0]['files'][number];
const ready: AttachmentView = { id: 'attachment-one', kind: 'image', mime: 'image/png', name: '受控图片.png', size: 1024, width: 100, height: 100, frameCount: 1, state: 'ready', contentUrl: '/api/v1/attachments/a/content', thumbnailUrl: '/api/v1/attachments/a/thumbnail', previewUrl: '/api/v1/attachments/a/preview', error: null, errorCode: null };
const restricted: AttachmentView = { ...ready, state: 'quarantined', contentUrl: '', thumbnailUrl: undefined, previewUrl: undefined, errorCode: 'FILE_RESTRICTED', error: '因违规附件已被管理员隔离' };
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((finish) => { resolve = finish; }); return { promise, resolve }; }
beforeEach(() => { vi.stubGlobal('fetch', vi.fn()); Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:download-test') }); Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() }); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {}); Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function (this: HTMLDialogElement) { this.open = true; } }); Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value: function (this: HTMLDialogElement) { this.open = false; } }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); });

describe('S2 ordinary file governance', () => {
  it.each(['restricted', 'empty-url'] as const)('disables %s download and displays the real server reason without requesting an empty URL', (condition) => {
    const file: AttachmentView = { ...ready, state: condition === 'restricted' ? 'quarantined' : 'ready', contentUrl: '', thumbnailUrl: undefined, previewUrl: undefined, errorCode: condition === 'restricted' ? 'FILE_RESTRICTED' : 'FILE_MISSING', error: condition === 'restricted' ? '因违规附件已被管理员隔离' : '原件已清理，当前无法下载' };
    render(<AttachmentList files={[file]} />); const button = screen.getByRole('button', { name: '下载文件 受控图片.png' }); expect(button).toBeDisabled(); expect(screen.getByText(file.error!)).toBeInTheDocument(); fireEvent.click(button); expect(fetch).not.toHaveBeenCalled();
  });
  it('closes an already-open preview as soon as governance restriction arrives', () => { const view = render(<AttachmentList files={[ready]} />); fireEvent.click(screen.getByRole('button', { name: '预览图片 受控图片.png' })); expect(screen.getByRole('dialog')).toBeInTheDocument(); view.rerender(<AttachmentList files={[restricted]} />); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(screen.queryByRole('img')).not.toBeInTheDocument(); expect(screen.getByText(restricted.error!)).toBeInTheDocument(); });
  it('aborts an in-flight download on restriction and cannot save its late Blob even after release', async () => {
    const pending = deferred<Blob>(); vi.mocked(fetch).mockResolvedValue({ ok: true, blob: () => pending.promise } as Response); const view = render(<AttachmentList files={[ready]} />); await act(async () => { fireEvent.click(screen.getByRole('button', { name: '下载文件 受控图片.png' })); }); const signal = vi.mocked(fetch).mock.calls[0][1]?.signal;
    view.rerender(<AttachmentList files={[restricted]} />); expect(signal?.aborted).toBe(true); view.rerender(<AttachmentList files={[ready]} />); await act(async () => { pending.resolve(new Blob(['late old download'])); }); expect(URL.createObjectURL).not.toHaveBeenCalled(); expect(HTMLAnchorElement.prototype.click).not.toHaveBeenCalled();
    vi.mocked(fetch).mockResolvedValue({ ok: true, blob: async () => new Blob(['fresh download']) } as Response); await act(async () => { fireEvent.click(screen.getByRole('button', { name: '下载文件 受控图片.png' })); }); expect(HTMLAnchorElement.prototype.click).toHaveBeenCalledTimes(1); expect(vi.mocked(fetch).mock.calls.every(([url]) => url !== '')).toBe(true);
  });
  it('clears an old thumbnail failure after release but keeps the current server error visible', () => { const view = render(<AttachmentList files={[ready]} />); fireEvent.error(screen.getByRole('img')); expect(screen.queryByRole('button', { name: '预览图片 受控图片.png' })).not.toBeInTheDocument(); view.rerender(<AttachmentList files={[restricted]} />); expect(screen.getByText(restricted.error!)).toBeInTheDocument(); view.rerender(<AttachmentList files={[{ ...ready, error: '服务器当前提示仍然有效' }]} />); expect(screen.getByText('服务器当前提示仍然有效')).toBeInTheDocument(); expect(screen.getByRole('button', { name: '预览图片 受控图片.png' })).toBeEnabled(); expect(screen.getByRole('button', { name: '下载文件 受控图片.png' })).toBeEnabled(); fireEvent.click(screen.getByRole('button', { name: '预览图片 受控图片.png' })); expect(screen.getByRole('dialog')).toBeInTheDocument(); });
  it('cancels on unmount without allowing a late successful response to save', async () => { const pending = deferred<Response>(); vi.mocked(fetch).mockReturnValue(pending.promise); const view = render(<AttachmentList files={[ready]} />); fireEvent.click(screen.getByRole('button', { name: '下载文件 受控图片.png' })); const signal = vi.mocked(fetch).mock.calls[0][1]?.signal; view.unmount(); expect(signal?.aborted).toBe(true); await act(async () => pending.resolve({ ok: true, blob: async () => new Blob(['late']) } as Response)); expect(HTMLAnchorElement.prototype.click).not.toHaveBeenCalled(); });
  it('retains the 120-second timeout cancellation boundary', async () => { vi.useFakeTimers(); vi.mocked(fetch).mockReturnValue(new Promise(() => {})); render(<AttachmentList files={[ready]} />); fireEvent.click(screen.getByRole('button', { name: '下载文件 受控图片.png' })); const signal = vi.mocked(fetch).mock.calls[0][1]?.signal; await act(async () => { await vi.advanceTimersByTimeAsync(120000); }); expect(signal?.aborted).toBe(true); expect(screen.getByText('下载超过 120 秒，已停止等待，请重试。')).toBeInTheDocument(); expect(HTMLAnchorElement.prototype.click).not.toHaveBeenCalled(); });
});
