import { useEffect, useRef, useState } from 'react';
import { api } from './lib/api';
import type { Conversation } from './lib/chat-types';
import type { MessageResults } from './lib/interactions-types';

export function MessageSearchPage({ conversations, initialConversationId, onJump, onClose }: { conversations: Conversation[]; initialConversationId?: string; onJump: (id: string) => Promise<void>; onClose: () => void }) {
  const [mode, setMode] = useState<'search' | 'bookmarks'>('search'); const [query, setQuery] = useState(''); const [conversationId, setConversationId] = useState(initialConversationId || '');
  const [result, setResult] = useState<MessageResults | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const controller = useRef<AbortController | null>(null); const submitted = useRef({ query: '', conversationId: '' });
  useEffect(() => () => controller.current?.abort(), []);
  async function load(append = false, nextMode = mode) {
    const criteria = append ? submitted.current : { query: query.trim(), conversationId };
    if (nextMode === 'search' && !criteria.query) return;
    controller.current?.abort(); const request = new AbortController(); controller.current = request; setBusy(true); setError('');
    if (!append) setResult(null);
    const params = new URLSearchParams({ limit: '50' }); if (nextMode === 'search') { params.set('q', criteria.query); if (criteria.conversationId) params.set('conversationId', criteria.conversationId); } if (append && result?.nextCursor) params.set('after', result.nextCursor);
    try { const page = await api<MessageResults>(`/api/v1/${nextMode === 'search' ? 'messages/search' : 'bookmarks'}?${params}`, { signal: request.signal }); if (!request.signal.aborted) { submitted.current = criteria; setResult((current) => ({ items: append ? [...(current?.items || []), ...page.items] : page.items, nextCursor: page.nextCursor })); } }
    catch (cause) { if (!request.signal.aborted) setError(cause instanceof Error ? cause.message : '加载失败，请重试。'); }
    finally { if (!request.signal.aborted) setBusy(false); }
  }
  async function act(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await action(); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败，请重试。'); } finally { setBusy(false); } }
  return <div className="message-search-page"><header className="workspace-page-header"><h1>消息搜索与收藏</h1><button className="secondary-button" onClick={onClose}>返回聊天</button></header><div className="page-tabs"><button aria-pressed={mode === 'search'} onClick={() => { controller.current?.abort(); setMode('search'); setResult(null); setError(''); setBusy(false); }}>搜索消息</button><button aria-pressed={mode === 'bookmarks'} onClick={() => { setMode('bookmarks'); void load(false, 'bookmarks'); }}>我的收藏</button></div>{mode === 'search' && <form className="message-search-form" onSubmit={(event) => { event.preventDefault(); void load(); }}><label className="form-field">消息关键词<input value={query} maxLength={200} required placeholder="支持中文关键词" onChange={(event) => setQuery(event.target.value)} /></label><label className="form-field">搜索范围<select value={conversationId} onChange={(event) => setConversationId(event.target.value)}><option value="">所有可访问会话</option>{conversations.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><button className="primary-button" disabled={busy || !query.trim()}>搜索</button></form>}{error && <p className="form-error" role="alert">{error}<button className="text-button" disabled={busy} onClick={() => void load()}>重新加载</button></p>}{busy && <p role="status">正在处理…</p>}{result && !result.items.length && <p role="status">{mode === 'bookmarks' ? '还没有收藏消息。' : '没有匹配的可访问消息。'}</p>}<ul className="message-results">{result?.items.map((item) => <li key={item.id}><div><strong>{item.available ? item.conversation?.title : '消息不可用'}</strong>{item.available && item.message ? <><p>{item.message.status === 'sent' ? item.message.text || `[${item.message.attachments.length} 个附件]` : '这条消息已撤回或删除'}</p><small>{item.message.sender?.nickname || '已注销账号'} · {new Date(item.message.createdAt).toLocaleString('zh-CN')}</small></> : <p>消息已删除或当前账号不再具有访问权限。</p>}</div><div className="message-result-actions"><button className="secondary-button" disabled={busy || !item.available} onClick={() => void act(() => onJump(item.id))}>定位消息</button>{mode === 'bookmarks' && <button className="text-button" disabled={busy} onClick={() => void act(async () => { await api(`/api/v1/messages/${encodeURIComponent(item.id)}/bookmark`, { method: 'DELETE', body: {} }); setResult((current) => current ? { ...current, items: current.items.filter((candidate) => candidate.id !== item.id) } : current); })}>移除收藏</button>}</div></li>)}</ul>{result?.nextCursor && <button className="load-more-button" disabled={busy} onClick={() => void load(true)}>加载更多结果</button>}</div>;
}
