import { useState } from 'react';
import { Clock3, Copy, RotateCw, X } from 'lucide-react';
import type { QueuedMessage } from './lib/chat-types';
import { EmptyState } from './components/EmptyState';

export function OfflineQueuePage({ items, onRetry, onCancel, onCopyToDraft }: { items: QueuedMessage[]; onRetry: (id: string) => Promise<void>; onCancel: (id: string) => Promise<void>; onCopyToDraft: (item: QueuedMessage) => Promise<void> }) {
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function perform(id: string, action: () => Promise<void>, success?: string) { if (busy) return; setBusy(id); setError(''); setNotice(''); try { await action(); if (success) setNotice(success); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败，请重试。'); } finally { setBusy(null); } }
  return <div className="offline-queue-page"><header className="workspace-page-header"><div><h1>本机待发</h1><p>只有本机保存成功的消息才会出现在这里。</p></div><Clock3 size={25} aria-hidden="true" /></header><div className="queue-explanation"><p>待发消息保留在当前账号的本机空间，最多 100 条、7 天。恢复网络后会先确认权限，再继续投递。</p><p>停止本机重试不会撤回已到达服务器的消息。复制回编辑器也不会自动发送。</p></div>{error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="success-note" role="status">{notice}</p>}{items.length ? <ul className="outbox-list">{items.map((item) => <li className={`outbox-card ${item.state}`} key={item.key}><header><strong>{item.conversationTitle}</strong><span className="queue-state">{item.state === 'queued' ? '已存本机 · 等待投递' : item.state === 'sending' ? '发送中 · 等待服务器确认' : '发送失败'}</span></header><p className="outbox-message">{item.payload.text || '（没有正文）'}</p>{item.files.length > 0 && <p className="field-hint">包含 {item.files.length} 个本机附件</p>}{item.error && <p className="field-error">{item.error}</p>}<div className="outbox-meta"><span>保存于 {new Date(item.createdAt).toLocaleString('zh-CN')}</span><span>到期时间 {new Date(item.expiresAt).toLocaleString('zh-CN')}</span></div><footer>{item.state !== 'sending' && <button className="secondary-button" disabled={!!busy} onClick={() => void perform(item.key, () => onRetry(item.payload.clientMessageId))}><RotateCw size={15} />重试</button>}<button className="secondary-button" disabled={!!busy} onClick={() => void perform(item.key, () => onCopyToDraft(item))}><Copy size={15} />复制到编辑器</button><button className="text-button danger-text" disabled={!!busy} onClick={() => void perform(item.key, () => onCancel(item.payload.clientMessageId), '已停止这条消息的本机重试；服务器上已收到的消息不受影响。')}><X size={15} />停止本机重试</button></footer></li>)}</ul> : <EmptyState title="没有本机待发消息" description="断网时保存的消息和发送失败的消息会显示在这里。" />}</div>;
}
