import { ImagePlus, Paperclip, Send } from 'lucide-react';
import { useId, useRef, useState } from 'react';
import type { LocalAttachment } from '../lib/chat-types';
import { LocalAttachmentList } from '../AttachmentViews';

export function Composer({ value, onChange, onSend, disabledReason, sending = false, notice, inputRef, files = [], onAddFiles, onRemoveFile, fileError }: { value: string; onChange: (value: string) => void; onSend: () => void; disabledReason?: string; sending?: boolean; notice?: string; inputRef?: React.Ref<HTMLTextAreaElement>; files?: LocalAttachment[]; onAddFiles?: (files: File[]) => void; onRemoveFile?: (id: string) => void; fileError?: string }) {
  const [composing, setComposing] = useState(false);
  const [dragging, setDragging] = useState(false); const imageInput = useRef<HTMLInputElement>(null); const fileInput = useRef<HTMLInputElement>(null);
  const hintId = useId();
  const codepoints = Array.from(value).length;
  const bytes = new TextEncoder().encode(value).byteLength;
  const limitError = codepoints > 4000 || bytes > 16384 ? '消息不能超过 4,000 个字符或 16 KiB，请缩短后再发送。' : '';
  const canSend = !disabledReason && !sending && !limitError && (!!value.trim() || files.length > 0);
  const acceptFiles = (selected: File[]) => { if (!disabledReason && selected.length) onAddFiles?.(selected); };
  return <form className={`composer ${dragging ? 'dragging' : ''}`} onSubmit={(event) => { event.preventDefault(); if (canSend) onSend(); }} onDragOver={(event) => { if (onAddFiles && !disabledReason && Array.from(event.dataTransfer.types).includes('Files')) { event.preventDefault(); setDragging(true); } }} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragging(false); }} onDrop={(event) => { if (onAddFiles && event.dataTransfer.files.length) { event.preventDefault(); setDragging(false); acceptFiles(Array.from(event.dataTransfer.files)); } }} onPaste={(event) => { const pasted = Array.from(event.clipboardData.files); if (onAddFiles && pasted.length) { event.preventDefault(); acceptFiles(pasted); } }}>
    {onAddFiles && <div className="composer-tools"><button type="button" className="text-button" disabled={!!disabledReason} onClick={() => imageInput.current?.click()}><ImagePlus size={18} />选择图片</button><button type="button" className="text-button" disabled={!!disabledReason} onClick={() => fileInput.current?.click()}><Paperclip size={18} />选择文件</button><span className="field-hint">可拖入或粘贴 · 最多 6 件 / 50 MiB</span><input ref={imageInput} className="attachment-input" aria-label="图片附件" type="file" multiple accept=".png,.jpg,.jpeg,.webp,.gif" disabled={!!disabledReason} onChange={(event) => { acceptFiles(Array.from(event.target.files || [])); event.target.value = ''; }} /><input ref={fileInput} className="attachment-input" aria-label="文件附件" type="file" multiple accept=".pdf,.txt,.md,.csv,.json,.docx,.xlsx,.pptx,.zip,.7z" disabled={!!disabledReason} onChange={(event) => { acceptFiles(Array.from(event.target.files || [])); event.target.value = ''; }} /></div>}
    <LocalAttachmentList files={files} onRemove={onRemoveFile} />{fileError && <p className="field-error" role="alert">{fileError}</p>}
    <textarea ref={inputRef} aria-label="消息内容" aria-describedby={hintId} aria-invalid={!!limitError} placeholder={disabledReason || '发送一条消息…'} disabled={!!disabledReason} value={value} onChange={(event) => onChange(event.target.value)} onCompositionStart={() => setComposing(true)} onCompositionEnd={() => setComposing(false)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !composing && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); if (canSend) onSend(); } }} />{limitError && <p className="field-error" role="alert">{limitError}</p>}<div className="composer-footer"><p id={hintId}>{disabledReason || notice || 'Enter 发送 · Shift + Enter 换行'}{codepoints > 3500 && <span className="composer-count">{codepoints.toLocaleString()} / 4,000 字符</span>}</p><button className="primary-button" disabled={!canSend} type="submit">{sending ? '保存中…' : '发送'}<Send size={16} /></button></div></form>;
}
