import { Avatar } from '../AttachmentViews';
import { BellOff, Pin, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import { Brand } from './Brand';
import { EmptyState } from './EmptyState';

// Presentation models only. Map authenticated domain data into these props.
export interface ConversationView { id: string; avatarUrl?: string | null; title: string; preview: string; timeLabel?: string; unreadLabel?: string; unreadCount?: number; pinned?: boolean; muted?: boolean; archived?: boolean; online?: boolean }
export function ConversationList({ conversations, selectedId, onSelect, onAdd, onCreateGroup, onJoinGroup, hasMore, onLoadMore, loading = false, onSearchMessages }: { conversations: ConversationView[]; selectedId?: string; onSelect: (id: string) => void; onAdd?: () => void; onCreateGroup?: () => void; onJoinGroup?: () => void; hasMore?: boolean; onLoadMore?: () => void; loading?: boolean; onSearchMessages?: () => void }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'all' | 'unread' | 'archived'>('all');
  const filtered = conversations.filter((item) => item.title.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()) && (filter === 'archived' ? item.archived : !item.archived && (filter !== 'unread' || !!item.unreadCount)));
  return <aside className="conversation-list" aria-label="会话列表"><header className="list-brand"><Brand /><p>让对话，自然发生。</p></header><div className="conversation-search-row"><label className="search-field"><Search size={17} aria-hidden="true" /><input aria-label="搜索会话" placeholder="搜索会话" value={search} onChange={(event) => setSearch(event.target.value)} /></label>{onAdd && <button className="icon-button add-friend-button" aria-label="添加好友" onClick={onAdd}><Plus size={20} /></button>}</div>{(onCreateGroup || onJoinGroup) && <div className="conversation-group-actions">{onCreateGroup && <button className="text-button" onClick={onCreateGroup}>创建群聊</button>}{onJoinGroup && <button className="text-button" onClick={onJoinGroup}>加入群聊</button>}</div>}{onSearchMessages && <button className="text-button" onClick={onSearchMessages}>搜索消息 / 我的收藏</button>}<div className="conversation-filters" aria-label="会话筛选">{([{ id: 'all', label: '全部' }, { id: 'unread', label: '未读' }, { id: 'archived', label: '已归档' }] as const).map(({ id, label }) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="list-label">{filter === 'archived' ? '归档会话' : '最近会话'}</div><div className="conversation-scroll">{filtered.length ? <ul>{filtered.map((item) => <li key={item.id}><button className={`conversation-item ${selectedId === item.id ? 'selected' : ''}`} onClick={() => onSelect(item.id)} aria-current={selectedId === item.id ? 'true' : undefined}><span className="conversation-avatar"><Avatar url={item.avatarUrl} label={item.title} />{item.online && <span className="online-dot" aria-label="在线" />}</span><span className="conversation-copy"><span className="conversation-title">{item.title}</span><span className="conversation-preview">{item.preview}</span></span><span className="conversation-meta"><time>{item.timeLabel}</time><span className="conversation-indicators">{item.pinned && <Pin size={12} aria-label="已置顶" />}{item.muted && <BellOff size={12} aria-label="已免打扰" />}{item.unreadLabel && <span className={`unread ${item.muted ? 'muted-unread' : ''}`}>{item.unreadLabel}</span>}</span></span></button></li>)}</ul> : <EmptyState title={search ? '没有找到会话' : filter === 'unread' ? '没有未读会话' : filter === 'archived' ? '还没有归档会话' : '还没有会话'} description={search ? '试试其他关键词。' : filter === 'archived' ? '你归档的会话会保留在这里。' : '添加好友后，就能开始一段对话。'} action={!search && filter === 'all' && onAdd ? <button className="text-button" onClick={onAdd}>查找好友</button> : undefined} />}{hasMore && onLoadMore && <button className="load-more-button" onClick={onLoadMore} disabled={loading}>{loading ? '正在加载…' : '加载更多会话'}</button>}</div></aside>;
}
