import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { filterEmoji, loadEmojiData, emojiVariants, recentEmoji, rememberEmoji, type EmojiData, type EmojiEntry } from '../lib/emoji';

export function EmojiPicker({ userId, onSelect, onClose }: { userId: string; onSelect: (sequence: string) => void; onClose: () => void }) {
  const [data, setData] = useState<EmojiData | null>(null); const [error, setError] = useState(''); const [reload, setReload] = useState(0);
  const [query, setQuery] = useState(''); const [group, setGroup] = useState(''); const [recent, setRecent] = useState(false);
  const [variant, setVariant] = useState<EmojiEntry | null>(null); const [limit, setLimit] = useState(120); const search = useRef<HTMLInputElement>(null); const grid = useRef<HTMLDivElement>(null); const labelId = useId();
  useEffect(() => { let active = true; setError(''); void loadEmojiData().then((loaded) => { if (active) setData(loaded); }).catch(() => { if (active) setError('表情数据加载失败，请重试。'); }); search.current?.focus(); return () => { active = false; }; }, [reload]);
  const entries = useMemo(() => { if (!data) return []; if (variant) return emojiVariants(data, variant); if (recent) return recentEmoji(userId).map((sequence) => data.entries.find((entry) => entry.sequence === sequence)).filter((entry): entry is EmojiEntry => !!entry); return filterEmoji(data, query, group); }, [data, variant, recent, userId, query, group]);
  const variantCounts = useMemo(() => { const counts = new Map<string, number>(); for (const entry of data?.entries || []) counts.set(entry.variantGroup, (counts.get(entry.variantGroup) || 0) + 1); return counts; }, [data]);
  const choose = (entry: EmojiEntry) => { rememberEmoji(userId, entry.sequence); onSelect(entry.sequence); onClose(); };
  const reset = () => { setVariant(null); setLimit(120); };
  return <section className="emoji-picker" aria-labelledby={labelId} onKeyDown={(event) => { if (event.key === 'Escape') { event.stopPropagation(); onClose(); } }}><div className="card-heading"><strong id={labelId}>表情</strong><button type="button" className="text-button" onClick={onClose}>关闭表情</button></div><label className="form-field">搜索表情<input ref={search} value={query} placeholder="中文、English 或表情" onChange={(event) => { setQuery(event.target.value); setRecent(false); reset(); }} /></label><div className="emoji-categories" aria-label="表情分类"><button type="button" aria-pressed={!group && !recent} onClick={() => { setGroup(''); setRecent(false); reset(); }}>全部</button><button type="button" aria-pressed={recent} onClick={() => { setRecent(true); reset(); }}>最近使用</button>{data?.groups.map((item) => <button key={item.id} type="button" aria-pressed={group === item.id && !recent} onClick={() => { setGroup(item.id); setRecent(false); reset(); }}>{item.label}</button>)}</div>{error ? <p role="alert">{error}<button type="button" className="text-button" onClick={() => setReload((value) => value + 1)}>重试</button></p> : !data ? <p role="status">正在加载表情…</p> : <>{variant && <div className="card-heading"><strong>{variant.name} · 完整肤色候选</strong><button type="button" className="text-button" onClick={reset}>返回结果</button></div>}<p className="field-hint" role="status">{entries.length} 个结果 · 方向键移动，Enter 选择</p><div ref={grid} className="emoji-grid" role="group" aria-label={variant ? '肤色候选' : '表情结果'} onKeyDown={(event) => { const buttons = Array.from(grid.current?.querySelectorAll<HTMLButtonElement>('button[data-emoji]') || []); const index = buttons.indexOf(document.activeElement as HTMLButtonElement); if (index < 0) return; const columns = Math.max(1, Math.round((grid.current?.clientWidth || 320) / 44)); const step = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : event.key === 'ArrowDown' ? columns : event.key === 'ArrowUp' ? -columns : 0; if (step) { event.preventDefault(); buttons[Math.max(0, Math.min(buttons.length - 1, index + step))]?.focus(); } }}>{entries.slice(0, limit).map((entry) => <div className="emoji-cell" key={entry.id}><button type="button" data-emoji={entry.id} className="emoji-choice" aria-label={`${entry.name} / ${entry.english}`} title={`${entry.name} · ${entry.english}`} onClick={() => choose(entry)}>{entry.sequence}</button>{!variant && data && (variantCounts.get(entry.variantGroup) || 0) > 1 && <button type="button" className="emoji-variants" aria-label={`选择${entry.name}的肤色`} onClick={() => { setVariant(entry); setLimit(120); }}>肤色</button>}</div>)}</div>{!entries.length && <p>没有匹配的表情。</p>}{entries.length > limit && <button type="button" className="load-more-button" onClick={() => setLimit((value) => value + 120)}>显示更多表情（已显示 {limit}）</button>}</>}<small className="field-hint">Unicode 17.0 · 字形由系统提供；部分新表情可能显示为方框。</small></section>;
}
