import { Bell, ClipboardList, Clock3, Folder, MessageCircle, MoreHorizontal, Settings, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Brand } from './Brand';

export type MainSection = 'messages' | 'tasks' | 'contacts' | 'notifications' | 'queue' | 'files' | 'settings';
const sections = [{ id: 'messages', label: '消息', Icon: MessageCircle }, { id: 'tasks', label: '待办', Icon: ClipboardList }, { id: 'contacts', label: '联系人', Icon: Users }, { id: 'notifications', label: '通知', Icon: Bell }, { id: 'queue', label: '待发', Icon: Clock3 }, { id: 'files', label: '文件', Icon: Folder }, { id: 'settings', label: '设置', Icon: Settings }] as const;
const secondary = new Set<MainSection>(['contacts', 'queue', 'files', 'settings']);
export function NavigationRail({ active, onNavigate, badges = {}, failedCount = 0 }: { active: MainSection; onNavigate: (section: MainSection) => void; badges?: Partial<Record<MainSection, number>>; failedCount?: number }) {
  const [more, setMore] = useState(false);
  useEffect(() => setMore(false), [active]);
  function go(section: MainSection) { setMore(false); onNavigate(section); }
  const badge = (id: MainSection) => (badges[id] || 0) > 0 && <span className="rail-badge" aria-label={`${badges[id]} 条未处理`}>{badges[id]! > 99 ? '99+' : badges[id]}</span>;
  return <nav className="navigation-rail" aria-label="主导航"><a className="rail-brand" href="/" aria-label="同频首页"><Brand compact /></a><div className="rail-items">{sections.map(({ id, label, Icon }) => <button key={id} className={`rail-button ${secondary.has(id) ? 'rail-secondary' : 'rail-primary'} ${active === id ? 'active' : ''}`} aria-current={active === id ? 'page' : undefined} onClick={() => go(id)}><Icon size={21} strokeWidth={1.6} /><span>{label}</span>{badge(id)}</button>)}<button className={`rail-button rail-more ${secondary.has(active) ? 'active' : ''}`} aria-expanded={more} aria-label="更多" aria-controls="mobile-more-navigation" onClick={() => setMore((value) => !value)}><MoreHorizontal size={21} /><span>更多</span>{((badges.contacts || 0) + (badges.queue || 0) > 0 || failedCount > 0) && <span className="rail-more-dot" aria-label={failedCount ? `${failedCount} 条待发失败` : '更多入口有未处理内容'} />}</button></div>{more && <section id="mobile-more-navigation" className="mobile-more-navigation" aria-label="更多功能"><header><strong>更多功能</strong><button className="text-button" onClick={() => setMore(false)}>收起更多</button></header>{failedCount > 0 && <p className="warning-note">有 {failedCount} 条消息投递失败，可在“待发”中处理。</p>}<div>{sections.filter(({ id }) => secondary.has(id)).map(({ id, label, Icon }) => <button key={id} className="secondary-button" onClick={() => go(id)}><Icon size={19} />{label}{(badges[id] || 0) > 0 && <span>{badges[id]} 条未处理</span>}</button>)}</div></section>}</nav>;
}