import { useCallback, useEffect, useState } from 'react';
import { Modal } from '../components/Modal';
import type { TaskClient } from '../lib/tasks-client';
import type { Task } from '../lib/tasks-types';
import { CommandFeedback, TaskConflict, TaskLoadState, TaskUnavailable, timeText, useTaskCommand, useTaskResource, useTaskState } from './TaskShared';

export function TaskActivityPanel({ client, task, enhanced, onRemoveComment, onReportComment }: { client: TaskClient; task: Task; enhanced: boolean; onRemoveComment: (id: string) => void; onReportComment: (id: string) => void }) {
  const [tab, setTab] = useState<'activities' | 'comments'>('activities'); const [after, setAfter] = useState(''); const [text, setText] = useState(''); const [base, setBase] = useState(task); const [notice, setNotice] = useState(''); const command = useTaskCommand(client); const state = useTaskState(client);
  const current = state.entities[task.id]; const unavailable = !current || !!state.invalid[task.id] || current.viewerId !== client.userId;
  const activities = useTaskResource(useCallback(() => client.activities(task.id, after), [client, task.id, task.etag, after]), tab === 'activities' && state.online && !unavailable);
  const comments = useTaskResource(useCallback(() => client.comments(task.id, after), [client, task.id, task.etag, after]), tab === 'comments' && enhanced && state.online && !unavailable);
  useEffect(() => { if (!text && !command.unknown) setBase(task); }, [task, text, command.unknown]);
  const resource = tab === 'activities' ? activities : comments;
  if (unavailable) return null;
  return <section className="task-discussion"><div className="task-tabs" role="group" aria-label="待办记录类型"><button aria-pressed={tab === 'activities'} onClick={() => { setTab('activities'); setAfter(''); }}>活动记录</button>{enhanced && <button aria-pressed={tab === 'comments'} onClick={() => { setTab('comments'); setAfter(''); }}>任务评论</button>}</div><p className="task-hint">{task.scope === 'group' ? '活动与评论仅展示本次加入群聊后的可读记录。' : '个人待办的活动与评论仅本人可见。'}</p><TaskLoadState {...resource} />
    {tab === 'activities' && activities.data && (activities.data.items.length ? <ol className="task-activity-list">{activities.data.items.map((item) => <li key={item.id}><div><strong>{item.actor?.nickname || '系统'}</strong><time>{timeText(item.createdAt)}</time></div><p>{item.text}</p></li>)}</ol> : <p>当前可读范围内没有活动记录。</p>)}
    {tab === 'comments' && enhanced && <>{comments.data && (comments.data.items.length ? <ol className="task-comment-list">{comments.data.items.map((item) => <li key={item.id}><div><strong>{item.author.nickname}</strong><time>{timeText(item.createdAt)}</time></div><p className="task-description">{item.removed ? '评论已删除。' : item.text}</p>{!item.removed && <div className="task-actions">{item.canDelete && <button className="text-button" disabled={!state.online} onClick={() => onRemoveComment(item.id)}>删除评论</button>}<button className="text-button" disabled={!state.online} onClick={() => onReportComment(item.id)}>举报评论</button></div>}</li>)}</ol> : <p>当前可读范围内没有评论。</p>)}
      <form className="task-comment-form" onSubmit={(event) => { event.preventDefault(); if (command.busy || !task.capabilities.comment || !state.online || !text.trim() || [...text.trim()].length > 1000) return; void command.run(JSON.stringify({ kind: 'comment', id: base.id, etag: base.etag, text: text.trim() }), (key) => client.addComment(base, text.trim(), key), base.id).then((result) => { if (result.ok) { setText(''); setBase(result.value); setNotice('评论已由服务器保存。'); command.clear(); comments.retry(); } }); }}><label className="form-field">添加任务评论<textarea rows={3} value={text} disabled={!task.capabilities.comment || command.busy || command.unknown} onChange={(event) => { setText(event.target.value); setNotice(''); }} /></label><p className="task-hint">最多 1,000 个字符，无附件。离线评论仅保留当前输入，不会自动提交。</p>{[...text.trim()].length > 1000 && <p role="alert" className="task-error">评论不能超过 1,000 个字符。</p>}{!task.capabilities.comment && <p className="warning-note">{task.capabilities.writeReason || '当前不能发表评论。'}</p>}<CommandFeedback {...command} />{command.conflict && <TaskConflict latest={command.conflict} draft={{ text }} onAccept={() => { setBase(command.conflict!); command.clear(); }} />}<button className="secondary-button" disabled={!state.online || !task.capabilities.comment || !text.trim() || [...text.trim()].length > 1000 || command.busy || !!command.conflict}>{command.busy ? '正在保存评论…' : command.unknown ? '核对并重试同一评论' : '提交评论'}</button>{notice && <p role="status" className="success-note">{notice}</p>}</form>
    </>}
    <div className="task-actions">{after && <button className="text-button" onClick={() => setAfter('')}>回到记录首页</button>}{resource.data?.nextCursor && <button className="secondary-button" disabled={resource.loading} onClick={() => setAfter(resource.data!.nextCursor!)}>下一页记录</button>}</div>
  </section>;
}

export function TaskReportDialog({ client, task, commentId, onClose }: { client: TaskClient; task: Task; commentId?: string; onClose: () => void }) {
  const state = useTaskState(client); const current = state.entities[task.id]; const [base, setBase] = useState(task); const [category, setCategory] = useState<'spam' | 'harassment' | 'illegal' | 'other'>('other'); const [description, setDescription] = useState(''); const [reportId, setReportId] = useState(''); const command = useTaskCommand(client);
  if (!current || state.invalid[task.id]) return <Modal open title="举报待办" onClose={onClose}><TaskUnavailable onClose={onClose} /></Modal>;
  const payload = { category, description: description.trim(), ...(commentId ? { commentId } : {}) };
  return <Modal open title={commentId ? '举报任务评论' : '举报此待办'} onClose={onClose} dismissible={!command.busy}>{reportId ? <p role="status" className="success-note">举报已提交，编号：{reportId}。处理结果请在通知与举报反馈中查看。</p> : <form className="task-form-fields" onSubmit={(event) => { event.preventDefault(); if (command.busy || !state.online || !description.trim()) return; void command.run(JSON.stringify({ id: base.id, etag: base.etag, payload }), (key) => client.report(base, payload, key), base.id).then((result) => { if (result.ok) setReportId(result.value.id); }); }}><p>举报将向站点处理人员提供此具体{commentId ? '评论' : '待办'}及必要说明，用于核实问题。私人待办不会因此进入全站常规列表。</p><fieldset disabled={command.busy || command.unknown}><label className="form-field">举报类别<select value={category} onChange={(event) => setCategory(event.target.value as typeof category)}><option value="spam">垃圾信息</option><option value="harassment">骚扰</option><option value="illegal">违法内容</option><option value="other">其他</option></select></label><label className="form-field">举报说明<textarea required rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></label></fieldset><CommandFeedback {...command} />{command.conflict && <TaskConflict latest={command.conflict} draft={{ title: base.title, description: base.description }} onAccept={() => { setBase(command.conflict!); command.clear(); }} />}<button className="primary-button" disabled={command.busy || !state.online || !description.trim() || !!command.conflict}>{command.unknown ? '核对并重试同一举报' : '确认提交举报'}</button></form>}<button className="text-button" disabled={command.busy} onClick={onClose}>关闭</button></Modal>;
}
