import { AtSign, ClipboardList, ImagePlus, Paperclip, Send } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';
import { api } from '../lib/api';
import type { GroupMember } from '../lib/group-types';
import type { Page } from '../lib/chat-types';
export type ComposerContext = { replyToMessageId: string | null; mentionedUserIds: string[]; mentionAll: boolean };
export const emptyComposerContext = (): ComposerContext => ({ replyToMessageId: null, mentionedUserIds: [], mentionAll: false });
import type { LocalAttachment } from '../lib/chat-types';
import { LocalAttachmentList } from '../AttachmentViews';

export function Composer({ value, onChange, onSend, disabledReason, sending = false, notice, inputRef, files = [], onAddFiles, onRemoveFile, fileError, userId, conversationId, groupRole, context, onContextChange, replyLabel, onCreateTask, onOpenTasks, taskDisabledReason }: { userId?: string; conversationId?: string; groupRole?: string; context?: ComposerContext; onContextChange?: (value: ComposerContext) => void; replyLabel?: string; value: string; onChange: (value: string) => void; onSend: () => void; disabledReason?: string; sending?: boolean; notice?: string; inputRef?: React.Ref<HTMLTextAreaElement>; files?: LocalAttachment[]; onAddFiles?: (files: File[]) => void; onRemoveFile?: (id: string) => void; fileError?: string; onCreateTask?: () => void; onOpenTasks?: () => void; taskDisabledReason?: string }) {
  const [composing, setComposing] = useState(false);
  const [dragging, setDragging] = useState(false); const imageInput = useRef<HTMLInputElement>(null); const fileInput = useRef<HTMLInputElement>(null);
  const hintId = useId(); const textarea = useRef<HTMLTextAreaElement | null>(null);
  const [mentionsOpen, setMentionsOpen] = useState(false); const [members, setMembers] = useState<Page<GroupMember> | null>(null); const [membersError, setMembersError] = useState(''); const [membersBusy, setMembersBusy] = useState(false); const memberRequest = useRef<AbortController | null>(null);
  useEffect(() => { setMentionsOpen(false); setMembers(null); memberRequest.current?.abort(); return () => memberRequest.current?.abort(); }, [conversationId]);
  async function loadMembers(append = false) { if (!conversationId || !groupRole) return; memberRequest.current?.abort(); const controller = new AbortController(); memberRequest.current = controller; setMembersBusy(true); setMembersError(''); try { const result = await api<Page<GroupMember>>(`/api/v1/groups/${encodeURIComponent(conversationId)}/members${append && members?.nextCursor ? `?after=${encodeURIComponent(members.nextCursor)}` : ''}`, { signal: controller.signal }); if (!controller.signal.aborted) setMembers((current) => ({ items: append ? [...(current?.items || []), ...result.items] : result.items, nextCursor: result.nextCursor })); } catch (cause) { if (!controller.signal.aborted) setMembersError(cause instanceof Error ? cause.message : '成员加载失败。'); } finally { if (!controller.signal.aborted) setMembersBusy(false); } }

  const codepoints = Array.from(value).length;
  const bytes = new TextEncoder().encode(value).byteLength;
  const limitError = codepoints > 4000 || bytes > 16384 ? '消息不能超过 4,000 个字符或 16 KiB，请缩短后再发送。' : '';
  const canSend = !disabledReason && !sending && !limitError && (!!value.trim() || files.length > 0);
  const acceptFiles = (selected: File[]) => { if (!disabledReason && selected.length) onAddFiles?.(selected); };
  return <form className={`composer ${dragging ? 'dragging' : ''}`} onSubmit={(event) => { event.preventDefault(); if (canSend) onSend(); }} onDragOver={(event) => { if (onAddFiles && !disabledReason && Array.from(event.dataTransfer.types).includes('Files')) { event.preventDefault(); setDragging(true); } }} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragging(false); }} onDrop={(event) => { if (onAddFiles && event.dataTransfer.files.length) { event.preventDefault(); setDragging(false); acceptFiles(Array.from(event.dataTransfer.files)); } }} onPaste={(event) => { const pasted = Array.from(event.clipboardData.files); if (onAddFiles && pasted.length) { event.preventDefault(); acceptFiles(pasted); } }}>
    <div className="composer-toolbar"><div className="composer-rich-tools">{onCreateTask && <button type="button" className="text-button composer-task-create" disabled={composing || !!taskDisabledReason} title={taskDisabledReason} onClick={onCreateTask}><ClipboardList size={15} />新建待办</button>}{onOpenTasks && <button type="button" className="text-button composer-task-open" disabled={composing} onClick={onOpenTasks}>查看群待办</button>}{groupRole && onContextChange && <button type="button" className="icon-button composer-mention" aria-label="@ 提及成员" title="@ 提及成员" disabled={!!disabledReason} aria-expanded={mentionsOpen} onClick={() => { setMentionsOpen((open) => !open); if (!members) void loadMembers(); }}><AtSign size={19} /></button>}</div>    {onAddFiles && <div className="composer-tools"><button type="button" className="icon-button" aria-label="选择图片" title="选择图片" disabled={!!disabledReason} onClick={() => imageInput.current?.click()}><ImagePlus size={18} /></button><button type="button" className="icon-button" aria-label="选择文件" title="选择文件" disabled={!!disabledReason} onClick={() => fileInput.current?.click()}><Paperclip size={18} /></button><span className="field-hint">可拖入或粘贴 · 最多 6 件 / 50 MiB</span><input ref={imageInput} className="attachment-input" aria-label="图片附件" type="file" multiple accept=".png,.jpg,.jpeg,.webp,.gif" disabled={!!disabledReason} onChange={(event) => { acceptFiles(Array.from(event.target.files || [])); event.target.value = ''; }} /><input ref={fileInput} className="attachment-input" aria-label="文件附件" type="file" multiple accept=".pdf,.txt,.md,.csv,.json,.docx,.xlsx,.pptx,.zip,.7z" disabled={!!disabledReason} onChange={(event) => { acceptFiles(Array.from(event.target.files || [])); event.target.value = ''; }} /></div>}</div>
    {context && onContextChange && <div className="composer-context">{context.replyToMessageId && <span className="composer-chip">引用：{replyLabel || '正在核对原消息…'}<button type="button" aria-label="移除引用" onClick={() => onContextChange({ ...context, replyToMessageId: null })}>×</button></span>}{context.mentionedUserIds.map((id) => <span className="composer-chip" key={id}>@{members?.items.find((member) => member.user.id === id)?.user.nickname || '已选成员'}<button type="button" aria-label={`移除提及 ${id}`} onClick={() => onContextChange({ ...context, mentionedUserIds: context.mentionedUserIds.filter((value) => value !== id) })}>×</button></span>)}{context.mentionAll && <span className="composer-chip">@全体成员<button type="button" aria-label="移除全体提及" onClick={() => onContextChange({ ...context, mentionAll: false })}>×</button></span>}</div>}
    {mentionsOpen && context && onContextChange && <section className="mention-picker" aria-label="选择提及成员"><p className="field-hint">只提醒仍在群里的成员，发送时会再次核对。</p>{['owner', 'admin'].includes(groupRole || '') && <button type="button" className="secondary-button" aria-pressed={context.mentionAll} onClick={() => onContextChange({ ...context, mentionAll: !context.mentionAll })}>@全体成员</button>}{members?.items.filter((member) => member.user.id !== userId).map((member) => <button key={member.user.id} type="button" className="text-button" aria-pressed={context.mentionedUserIds.includes(member.user.id)} onClick={() => onContextChange({ ...context, mentionedUserIds: context.mentionedUserIds.includes(member.user.id) ? context.mentionedUserIds.filter((id) => id !== member.user.id) : [...context.mentionedUserIds, member.user.id] })}>{member.user.nickname} (@{member.user.username})</button>)}{membersError && <p className="form-error" role="alert">{membersError}<button type="button" className="text-button" onClick={() => void loadMembers()}>重试</button></p>}{membersBusy && <p role="status">正在加载成员…</p>}{members?.nextCursor && <button type="button" className="text-button" disabled={membersBusy} onClick={() => void loadMembers(true)}>加载更多成员</button>}<button type="button" className="text-button" onClick={() => setMentionsOpen(false)}>完成选择</button></section>}

    <LocalAttachmentList files={files} onRemove={onRemoveFile} />{fileError && <p className="field-error" role="alert">{fileError}</p>}
    <textarea ref={(element) => { textarea.current = element; if (typeof inputRef === 'function') inputRef(element); else if (inputRef) inputRef.current = element; }} aria-label="消息内容" aria-describedby={hintId} aria-invalid={!!limitError} placeholder={disabledReason || '发送一条消息…'} disabled={!!disabledReason} value={value} onChange={(event) => onChange(event.target.value)} onCompositionStart={() => setComposing(true)} onCompositionEnd={() => setComposing(false)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !composing && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); if (canSend) onSend(); } }} />{limitError && <p className="field-error" role="alert">{limitError}</p>}<div className="composer-footer"><p id={hintId}>{disabledReason || notice || 'Enter 发送 · Shift + Enter 换行'}{codepoints > 3500 && <span className="composer-count">{codepoints.toLocaleString()} / 4,000 字符</span>}</p><button className="primary-button" disabled={!canSend} type="submit">{sending ? '保存中…' : '发送'}<Send size={16} /></button></div></form>;
}
