import { AttachmentList, Avatar, LocalAttachmentList } from '../AttachmentViews';
import type { Attachment, LocalAttachment } from '../lib/chat-types';
import { EmptyState } from './EmptyState';
import type { ReactNode, Ref } from 'react';

export interface MessageView { id: string; attachments?: Attachment[]; localFiles?: LocalAttachment[]; avatarUrl?: string | null; author: string; text: string; own: boolean; timeLabel: string; statusLabel?: string; system?: boolean; tombstone?: boolean; actions?: ReactNode; menu?: ReactNode; taskCard?: ReactNode; error?: string; quote?: string; onQuote?: () => void; located?: boolean }
export function MessageTimeline({ messages, viewportRef, onScroll, hasOlder = false, loading = false, onLoadOlder }: { messages: MessageView[]; viewportRef?: Ref<HTMLElement>; onScroll?: () => void; hasOlder?: boolean; loading?: boolean; onLoadOlder?: () => void }) {
  return <section ref={viewportRef} className="message-timeline" aria-label="消息记录" aria-busy={loading} onScroll={onScroll}>{hasOlder && onLoadOlder && <button className="history-load-button" disabled={loading} onClick={onLoadOlder}>{loading ? '正在加载历史…' : '加载更早的消息'}</button>}{!hasOlder && messages.length > 0 && <p className="history-start">对话的开始</p>}{messages.length ? <ol>{messages.map((message) => message.system ? <li className="system-message" key={message.id} data-message-id={message.id}><p>{message.text}</p><time>{message.timeLabel}</time></li> : <li className={`message ${message.own ? 'own' : ''} ${message.tombstone ? 'tombstone' : ''} ${message.located ? 'is-located' : ''}`} key={message.id} data-message-id={message.id}><Avatar url={message.avatarUrl} label={message.author} /><div className="message-content"><div className="message-meta">{message.author}<span>{message.timeLabel}</span></div><div className="message-body">{message.quote && <button type="button" className="message-quote message-quote-button" disabled={!message.onQuote} onClick={message.onQuote}>{message.quote}</button>}{!message.tombstone && message.taskCard ? <div className="message-task-slot">{message.taskCard}</div> : message.text && <div className="message-bubble">{message.text}</div>}{!message.tombstone && <><AttachmentList files={message.attachments || []} /><LocalAttachmentList files={message.localFiles || []} allowDownload /></>}{message.menu}</div>{message.statusLabel && <div className="message-status">{message.statusLabel}</div>}{message.error && <p className="message-error">{message.error}</p>}{message.actions && <div className="message-inline-actions">{message.actions}</div>}</div></li>)}</ol> : loading ? <p className="timeline-loading" role="status">正在加载对话…</p> : <EmptyState title="对话从这里开始" description="这段会话还没有消息。" />}</section>;
}
