import { MoreTaskConversations, type TaskConversationPaging } from './TaskShared';
import { useCallback, useEffect, useState } from 'react';
import { Check, ChevronRight, ClipboardList, Plus, Inbox, UserRound, UsersRound, Pencil, Star, Bookmark, Settings, Trash2, FileText, LockKeyhole, List, Columns3 } from 'lucide-react';
import type { Contact, Conversation } from '../lib/chat-types';
import type { TaskClient } from '../lib/tasks-client';
import type { Task, TaskDraft, TaskMeta, TaskQuery, TaskStatus } from '../lib/tasks-types';
import { TaskActionDialog, type TaskAction } from './TaskActionDialog';
import { TaskDetail } from './TaskDetail';
import { TaskDrafts } from './TaskDrafts';
import { TaskForm } from './TaskForm';
import { TaskSettings } from './TaskSettings';
import { Modal } from '../components/Modal';
import '../styles-task-preferences.css';
import { priorityLabels, statusLabels, TaskBadge, TaskLoadState, TaskUnavailable, useTaskResource, useTaskState } from './TaskShared';
import '../styles-tasks.css';

export type TaskWorkspaceProps = { client: TaskClient; userId: string; conversations: Conversation[]; contacts: Contact[]; initialGroupId?: string; initialTaskId?: string; onOpenSource: (messageId: string) => void | Promise<void>; onClose?: () => void; initialMeta?: TaskMeta } & TaskConversationPaging;
type FormState = { draft?: TaskDraft; task?: Task; initialGroupId?: string };
const views = [['mine', '我的待办'], ['personal', '个人待办'], ['created', '我创建的'], ['followed', '我关注的'], ['bookmarked', '我收藏的']] as const;
export function TaskWorkspace(props: TaskWorkspaceProps) { return <Workspace key={props.userId} {...props} />; }
function dateGroup(task: Task) {
  if (task.status === 'done') return '已完成'; if (!task.dueOn) return '无截止日期'; if (task.overdue) return '已逾期';
  try { const today = new Intl.DateTimeFormat('sv-SE', { timeZone: task.dueTimezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(); if (task.dueOn === today) return '今天'; } catch { /* Server dates remain visible when a browser lacks timezone support. */ }
  return '接下来';
}
function TaskRow({ task, onOpen, onAction, online }: { task: Task; onOpen: () => void; onAction: (action: TaskAction) => void; online: boolean }) {
  return <article className={`task-row ${task.status}`}><button className={`task-completion-icon ${task.status}`} aria-label={`${task.title}：${task.status === 'done' ? '设为未开始' : '设为已完成'}`} disabled={!online || !task.capabilities.progress || !!task.deletedAt} onClick={() => onAction({ kind: 'status', status: task.status === 'done' ? 'todo' : 'done' })}>{task.status === 'done' && <Check size={13} aria-hidden="true" />}</button><div className="task-row-main"><button className="task-title-button" onClick={onOpen}><strong>{task.title}</strong></button><div className="task-row-meta"><TaskBadge task={task} />{!!task.checkItems.length && <span className="task-check-progress"><ClipboardList size={12} aria-hidden="true" />{task.checkItems.filter((item) => item.done).length}/{task.checkItems.length}</span>}<span className={task.overdue ? 'task-overdue' : ''} title={task.dueTimezone}>{task.dueOn || '无截止日期'}</span>{task.status === 'doing' && <span className="task-doing-label">进行中</span>}</div></div><div className="task-row-end"><span className={`task-priority ${task.priority}`} title={`${priorityLabels[task.priority]}优先级`}><i aria-hidden="true" />{task.priority === 'normal' ? '中' : priorityLabels[task.priority]}</span><span className="task-assignee-avatar" title={task.assignee?.nickname || '待认领'} aria-label={`负责人：${task.assignee?.nickname || '待认领'}`}>{task.assignee?.nickname?.slice(0, 1) || <UserRound size={14} aria-hidden="true" />}</span>{task.deletedAt ? <span className="task-scope">回收中</span> : task.capabilities.progress && <details className="task-row-status"><summary aria-label={`${task.title} 状态操作`}>•••</summary><div>{(Object.keys(statusLabels) as TaskStatus[]).filter((value) => value !== task.status).map((value) => <button key={value} className="text-button" disabled={!online} onClick={() => onAction({ kind: 'status', status: value })}>设为{statusLabels[value]}</button>)}</div></details>}</div></article>;
}
function Workspace({ client, userId, conversations, contacts, initialGroupId, initialTaskId, onOpenSource, onClose, initialMeta, ...paging }: TaskWorkspaceProps) {
  const state = useTaskState(client); const [spacesOpen, setSpacesOpen] = useState(false); const [query, setQuery] = useState<TaskQuery>({ view: initialGroupId ? 'group' : 'mine', ...(initialGroupId ? { groupId: initialGroupId } : {}), status: 'open', limit: 30 }); const [view, setView] = useState<'list' | 'board'>('list'); const [panel, setPanel] = useState<'tasks' | 'drafts'>('tasks'); const [settingsOpen, setSettingsOpen] = useState(false); const [settingsBusy, setSettingsBusy] = useState(false);
  const [selected, setSelected] = useState(initialTaskId || ''); const [form, setForm] = useState<FormState | null>(null); const [action, setAction] = useState<{ task: Task; action: TaskAction } | null>(null); const [lastMeta, setLastMeta] = useState<TaskMeta | null>(initialMeta || null);
  const metaResource = useTaskResource(useCallback(() => client.meta(), [client]), state.online); const meta = metaResource.data || lastMeta;
  useEffect(() => { if (metaResource.data?.actorId === userId) setLastMeta(metaResource.data); }, [metaResource.data, userId]);
  useEffect(() => { if (initialTaskId) setSelected(initialTaskId); }, [initialTaskId]);
  useEffect(() => { if (initialGroupId) { setQuery({ view: 'group', groupId: initialGroupId, status: 'open', limit: 30 }); setPanel('tasks'); } }, [initialGroupId]);
  const queryKey = JSON.stringify(query);
  const list = useTaskResource(useCallback(() => client.list(JSON.parse(queryKey) as TaskQuery), [client, queryKey, state.listRevision]), state.online && !!meta?.enabled && panel === 'tasks' && (query.view !== 'group' || !!query.groupId));
  const tasks = list.data?.actorId === userId ? list.data.items.flatMap((item) => { const current = state.entities[item.id]; return current && current.viewerId === userId && !state.invalid[item.id] ? [current] : []; }) : [];
  const currentGroup = conversations.find((item) => item.kind === 'group' && item.id === query.groupId); const enhanced = !!meta?.enhanced && state.enhanced;
  function navigate(next: TaskQuery['view'], groupId?: string) { setSpacesOpen(false); setQuery({ view: next, ...(groupId ? { groupId } : {}), status: 'open', limit: 30 }); setPanel('tasks'); }
  function openDraft(draft: TaskDraft, latest: Task | null) { if (draft.userId !== userId || draft.expiresAt <= Date.now() || (latest && !latest.capabilities.edit)) return; setForm({ draft, ...(latest ? { task: latest } : {}) }); }
  if (client.userId !== userId || (meta && meta.actorId !== userId)) return <TaskUnavailable onClose={onClose} />;
  if (meta && (!meta.enabled || !state.enabled)) return <section className="task-workspace"><header className="task-page-heading"><h1>待办</h1>{onClose && <button className="secondary-button" onClick={onClose}>返回聊天</button>}</header><p className="task-empty">服务器当前未启用待办功能。聊天保持可用，已有待办数据不会因此自动删除。</p></section>;
  return <div className="task-workspace">
    <div className={`task-workspace-layout${spacesOpen ? ' task-spaces-open' : ''}`}><aside id="task-spaces" className="task-spaces" aria-label="待办空间"><div className="task-brand"><strong>同频<span>.</span></strong><p>让对话，有下一步。</p></div><nav aria-label="任务范围"><h2>工作概览</h2>{views.filter(([key]) => enhanced || !['followed', 'bookmarked'].includes(key)).map(([key, label]) => <button key={key} aria-current={panel === 'tasks' && query.view === key && !query.deleted ? 'page' : undefined} onClick={() => navigate(key)}>{key === 'mine' ? <Inbox size={18} /> : key === 'personal' ? <UserRound size={18} /> : key === 'created' ? <Pencil size={18} /> : key === 'followed' ? <Star size={18} /> : <Bookmark size={18} />}<span>{label}</span></button>)}<h2>团队空间 <span>按群聊组织</span></h2>{conversations.filter((item) => item.kind === 'group').map((item) => <button key={item.id} aria-current={panel === 'tasks' && query.view === 'group' && query.groupId === item.id && !query.deleted ? 'page' : undefined} onClick={() => navigate('group', item.id)}><UsersRound size={18} /><span>{item.title}</span></button>)}{!conversations.some((item) => item.kind === 'group') && <p className="task-hint">当前会话列表没有群，可在聊天中同步或加入群。</p>}<button aria-current={panel === 'tasks' && query.deleted ? 'page' : undefined} onClick={() => { setQuery({ ...query, deleted: 'only', status: 'all', after: undefined }); setPanel('tasks'); }}><Trash2 size={18} /><span>当前范围回收站</span></button><MoreTaskConversations {...paging} /><h2>本机与偏好</h2><button aria-current={panel === 'drafts' ? 'page' : undefined} onClick={() => setPanel('drafts')}><FileText size={18} /><span>本机任务草稿</span></button><button aria-expanded={settingsOpen} disabled={!meta} onClick={() => { setSettingsOpen(true); setSpacesOpen(false); }}><Settings size={18} /><span>{enhanced ? '偏好与分类' : '群创建策略'}</span></button></nav><div className="task-sidebar-foot"><span className={state.online ? 'online' : 'offline'} />{state.online ? '已连接 · 任务同步中' : '离线 · 草稿保存在本机'}<p><LockKeyhole size={12} />仅显示你有权访问的待办</p></div></aside>
    <main className="task-workspace-content"><div className="task-topbar"><button className="task-spaces-toggle" aria-expanded={spacesOpen} aria-controls="task-spaces" onClick={() => setSpacesOpen((open) => !open)}><List size={16} aria-hidden="true" />任务空间</button><span className="task-desktop-crumb">工作台</span><ChevronRight size={14} /><span>待办</span>{onClose && <button className="text-button" onClick={onClose}>返回聊天</button>}</div><div className="task-content-body">{!state.online && <p className="warning-note">当前离线：任务操作不会自动提交。可查看本机草稿，保存新建或编辑输入后，联网由本人重新核对。</p>}{state.error && <p role="alert" className="task-error">{state.error}</p>}<TaskLoadState {...metaResource} />{panel === 'drafts' ? <TaskDrafts client={client} onReview={openDraft} onClose={() => setPanel('tasks')} /> : <>
      <div className="task-section-heading"><div><h2>{query.deleted ? '回收站 · ' : ''}{query.view === 'group' ? currentGroup?.title || '群待办' : views.find(([key]) => key === query.view)?.[1] || '我的待办'}</h2><p className="task-hint">{query.view === 'personal' ? '仅自己可见' : query.view === 'group' ? '让群里的讨论，变成一起推进的事。' : '个人计划和分配给你的群任务，都在这里。'}</p></div><button className="primary-button" disabled={!meta} onClick={() => setForm({ initialGroupId: query.view === 'group' ? query.groupId : undefined })}><Plus size={17} aria-hidden="true" />新建待办</button></div><div className="task-summary" aria-label="当前页待办摘要"><span>待完成<strong>{tasks.filter((task) => task.status !== 'done').length}</strong></span><span>进行中<strong>{tasks.filter((task) => task.status === 'doing').length}</strong></span><span>已完成<strong>{tasks.filter((task) => task.status === 'done').length}</strong></span><span className="task-overdue">已逾期<strong>{tasks.filter((task) => task.overdue).length}</strong></span><small>当前页</small></div>
      <form key={queryKey} className="task-filters" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setQuery({ view: query.view, groupId: query.groupId, deleted: query.deleted, status: String(data.get('status') || 'open') as TaskQuery['status'], priority: String(data.get('priority') || '') as TaskQuery['priority'], assignee: String(data.get('assignee') || 'all') as TaskQuery['assignee'], due: String(data.get('due') || '') as TaskQuery['due'], q: String(data.get('q') || '').trim(), ...(enhanced ? { listId: String(data.get('listId') || ''), tagId: String(data.get('tagId') || '') } : {}), limit: 30 }); }}>
        <div className="task-status-segments" role="group" aria-label="常用状态筛选">{([['open', '未完成'], ['done', '已完成'], ['all', '全部']] as const).map(([value, label]) => <button key={value} type="button" onClick={(event) => { const form = event.currentTarget.form; const status = form?.elements.namedItem('status'); if (status instanceof HTMLSelectElement) { status.value = value; form?.requestSubmit(); } }} aria-pressed={query.status === value || (!query.status && value === 'open')}>{label}</button>)}</div>
        <label className="task-primary-filter">优先级筛选<select name="priority" defaultValue={query.priority || ''}><option value="">全部优先级</option>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
        <label className="task-primary-filter">负责人筛选<select name="assignee" defaultValue={query.assignee || 'all'}><option value="all">全部负责人</option><option value="me">由我负责</option><option value="unassigned">待认领</option></select></label>
        <label className="task-search-filter">关键词<input name="q" placeholder="搜索任务标题、描述…" defaultValue={query.q || ''} /></label>
        {enhanced && <div className="task-tabs task-view-switch" role="group" aria-label="任务视图"><button type="button" aria-label="列表" aria-pressed={view === 'list'} onClick={() => setView('list')}><List size={16} aria-hidden="true" /></button><button type="button" aria-label="看板" aria-pressed={view === 'board'} onClick={() => setView('board')}><Columns3 size={16} aria-hidden="true" /></button></div>}
        <details className="task-more-filters"><summary>更多筛选{(query.due || query.listId || query.tagId || query.status === 'todo' || query.status === 'doing') && <span aria-label="有附加筛选"> ·</span>}</summary><div>
          <label>状态<select name="status" defaultValue={query.status || 'open'}><option value="open">未完成</option><option value="all">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>
          <label>日期筛选<select name="due" defaultValue={query.due || ''}><option value="">全部日期</option><option value="today">今天到期</option><option value="overdue">已逾期</option></select></label>
          {enhanced && meta && <><label>清单筛选<select name="listId" defaultValue={query.listId || ''}><option value="">全部个人清单</option>{meta.labels.filter((item) => item.kind === 'list').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>标签筛选<select name="tagId" defaultValue={query.tagId || ''}><option value="">全部个人标签</option>{meta.labels.filter((item) => item.kind === 'tag').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></>}
        </div></details><button className="secondary-button task-apply-filter" aria-label="应用待办筛选">应用</button>
      </form><TaskLoadState {...list} />{list.data && <p className="task-result-count">当前筛选共 {list.data.total} 项，本页显示 {tasks.length} 项。{view === 'board' && enhanced ? '看板列仅统计当前页，翻页查看其余结果。' : ''}</p>}
      {list.data && !tasks.length && <div className="task-empty"><ClipboardList size={30} aria-hidden="true" /><h3>{list.data.items.length ? '当前页正在重新核对权限' : query.q ? '没有符合筛选的待办' : '这里还没有待办'}</h3><p>{list.data.items.length ? '旧任务内容已隐藏。' : '可调整范围或创建新的待办。'}</p></div>}
      {view === 'board' && enhanced ? <div className="task-board">{(Object.keys(statusLabels) as TaskStatus[]).map((status) => <section key={status} aria-label={`${statusLabels[status]}看板列`}><h3>{statusLabels[status]} <span>{tasks.filter((item) => item.status === status).length}</span></h3>{tasks.filter((item) => item.status === status).map((task) => <TaskRow key={task.id} task={task} online={state.online} onOpen={() => setSelected(task.id)} onAction={(next) => setAction({ task, action: next })} />)}</section>)}</div> : <div className="task-grouped-list">{['已逾期', '今天', '接下来', '无截止日期', '已完成'].map((group) => { const items = tasks.filter((task) => dateGroup(task) === group); return items.length ? <section key={group}><h3>{group} <span>{items.length}</span></h3>{items.map((task) => <TaskRow key={task.id} task={task} online={state.online} onOpen={() => setSelected(task.id)} onAction={(next) => setAction({ task, action: next })} />)}</section> : null; })}</div>}
      <div className="task-pagination">{query.after && <button className="secondary-button" onClick={() => setQuery({ ...query, after: undefined })}>待办首页</button>}{list.data?.nextCursor && <button className="secondary-button" disabled={list.loading} onClick={() => setQuery({ ...query, after: list.data!.nextCursor! })}>下一页待办</button>}<button className="text-button" disabled={!state.online || list.loading} onClick={list.retry}>重新核对列表</button></div>
    </>}</div></main></div>
    {settingsOpen && meta && <Modal open title="我的待办偏好" className="account-dialog task-preferences-dialog" icon={<ClipboardList size={21} />} dismissible={!settingsBusy} onClose={() => setSettingsOpen(false)}><TaskSettings client={client} meta={meta} conversations={conversations} onMetaChanged={metaResource.retry} onBusyChange={setSettingsBusy} /></Modal>}
    {selected && meta && <TaskDetail {...paging} client={client} taskId={selected} userId={userId} conversations={conversations} contacts={contacts} meta={meta} onOpenSource={onOpenSource} onClose={() => setSelected('')} onOpenTask={setSelected} />}
    {form && meta && <TaskForm {...paging} key={form.draft?.id || form.task?.id || 'new'} client={client} userId={userId} conversations={conversations} meta={meta} {...form} onSaved={(task) => { setForm(null); setSelected(task.id); setPanel('tasks'); }} onClose={() => setForm(null)} />}
    {action && <TaskActionDialog client={client} task={action.task} action={action.action} onClose={() => setAction(null)} />}
  </div>;
}
