import { useCallback, useState } from 'react';
import { Modal } from '../components/Modal';
import { FormField } from '../components/FormField';
import type { Conversation } from '../lib/chat-types';
import type { TaskClient } from '../lib/tasks-client';
import type { GroupTaskSettings, TaskLabel, TaskMeta, TaskPreferences } from '../lib/tasks-types';
import { CommandFeedback, taskError, TaskLoadState, useTaskCommand, useTaskResource, useTaskState } from './TaskShared';

export function TaskPreferencesForm({ client, preferences, onSaved }: { client: TaskClient; preferences: TaskPreferences; onSaved: () => void }) {
  const [values, setValues] = useState(preferences); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const state = useTaskState(client); const command = useTaskCommand(client);
  return <section className="task-settings-card"><h3>待办通知与默认时区</h3><p>分配、评论、完成和到期通知分别配置，仍尊重账号免打扰。提醒在站内投递，不承诺浏览器关闭后的系统推送。</p><form onSubmit={(event) => { event.preventDefault(); if (command.busy || !state.online) return; setError(''); try { new Intl.DateTimeFormat('zh-CN', { timeZone: values.timezone.trim() }).format(); } catch { setError('请输入有效时区。'); return; } const payload = { ...values, timezone: values.timezone.trim() }; void command.run(JSON.stringify({ kind: 'preferences', payload }), (key) => client.preferences(payload, key)).then((result) => { if (result.ok) { setValues(result.value); setNotice('待办通知偏好已保存。'); command.clear(); onSaved(); } }); }}><fieldset className="task-form-fields" disabled={command.busy || command.unknown}>{([['assignments', '负责人分配通知'], ['comments', '评论通知'], ['completed', '完成通知'], ['due', '到期提醒通知']] as const).map(([key, text]) => <label key={key} className="task-check"><input type="checkbox" checked={values[key]} onChange={(event) => { setValues({ ...values, [key]: event.target.checked }); setNotice(''); }} />{text}</label>)}<FormField label="新待办默认时区" required value={values.timezone} onChange={(event) => setValues({ ...values, timezone: event.target.value })} /></fieldset>{error && <p role="alert" className="task-error">{error}</p>}<CommandFeedback {...command} /><button className="primary-button" disabled={!state.online || command.busy}>{command.unknown ? '核对并重试同一偏好设置' : '保存待办偏好'}</button>{notice && <p role="status" className="success-note">{notice}</p>}</form></section>;
}
function LabelDialog({ client, label, kind, remove = false, onClose, onSaved }: { client: TaskClient; label?: TaskLabel; kind: 'list' | 'tag'; remove?: boolean; onClose: () => void; onSaved: () => void }) {
  const state = useTaskState(client); const command = useTaskCommand(client); const [name, setName] = useState(label?.name || ''); const [confirmed, setConfirmed] = useState(false); const title = `${remove ? '删除' : label ? '重命名' : '创建'}个人${kind === 'list' ? '清单' : '标签'}`;
  return <Modal open title={title} onClose={onClose} dismissible={!command.busy}><form className="task-form-fields" onSubmit={(event) => { event.preventDefault(); if (command.busy || !state.online || (remove ? !confirmed : !name.trim())) return; const payload = { kind, name: name.trim() }; void command.run<TaskLabel | { deleted: boolean }>(JSON.stringify({ kind: remove ? 'label.delete' : 'label.save', id: label?.id, payload }), (key) => remove ? client.removeLabel(label!.id, key) : client.saveLabel(payload, label?.id, key)).then((result) => { if (result.ok) { onSaved(); onClose(); } }); }}><fieldset disabled={command.busy || command.unknown}>{remove ? <><p>删除“{label?.name}”的分类关系，不删除待办实体。</p><label className="task-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />我确认删除该分类</label></> : <FormField label="分类名称" required value={name} onChange={(event) => setName(event.target.value)} />}</fieldset><CommandFeedback {...command} /><button className="primary-button" disabled={!state.online || command.busy || (remove && !confirmed)}>{command.unknown ? '核对并重试同一分类操作' : title}</button></form></Modal>;
}
export function GroupTaskPolicy({ client, groupId }: { client: TaskClient; groupId: string }) {
  const state = useTaskState(client); const resource = useTaskResource(useCallback(() => client.groupSettings(groupId), [client, groupId, state.listRevision]), state.online); const command = useTaskCommand(client);
  const [base, setBase] = useState<GroupTaskSettings | null>(null); const [choice, setChoice] = useState<'members' | 'managers'>('members'); const [conflict, setConflict] = useState<GroupTaskSettings | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const data = resource.data;
  async function submit() {
    if (!data?.canManage || !base || !state.online || command.busy || conflict) return; setError('');
    const result = await command.run(JSON.stringify({ kind: 'group.policy', groupId, etag: base.etag, choice }), (key) => client.changeGroupSettings(base, choice, key));
    if (result.ok) { setBase(null); setNotice('群任务创建策略已保存。'); command.clear(); resource.retry(); }
    else { try { const latest = await client.groupSettings(groupId); if (latest.etag !== base.etag) setConflict(latest); } catch (cause) { setError(`最新群策略读取失败：${taskError(cause)}`); } }
  }
  return <section className="task-settings-card"><h3>群任务创建策略</h3><TaskLoadState {...resource} />{data && <><p>当前任务占用 {data.count} / {data.quota} · {data.createPolicy === 'members' ? '当前成员可创建' : '仅群管理者可创建'}</p>{data.writeReason && <p className="warning-note">{data.writeReason}</p>}{data.canManage ? <form onSubmit={(event) => { event.preventDefault(); void submit(); }}><label className="form-field">允许创建任务的人<select value={base ? choice : data.createPolicy} disabled={command.busy || command.unknown} onChange={(event) => { if (!base) setBase(data); setChoice(event.target.value as typeof choice); setNotice(''); }}><option value="members">当前群成员</option><option value="managers">仅群主和管理员</option></select></label><CommandFeedback {...command} />{conflict && <section className="task-conflict"><p>群策略版本已改变。我的选择：{choice === 'members' ? '当前成员' : '仅管理者'}；最新：{conflict.createPolicy === 'members' ? '当前成员' : '仅管理者'}。</p><button className="secondary-button" type="button" onClick={() => { setBase(conflict); setConflict(null); command.clear(); }}>采用最新策略版本，保留我的选择</button></section>}<button className="primary-button" disabled={!base || !state.online || command.busy || !!conflict}>确认保存群策略</button></form> : <p className="task-hint">只有服务器授予管理能力的人可以调整此策略。</p>}</>}{error && <p role="alert" className="task-error">{error}</p>}{notice && <p role="status" className="success-note">{notice}</p>}</section>;
}
export function TaskSettings({ client, meta, conversations, onMetaChanged, onClose }: { client: TaskClient; meta: TaskMeta; conversations: Conversation[]; onMetaChanged: () => void; onClose?: () => void }) {
  const state = useTaskState(client); const [editor, setEditor] = useState<{ label?: TaskLabel; kind: 'list' | 'tag'; remove?: boolean } | null>(null); const [groupId, setGroupId] = useState('');
  return <section className="task-settings"><header className="task-page-heading"><div><h2>偏好、分类与群策略</h2><p>清单、标签、关注和收藏均不改变任务访问权限。</p></div>{onClose && <button className="secondary-button" onClick={onClose}>返回待办</button>}</header>{meta.enhanced && state.enhanced && <><TaskPreferencesForm client={client} preferences={meta.preferences} onSaved={onMetaChanged} /><section className="task-settings-card"><h3>个人清单与标签</h3><div className="task-actions"><button className="secondary-button" disabled={!state.online} onClick={() => setEditor({ kind: 'list' })}>创建个人清单</button><button className="secondary-button" disabled={!state.online} onClick={() => setEditor({ kind: 'tag' })}>创建个人标签</button></div>{meta.labels.length ? <ul className="task-label-list">{meta.labels.map((item) => <li key={item.id}><span>{item.kind === 'list' ? '清单' : '标签'} · {item.name}</span><div className="task-actions"><button className="text-button" disabled={!state.online} onClick={() => setEditor({ label: item, kind: item.kind })}>重命名 {item.name}</button><button className="text-button danger-text" disabled={!state.online} onClick={() => setEditor({ label: item, kind: item.kind, remove: true })}>删除 {item.name}</button></div></li>)}</ul> : <p>尚未创建个人分类。</p>}</section></>}
    <section className="task-settings-card"><label className="form-field">选择要查看策略的群<select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">选择当前群</option>{conversations.filter((item) => item.kind === 'group').map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label></section>{groupId && <GroupTaskPolicy key={groupId} client={client} groupId={groupId} />}{editor && <LabelDialog client={client} {...editor} onClose={() => setEditor(null)} onSaved={onMetaChanged} />}
  </section>;
}
