import { useCallback, useState } from 'react';
import type { TaskClient } from '../lib/tasks-client';
import type { Task, TaskDraft } from '../lib/tasks-types';
import { CommandFeedback, TaskConflict, taskError, TaskLoadState, timeText, useTaskCommand, useTaskResource, useTaskState } from './TaskShared';

type TaskDraftsProps = { client: TaskClient; onReview: (draft: TaskDraft, latest: Task | null) => void; onClose?: () => void };
export function TaskDrafts(props: TaskDraftsProps) { return <Drafts key={props.client.userId} {...props} />; }
function Drafts({ client, onReview, onClose }: TaskDraftsProps) {
  const state = useTaskState(client); const resource = useTaskResource(useCallback(() => client.drafts(), [client])); const command = useTaskCommand(client); const [review, setReview] = useState<{ draft: TaskDraft; latest: Task | null; expired: boolean } | null>(null); const [confirmed, setConfirmed] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [deleteId, setDeleteId] = useState<string | null>(null);
  const drafts = resource.data?.filter((item) => item.userId === client.userId) || [];
  async function inspect(draft: TaskDraft) { if (command.busy || !state.online) return; setNotice(''); setError(''); setReview(null); setConfirmed(false); const result = await command.run(`review:${draft.id}:${draft.updatedAt}`, () => client.reviewDraft(draft)); if (result.ok) setReview(result.value); }
  async function copy(draft: TaskDraft) { setError(''); setNotice(''); try { await navigator.clipboard.writeText([draft.payload.title || '', draft.payload.description || ''].filter(Boolean).join('\n\n')); setNotice('已复制本机输入，请自行保存在安全的位置。'); } catch (cause) { setError(`无法复制：${taskError(cause)}`); } }
  async function freshDraft() { if (!review || !confirmed || command.busy) return; const { draft } = review; const result = await command.run(`fresh-draft:${draft.id}:${draft.updatedAt}`, () => client.saveDraft({ taskId: draft.taskId, kind: draft.kind, payload: draft.payload, baseEtag: draft.baseEtag })); if (result.ok) { setReview(null); setConfirmed(false); setNotice('已创建新的本机草稿，尚未提交。请对新草稿重新执行联网复核。'); resource.retry(); } }
  return <section className="task-drafts"><header className="task-page-heading"><div><h2>本机任务草稿</h2><p>与聊天待发队列分开保存。恢复网络不会自动创建、改派、认领、删除或分享待办。</p></div>{onClose && <button className="secondary-button" onClick={onClose}>返回待办</button>}</header><p className="warning-note">草稿按账号隔离。7 天后仍可查看或复制，但不能直接提交；需本人确认建立新草稿。</p><TaskLoadState {...resource} /><CommandFeedback {...command} />{error && <p role="alert" className="task-error">{error}</p>}{notice && <p role="status" className="success-note">{notice}</p>}
    {resource.data && !drafts.length && <p className="task-empty">当前账号没有本机任务草稿。</p>}<ul className="task-draft-list">{drafts.map((draft) => { const invalid = !!draft.taskId && !!state.invalid[draft.taskId]; return <li key={draft.id}><h3>{invalid ? '待办访问状态待核对' : draft.payload.title || (draft.kind === 'edit' ? '待办修改草稿' : '未命名创建草稿')}</h3><p>{draft.kind === 'edit' ? '修改草稿' : '创建草稿'} · 保存 {timeText(draft.updatedAt)} · {draft.expiresAt <= Date.now() ? '已过期，不能直接提交' : `到期 ${timeText(draft.expiresAt)}`}</p>{!invalid && <details><summary>查看本机输入</summary><p className="task-description">{draft.payload.description || '无描述输入。'}</p></details>}<div className="task-actions"><button className="secondary-button" disabled={!state.online || command.busy} onClick={() => void inspect(draft)}>联网核对身份、权限与版本</button><button className="text-button" disabled={invalid} onClick={() => void copy(draft)}>复制本机输入</button><button className="text-button danger-text" disabled={command.busy} onClick={() => setDeleteId(draft.id)}>删除本机草稿</button></div>{deleteId === draft.id && <div className="task-confirm-inline"><p>只删除这份本机草稿，不修改服务器待办。</p><button className="secondary-button danger-text" disabled={command.busy} onClick={() => void command.run(`delete-draft:${draft.id}`, () => client.deleteDraft(draft.id)).then((result) => { if (result.ok) { setDeleteId(null); if (review?.draft.id === draft.id) setReview(null); resource.retry(); } })}>确认删除此草稿</button><button className="text-button" onClick={() => setDeleteId(null)}>取消</button></div>}</li>; })}</ul>
    {review && <section className="task-draft-review" aria-label="草稿复核结果"><h3>联网复核结果</h3><p>服务器已重新核对当前身份{review.latest ? '并读取当前可访问的任务版本' : '；创建范围将在表单中再次核对'}。</p>{review.expired ? <><p className="warning-note">此草稿已过期，不能直接提交旧草稿。</p><label className="task-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />我已重新核对这些输入，确认仅创建新的本机草稿</label><button className="secondary-button" disabled={!confirmed || command.busy} onClick={() => void freshDraft()}>以此输入创建新草稿</button></> : review.latest ? <TaskConflict review disabled={!state.online || !review.latest.capabilities.edit} latest={review.latest} draft={review.draft.payload as Record<string, unknown>} onAccept={() => onReview(review.draft, review.latest)} /> : <><dl className="task-facts"><div><dt>本机标题</dt><dd>{review.draft.payload.title || '未填写'}</dd></div><div><dt>本机描述</dt><dd className="task-description">{review.draft.payload.description || '未填写'}</dd></div></dl><label className="task-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />我确认打开表单，重新核对创建范围和内容</label><button className="primary-button" disabled={!confirmed || !state.online} onClick={() => onReview(review.draft, null)}>打开表单核对提交</button></>}{review.latest && !review.latest.capabilities.edit && <p className="warning-note">{review.latest.capabilities.writeReason || '当前没有编辑权限，不能提交该修改草稿。'}</p>}</section>}
  </section>;
}
