import { type TaskConversationPaging } from './TaskShared';
import { useCallback, useEffect, useState } from 'react';
import { Modal } from '../components/Modal';
import type { Contact, Conversation } from '../lib/chat-types';
import type { TaskClient } from '../lib/tasks-client';
import type { Task, TaskMeta } from '../lib/tasks-types';
import { TaskActionDialog, type TaskAction } from './TaskActionDialog';
import { TaskActivityPanel, TaskReportDialog } from './TaskActivityPanel';
import { TaskAssignmentDialog, TaskForm } from './TaskForm';
import { TaskShareDialog } from './TaskShareDialog';
import { priorityLabels, statusLabels, TaskBadge, taskError, TaskLoadState, TaskUnavailable, timeText, useLiveTask, useTaskResource } from './TaskShared';

export type TaskDetailProps = { client: TaskClient; taskId: string; userId: string; conversations: Conversation[]; contacts: Contact[]; meta: TaskMeta; onOpenSource: (messageId: string) => void | Promise<void>; onClose: () => void; onOpenTask?: (id: string) => void } & TaskConversationPaging;
export function TaskDetail(props: TaskDetailProps) { return <Detail key={`${props.userId}:${props.taskId}`} {...props} />; }
function Detail({ client, taskId, userId, conversations, contacts, meta, onOpenSource, onClose, onOpenTask, ...paging }: TaskDetailProps) {
  const { state, invalid } = useLiveTask(client, taskId); const task = state.entities[taskId];
  const resource = useTaskResource(useCallback(() => client.get(taskId), [client, taskId, state.listRevision]), state.online);
  const [action, setAction] = useState<TaskAction | null>(null); const [form, setForm] = useState<'edit' | 'copy' | null>(null); const [share, setShare] = useState(false); const [assign, setAssign] = useState(false); const [report, setReport] = useState<{ commentId?: string } | null>(null); const [sourceError, setSourceError] = useState(''); const [sourceBusy, setSourceBusy] = useState(false);
  useEffect(() => { if (!task || task.viewerId !== userId) { setAction(null); setForm(null); setShare(false); setAssign(false); setReport(null); setSourceError(''); } }, [task, userId]);
  function saved(next: Task) { setForm(null); if (next.id !== taskId) onOpenTask?.(next.id); }
  if (client.userId !== userId || meta.actorId !== userId) return <Modal open title="待办详情" onClose={onClose}><TaskUnavailable onClose={onClose} /></Modal>;
  if (!task || task.viewerId !== userId) return <Modal open title="待办详情" onClose={onClose}><TaskLoadState {...resource} /><TaskUnavailable onClose={onClose} onRetry={resource.retry} /></Modal>;
  return <><Modal open title="待办详情" onClose={onClose}>{invalid ? <><TaskLoadState {...resource} /><TaskUnavailable onClose={onClose} onRetry={resource.retry} /></> : <article className="task-detail"><header><TaskBadge task={task} /><h2>{task.title}</h2><div className="task-detail-meta"><span className={`task-status ${task.status}`}>{statusLabels[task.status]}</span><span>优先级 {priorityLabels[task.priority]}</span>{task.overdue && <strong className="task-overdue">已逾期</strong>}</div></header>
    <TaskLoadState {...resource} />{!state.online && <p className="warning-note">当前离线；不能提交状态、指派、删除或分享。编辑内容可另存本机草稿。</p>}
    {task.deletedAt && <p className="warning-note">此待办已进入回收期：{timeText(task.deletedAt)}。只提供服务器允许的恢复操作。</p>}
    {task.capabilities.writeReason && <p className="warning-note">{task.capabilities.writeReason}</p>}
    <section aria-label="待办属性"><dl className="task-facts"><div><dt>负责人</dt><dd>{task.assignee ? `${task.assignee.nickname} (@${task.assignee.username})` : '待认领'}</dd></div><div><dt>截止日期</dt><dd>{task.dueOn || '无截止日期'}{task.dueOn && ` · ${task.dueTimezone}`}</dd></div><div><dt>创建者</dt><dd>{task.creator.nickname}</dd></div><div><dt>创建 / 更新</dt><dd>{timeText(task.createdAt)} / {timeText(task.updatedAt)}</dd></div><div><dt>当前版本</dt><dd>{task.version}</dd></div></dl></section>
    {!task.deletedAt && <><div className="task-actions" aria-label="状态操作">{task.capabilities.progress && Object.entries(statusLabels).map(([value, label]) => <button key={value} className="secondary-button" disabled={!state.online || task.status === value} onClick={() => setAction({ kind: 'status', status: value as Task['status'] })}>设为{label}</button>)}{task.capabilities.claim && <button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'claim' })}>认领此待办</button>}{task.capabilities.release && <button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'release' })}>释放负责人</button>}{task.capabilities.assign && task.scope === 'group' && <button className="secondary-button" disabled={!state.online} onClick={() => setAssign(true)}>调整负责人</button>}</div>
    <section><h3>描述</h3><p className="task-description">{task.description || '尚无描述。'}</p></section>
    <section><div className="task-section-heading"><h3>检查项</h3><span>{task.checkItems.filter((item) => item.done).length} / {task.checkItems.length}</span></div>{task.checkItems.length ? <ul className="task-check-list">{task.checkItems.map((item) => <li key={item.id}><label><input type="checkbox" checked={item.done} disabled={!state.online || !task.capabilities.checkToggle} onChange={() => setAction({ kind: 'check.toggle', item })} /><span>{item.text}</span></label>{task.capabilities.checkStructure && <div className="task-actions"><button className="text-button" disabled={!state.online} onClick={() => setAction({ kind: 'check.edit', item })}>编辑检查项</button><button className="text-button" disabled={!state.online} onClick={() => setAction({ kind: 'check.remove', item })}>删除检查项</button></div>}</li>)}</ul> : <p className="task-hint">没有检查项。</p>}{task.capabilities.checkStructure && <button className="secondary-button" disabled={!state.online || task.checkItems.length >= meta.limits.checkItems} onClick={() => setAction({ kind: 'check.add' })}>添加检查项</button>}<p className="task-hint">最多 {meta.limits.checkItems} 项；检查项没有独立负责人。</p></section>
    <section><h3>来源消息</h3>{task.source?.available && task.source.messageId ? <><p className="task-source-preview">{task.source.text || '来源消息没有文本预览。'}</p><button className="secondary-button" disabled={sourceBusy || !state.online} onClick={() => { setSourceError(''); setSourceBusy(true); void Promise.resolve().then(() => onOpenSource(task.source!.messageId!)).catch((cause) => setSourceError(taskError(cause))).finally(() => setSourceBusy(false)); }}>查看有权访问的来源消息</button></> : <p>{task.source ? '来源消息当前不可读，旧标识与内容不再展示。任务作为独立实体保留。' : '此待办没有来源消息。'}</p>}{sourceError && <p role="alert" className="task-error">{sourceError}</p>}</section>

    </>}
    <section><h3>待办操作</h3><div className="task-actions">{task.capabilities.edit && <button className="secondary-button" onClick={() => setForm('edit')}>编辑待办</button>}{task.capabilities.share && <button className="secondary-button" disabled={!state.online} onClick={() => setShare(true)}>{task.scope === 'personal' ? '分享静态副本' : '发送实时引用'}</button>}{task.capabilities.copyToGroup && <button className="secondary-button" disabled={!state.online} onClick={() => setForm('copy')}>创建群副本</button>}{meta.enhanced && state.enhanced && !task.deletedAt && <><button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'reminder' })}>到期提醒</button><button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'mark', field: 'followed', value: !task.followed })}>{task.followed ? '取消关注待办' : '关注待办'}</button><button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'mark', field: 'bookmarked', value: !task.bookmarked })}>{task.bookmarked ? '取消收藏待办' : '收藏待办'}</button><button className="text-button" disabled={!state.online} onClick={() => setReport({})}>举报此待办</button></>}{task.capabilities.remove && <button className="secondary-button danger-text" disabled={!state.online} onClick={() => setAction({ kind: 'remove' })}>删除待办</button>}{task.capabilities.restore && <button className="secondary-button" disabled={!state.online} onClick={() => setAction({ kind: 'restore' })}>恢复待办</button>}</div></section>
    </article>}{!task.deletedAt && <TaskActivityPanel client={client} task={task} enhanced={meta.enhanced && state.enhanced} onRemoveComment={(commentId) => setAction({ kind: 'comment.remove', commentId })} onReportComment={(commentId) => setReport({ commentId })} />}{!invalid && <button className="text-button" onClick={onClose}>关闭详情</button>}</Modal>
    {action && <TaskActionDialog client={client} task={task} action={action} onClose={() => setAction(null)} onChanged={resource.retry} />}{form && <TaskForm {...paging} client={client} userId={userId} conversations={conversations} meta={meta} task={task} mode={form} onSaved={saved} onClose={() => setForm(null)} />}{assign && <TaskAssignmentDialog client={client} task={task} userId={userId} onClose={() => setAssign(false)} />}{share && <TaskShareDialog {...paging} client={client} task={task} conversations={conversations} contacts={contacts} onClose={() => setShare(false)} />}{report && <TaskReportDialog client={client} task={task} commentId={report.commentId} onClose={() => setReport(null)} />}
  </>;
}
