import { useContext, useState } from 'react';
import type { AdminAdministrators } from '../lib/admin-s3-types';
import { ActionButton, AdminContext, AdminLink, DataTable, dateText, EmptyRow, identityText, PageHeading, Pagination, queryPath, ResourceState, statusText, useResource } from './AdminShared';

export function AdministratorsPage({ params }: { params: URLSearchParams }) {
  const { openAction } = useContext(AdminContext); const [userId, setUserId] = useState('');
  const resource = useResource<AdminAdministrators>(queryPath('/api/v1/admin/administrators', { after: params.get('after') || '', limit: '50' }));
  return <><PageHeading title="管理员与第二因素" description="邀请由账号本人验证密码并绑定 TOTP 后生效。撤权保留普通账号，最后一位可用管理员由服务器事务保护。" />
    <section className="admin-panel"><h2>邀请管理员</h2><form className="admin-s3-form" onSubmit={(event) => { event.preventDefault(); if (userId.trim()) openAction({ action: 'administrator.invite', targetIds: [userId.trim()], labels: [`账号 ${userId.trim()}`], parameters: {} }); }}><label>被邀请账号 ID<input required value={userId} onChange={(event) => setUserId(event.target.value)} /></label><p>邀请有效期 24 小时；请本人前往账号设置完成绑定。</p><button className="primary-button">预览管理员邀请</button></form></section>
    <ResourceState {...resource} />{resource.data && <><DataTable caption="站点管理员" headings={['账号', '因素 / 可用状态', '设备 / 最近活动', '操作']}>{resource.data.administrators.items.length ? resource.data.administrators.items.map((item) => <tr key={item.user.id}><th scope="row"><AdminLink href={`/admin/users/${encodeURIComponent(item.user.id)}`}>{identityText(item.user)}</AdminLink></th><td>{statusText(item.status)} · {item.usable ? '可用' : '不可用'}<br />{item.hasSecondFactor ? '已绑定第二因素' : '尚未绑定第二因素'}</td><td><AdminLink href={`/admin/sessions?userId=${encodeURIComponent(item.user.id)}`}>{item.sessionCount} 个设备会话</AdminLink><br />{dateText(item.lastSeenAt)}</td><td><div className="admin-actions"><ActionButton request={{ action: 'administrator.revoke', targetIds: [item.user.id], labels: [identityText(item.user)], parameters: {} }}>撤销管理权限</ActionButton><ActionButton request={{ action: 'administrator.factor_reset', targetIds: [item.user.id], labels: [identityText(item.user)], parameters: {}, parameterSummary: [{ label: '恢复流程', value: '人工核验后使旧因素和全部设备失效，先降为普通账号并重新邀请绑定。' }] }}>人工恢复第二因素</ActionButton><ActionButton request={{ action: 'user.ban', targetIds: [item.user.id], labels: [identityText(item.user)] }}>停用账号</ActionButton></div></td></tr>) : <EmptyRow count={4} />}</DataTable><Pagination page={resource.data.administrators} params={params} path="/admin/administrators" />
    <section className="admin-panel"><h2>管理邀请</h2><p>最多显示最近 100 条邀请。</p><DataTable caption="最近管理邀请" headings={['账号 / 邀请者', '用途', '状态 / 到期', '操作']}>{resource.data.invitations.length ? resource.data.invitations.map((item) => <tr key={item.id}><th scope="row">{identityText(item.user)}<small>邀请者：{identityText(item.inviter)}</small></th><td>{item.purpose === 'factor_reset' ? '重新绑定第二因素' : '授予管理权限'}</td><td>{statusText(item.status)}<br />{dateText(item.expiresAt)}</td><td><ActionButton disabled={item.status !== 'pending'} request={{ action: 'administrator.cancel', targetIds: [item.id], labels: [identityText(item.user)], parameters: {} }}>取消邀请</ActionButton></td></tr>) : <EmptyRow count={4} />}</DataTable></section></>}
  </>;
}
