import type { AdminApplication, AdminGroup, AdminGroupDetail, AdminInvite, AdminMember, AdminPage } from '../lib/admin-types';
import { ActionButton, AdminLink, DataTable, dateText, EmptyRow, FilterForm, identityText, PageHeading, Pagination, queryPath, ResourceState, SelectFilter, statusText, useResource } from './AdminShared';

export function GroupsPage({ params }: { params: URLSearchParams }) {
  const query = new URLSearchParams(params); query.set('limit', '50'); const resource = useResource<AdminPage<AdminGroup>>(queryPath('/api/v1/admin/groups', query));
  return <><PageHeading title="群聊管理" description="查看群聊状态、群主和成员数量，管理动作均记录理由。" /><FilterForm path="/admin/groups"><label className="admin-filter">搜索群名<input name="q" defaultValue={params.get('q') || ''} /></label><label className="admin-filter">群主编号<input name="ownerId" defaultValue={params.get('ownerId') || ''} /></label><SelectFilter label="群聊状态" name="status" value={params.get('status') || ''} options={ [['', '全部状态'], ['active', '正常'], ['frozen', '冻结'], ['dissolved', '已解散']] } /></FilterForm><ResourceState {...resource} />{resource.data && <><DataTable caption="群聊列表" headings={['群聊', '群主', '状态', '成员数', '创建 / 更新时间']}>{resource.data.items.length ? resource.data.items.map((group) => <tr key={group.id}><th scope="row"><AdminLink href={`/admin/groups/${encodeURIComponent(group.id)}`}>{group.name}</AdminLink><small>{group.id}</small></th><td><AdminLink href={`/admin/users/${encodeURIComponent(group.owner.id)}`}>{identityText(group.owner)}</AdminLink></td><td>{statusText(group.status)}</td><td>{group.memberCount}</td><td>{dateText(group.createdAt)}<br />{dateText(group.updatedAt)}</td></tr>) : <EmptyRow count={5} />}</DataTable><Pagination page={resource.data} params={params} path="/admin/groups" /></>}</>;
}
function Members({ id, params, disabled }: { id: string; params: URLSearchParams; disabled: boolean }) {
  const resource = useResource<AdminPage<AdminMember>>(queryPath(`/api/v1/admin/groups/${encodeURIComponent(id)}/members`, { after: params.get('membersAfter') || '', limit: '50' }));
  return <><ResourceState {...resource} />{resource.data && <><DataTable caption="群成员" headings={['成员', '角色', '加入 / 禁言至', '管理操作']}>{resource.data.items.length ? resource.data.items.map((member) => <tr key={member.id}><th scope="row"><AdminLink href={`/admin/users/${encodeURIComponent(member.user.id)}`}>{identityText(member.user)}</AdminLink></th><td>{statusText(member.role)}</td><td>{dateText(member.joinedAt)}<br />{member.mutedUntil === null ? '未禁言' : dateText(member.mutedUntil)}</td><td>{member.role === 'owner' ? '群主纠正在群操作中处理' : <div className="admin-actions"><ActionButton disabled={disabled} request={{ action: 'group.member.role', targetIds: [member.id], labels: [identityText(member.user)], initial: { role: member.role } }}>纠正角色</ActionButton><ActionButton disabled={disabled} request={{ action: 'group.member.mute', targetIds: [member.id], labels: [identityText(member.user)] }}>禁言</ActionButton>{member.mutedUntil !== null && <ActionButton disabled={disabled} request={{ action: 'group.member.unmute', targetIds: [member.id], labels: [identityText(member.user)] }}>解除禁言</ActionButton>}<ActionButton disabled={disabled} request={{ action: 'group.member.remove', targetIds: [member.id], labels: [identityText(member.user)] }}>移出群聊</ActionButton></div>}</td></tr>) : <EmptyRow count={4} />}</DataTable><Pagination page={resource.data} params={params} path={`/admin/groups/${encodeURIComponent(id)}`} cursorKey="membersAfter" /></>}</>;
}
function Invites({ id, params, disabled }: { id: string; params: URLSearchParams; disabled: boolean }) {
  const resource = useResource<AdminPage<AdminInvite>>(queryPath(`/api/v1/admin/groups/${encodeURIComponent(id)}/invites`, { after: params.get('invitesAfter') || '', limit: '50' }));
  return <><ResourceState {...resource} />{resource.data && <><DataTable caption="群邀请元数据" headings={['创建者 / 受邀者', '类型 / 状态', '使用 / 预留 / 上限', '创建 / 到期', '操作']}>{resource.data.items.length ? resource.data.items.map((invite) => <tr key={invite.id}><th scope="row">{identityText(invite.creator)}<small>{invite.target ? identityText(invite.target) : '通过邀请链接加入'}</small></th><td>{invite.kind === 'link' ? '链接' : '定向邀请'} / {statusText(invite.status)}</td><td>{invite.used} / {invite.reserved} / {invite.maxUses}</td><td>{dateText(invite.createdAt)}<br />{dateText(invite.expiresAt)}</td><td><ActionButton disabled={disabled || invite.status !== 'active'} request={{ action: 'group.invite.revoke', targetIds: [invite.id], labels: [`${identityText(invite.creator)} 创建的邀请 · ${invite.id}`] }}>撤销邀请</ActionButton></td></tr>) : <EmptyRow count={5} />}</DataTable><Pagination page={resource.data} params={params} path={`/admin/groups/${encodeURIComponent(id)}`} cursorKey="invitesAfter" /></>}</>;
}
function Applications({ id, params }: { id: string; params: URLSearchParams }) {
  const resource = useResource<AdminPage<AdminApplication>>(queryPath(`/api/v1/admin/groups/${encodeURIComponent(id)}/applications`, { after: params.get('applicationsAfter') || '', limit: '50' }));
  return <><ResourceState {...resource} />{resource.data && <><DataTable caption="入群申请元数据" headings={['申请人', '状态', '创建 / 更新时间', '到期时间', '邀请编号']}>{resource.data.items.length ? resource.data.items.map((application) => <tr key={application.id}><th scope="row"><AdminLink href={`/admin/users/${encodeURIComponent(application.user.id)}`}>{identityText(application.user)}</AdminLink></th><td>{statusText(application.status)}</td><td>{dateText(application.createdAt)}<br />{dateText(application.updatedAt)}</td><td>{dateText(application.expiresAt)}</td><td>{application.inviteId}</td></tr>) : <EmptyRow count={5} />}</DataTable><Pagination page={resource.data} params={params} path={`/admin/groups/${encodeURIComponent(id)}`} cursorKey="applicationsAfter" /></>}</>;
}
export function GroupDetailPage({ id, params }: { id: string; params: URLSearchParams }) {
  const resource = useResource<AdminGroupDetail>(`/api/v1/admin/groups/${encodeURIComponent(id)}`); const group = resource.data?.group;
  return <><PageHeading title="群聊详情" description="成员、邀请和申请分别分页；邀请凭据与申请正文不会展示。"><AdminLink href="/admin/groups">返回群聊列表</AdminLink></PageHeading><ResourceState {...resource} />{group && <><section className="admin-panel"><h2>{group.name}</h2><p>{group.description || '尚未填写简介'}</p><dl className="admin-facts">{([['群编号', group.id], ['群主', identityText(group.owner)], ['状态', statusText(group.status)], ['成员数', String(group.memberCount)], ['全员禁言', group.everyoneMuted ? '已开启' : '未开启'], ['入群审核', group.reviewRequired ? '需要审核' : '无需审核'], ['邀请权限', group.inviteRole === 'members' ? '所有成员' : '群管理者'], ['创建时间', dateText(group.createdAt)], ['更新时间', dateText(group.updatedAt)]]).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{group.status !== 'dissolved' && <div className="admin-actions"><ActionButton request={{ action: group.status === 'frozen' ? 'conversation.unfreeze' : 'conversation.freeze', targetIds: [group.id], labels: [group.name] }}>{group.status === 'frozen' ? '解冻群聊' : '冻结群聊'}</ActionButton><ActionButton request={{ action: 'group.owner.change', targetIds: [group.id], labels: [group.name], groupId: group.id }}>纠正群主</ActionButton><ActionButton request={{ action: 'group.dissolve', targetIds: [group.id], labels: [group.name] }}>解散群聊</ActionButton></div>}</section><section className="admin-panel"><h2>群成员</h2><Members id={id} params={params} disabled={group.status === 'dissolved'} /></section><section className="admin-panel"><h2>群邀请</h2><Invites id={id} params={params} disabled={group.status === 'dissolved'} /></section><section className="admin-panel"><h2>入群申请</h2><Applications id={id} params={params} /></section></>}</>;
}
