import type { AdminConnection, AdminPage, AdminSession } from '../lib/admin-types';
import { ActionButton, AdminLink, DataTable, dateText, EmptyRow, FilterForm, identityText, PageHeading, Pagination, queryPath, ResourceState, SelectFilter, useResource, useSelection } from './AdminShared';

export function SessionsPage({ params }: { params: URLSearchParams }) {
  const userId = params.get('userId') || ''; const query = new URLSearchParams({ userId, state: params.get('state') || 'active', after: params.get('after') || '', limit: '50' });
  const resource = useResource<AdminPage<AdminSession>>(queryPath('/api/v1/admin/sessions', query));
  const connections = useResource<AdminPage<AdminConnection>>(queryPath('/api/v1/admin/connections', { userId, after: params.get('connectionsAfter') || '', limit: '50' }));
  const { selected, toggle } = useSelection(); const rows = resource.data?.items || [];
  return <><PageHeading title="会话与连接" description="分别查看登录设备和实时连接；连接可能在翻页时自然断开。" /><FilterForm path="/admin/sessions"><label className="admin-filter">用户编号<input name="userId" defaultValue={userId} placeholder="全部用户" /></label><SelectFilter label="会话状态" name="state" value={params.get('state') || 'active'} options={ [['active', '有效会话'], ['revoked', '已撤销'], ['expired', '已到期'], ['all', '全部会话']] } /></FilterForm><section className="admin-panel"><h2>登录会话</h2><ResourceState {...resource} />{resource.data && <><div className="admin-bulk"><span>已选 {selected.length} 个会话</span><ActionButton request={{ action: 'session.revoke', targetIds: selected, labels: rows.filter((session) => selected.includes(session.id)).map((session) => `${identityText(session.user)} · ${session.device}${session.current ? '（当前会话）' : ''}`) }}>撤销所选会话</ActionButton></div><DataTable caption="登录会话列表" headings={['选择', '用户', '设备', '登录 / 最近活动', '到期 / 撤销', '状态 / 连接', '操作']}>{rows.length ? rows.map((session) => <tr key={session.id}><td><input type="checkbox" aria-label={`选择会话 ${session.id}`} checked={selected.includes(session.id)} disabled={!session.active} onChange={(event) => toggle(session.id, event.target.checked)} /></td><th scope="row"><AdminLink href={`/admin/users/${encodeURIComponent(session.user.id)}`}>{identityText(session.user)}</AdminLink></th><td>{session.device || '未知设备'}{session.current && <strong className="admin-badge">当前会话</strong>}<small>{session.id}</small></td><td>{dateText(session.createdAt)}<br />{dateText(session.lastSeenAt)}</td><td>{dateText(session.expiresAt)}<br />{session.revokedAt === null ? '未撤销' : dateText(session.revokedAt)}</td><td>{session.active ? '有效' : '已失效'} / {session.connectionCount}</td><td><ActionButton disabled={!session.active} request={{ action: 'session.revoke', targetIds: [session.id], labels: [`${identityText(session.user)} · ${session.device}${session.current ? '（当前会话）' : ''}`] }}>撤销会话</ActionButton></td></tr>) : <EmptyRow count={7} />}</DataTable><Pagination page={resource.data} path="/admin/sessions" params={params} /></>}</section><section className="admin-panel"><h2>实时连接</h2><ResourceState {...connections} />{connections.data && <><DataTable caption="实时连接列表" headings={['连接编号', '用户编号', '所属会话', '建立时间']}>{connections.data.items.length ? connections.data.items.map((connection) => <tr key={connection.id}><th scope="row">{connection.id}</th><td><AdminLink href={`/admin/users/${encodeURIComponent(connection.userId)}`}>{connection.userId}</AdminLink></td><td>{connection.sessionId}</td><td>{dateText(connection.connectedAt)}</td></tr>) : <EmptyRow count={4} />}</DataTable><Pagination page={connections.data} path="/admin/sessions" params={params} cursorKey="connectionsAfter" /></>}</section></>;
}
