import type { AdminPage, AdminUser, AdminUserDetail } from '../lib/admin-types';
import { ActionButton, AdminLink, bytesText, DataTable, dateText, EmptyRow, FilterForm, identityText, PageHeading, Pagination, queryPath, ResourceState, SelectFilter, statusText, useResource, useSelection } from './AdminShared';

export function UsersPage({ params }: { params: URLSearchParams }) {
  const query = new URLSearchParams(params); query.set('limit', '50'); const resource = useResource<AdminPage<AdminUser>>(queryPath('/api/v1/admin/users', query)); const { selected, toggle } = useSelection();
  const users = resource.data?.items || []; const labels = users.filter((user) => selected.includes(user.id)).map(identityText);
  return <><PageHeading title="用户管理" description="查看账号状态、限制和实际资源用量，操作将要求理由与二次验证。" /><FilterForm path="/admin/users"><label className="admin-filter">搜索用户名或昵称<input name="q" defaultValue={params.get('q') || ''} /></label><SelectFilter label="账号状态" name="status" value={params.get('status') || ''} options={ [['', '全部状态'], ['active', '正常'], ['banned', '已封禁'], ['deleting', '注销冷静期'], ['deleted', '已注销']] } /><SelectFilter label="站点角色" name="role" value={params.get('role') || ''} options={ [['', '全部角色'], ['user', '普通用户'], ['super_admin', '超级管理员']] } /><SelectFilter label="排序" name="sort" value={params.get('sort') || 'newest'} options={ [['newest', '最新注册'], ['oldest', '最早注册'], ['username', '用户名']] } /></FilterForm><ResourceState {...resource} />{resource.data && <><div className="admin-bulk"><span>本页已选 {selected.length} 人</span>{(['user.ban', 'user.unban', 'user.mute', 'user.unmute', 'user.logout_all'] as const).map((action, index) => <ActionButton key={action} request={{ action, targetIds: selected, labels }}>{['封禁', '解封', '禁言', '解除禁言', '退出全部设备'][index]}</ActionButton>)}</div><DataTable caption="用户列表" headings={['选择', '账号', '角色 / 状态', '注册 / 最近活动', '群 / 会话', '已用附件配额']}>{users.length ? users.map((user) => <tr key={user.id}><td><input type="checkbox" aria-label={`选择 ${user.username}`} checked={selected.includes(user.id)} onChange={(event) => toggle(user.id, event.target.checked)} /></td><th scope="row"><AdminLink href={`/admin/users/${encodeURIComponent(user.id)}`}>{identityText(user)}</AdminLink><small>{user.id}</small></th><td>{statusText(user.siteRole)}<br /><span className={`admin-badge ${user.status}`}>{statusText(user.status)}</span></td><td>{dateText(user.createdAt)}<br />{dateText(user.lastSeenAt)}</td><td>{user.ownedGroupCount} 群 / {user.sessionCount} 会话</td><td>{bytesText(user.storageBytes)} / {bytesText(user.quotaBytes)}</td></tr>) : <EmptyRow count={6} />}</DataTable><Pagination page={resource.data} path="/admin/users" params={params} /></>}</>;
}
export function UserDetailPage({ id }: { id: string }) {
  const resource = useResource<AdminUserDetail>(`/api/v1/admin/users/${encodeURIComponent(id)}`); const user = resource.data?.user;
  return <><PageHeading title="用户详情" description="账号当前状态和限制理由以服务器返回为准。"><AdminLink href="/admin/users">返回用户列表</AdminLink></PageHeading><ResourceState {...resource} />{user && <><section className="admin-panel"><h2>{identityText(user)}</h2><p>{user.bio || '尚未填写简介'}</p><dl className="admin-facts">{([['账号编号', user.id], ['站点角色', statusText(user.siteRole)], ['状态', statusText(user.status)], ['状态理由', user.statusReason || '无'], ['全站禁言至', user.mutedUntil === null ? '未禁言' : dateText(user.mutedUntil)], ['禁言理由', user.muteReason || '无'], ['上传限制', user.uploadDisabled ? '禁止上传' : '允许上传'], ['创建群聊限制', user.groupCreationDisabled ? '禁止建群' : '允许建群'], ['限制理由', user.restrictionReason || '无'], ['注册时间', dateText(user.createdAt)], ['注销时间', dateText(user.deletionAt)], ['最近活动', dateText(user.lastSeenAt)], ['已用附件配额 / 总配额', `${bytesText(user.storageBytes)} / ${bytesText(user.quotaBytes)}`], ['拥有群数 / 会话数', `${user.ownedGroupCount} / ${user.sessionCount}`], ['必须修改密码', user.mustChangePassword ? '是' : '否'], ['第二因素', user.hasSecondFactor ? '已启用' : '未启用']]).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="admin-actions"><AdminLink href={`/admin/sessions?userId=${encodeURIComponent(user.id)}`}>查看设备与连接</AdminLink><AdminLink href={`/admin/groups?ownerId=${encodeURIComponent(user.id)}`}>查看拥有的全部群聊</AdminLink></div></section><section className="admin-panel"><h2>账号管理操作</h2><div className="admin-actions">{user.status !== 'deleted' && <><ActionButton request={{ action: user.status === 'banned' ? 'user.unban' : 'user.ban', targetIds: [id], labels: [identityText(user)] }}>{user.status === 'banned' ? '解除封禁' : '封禁账号'}</ActionButton><ActionButton request={{ action: 'user.mute', targetIds: [id], labels: [identityText(user)] }}>全站禁言</ActionButton>{user.mutedUntil !== null && <ActionButton request={{ action: 'user.unmute', targetIds: [id], labels: [identityText(user)] }}>解除全站禁言</ActionButton>}<ActionButton request={{ action: 'user.restrict', targetIds: [id], labels: [identityText(user)], initial: { uploadDisabled: user.uploadDisabled, groupCreationDisabled: user.groupCreationDisabled } }}>调整上传与建群限制</ActionButton><ActionButton request={{ action: 'user.logout_all', targetIds: [id], labels: [identityText(user)] }}>退出全部设备</ActionButton><ActionButton request={{ action: 'user.password_reset', targetIds: [id], labels: [identityText(user)] }}>人工重置密码</ActionButton><ActionButton request={{ action: 'user.quota', targetIds: [id], labels: [identityText(user)], initial: { quotaBytes: user.quotaBytes } }}>调整附件配额</ActionButton></>}{user.status === 'deleting' && <ActionButton request={{ action: 'user.restore', targetIds: [id], labels: [identityText(user)] }}>恢复冷静期账号</ActionButton>}</div></section></>}</>;
}
