from __future__ import annotations

import json
from pathlib import Path

from tongpin.contracts.base import HealthResponse


def typescript(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "object":
        required = schema.get("required", [])
        items = [f'{json.dumps(key)}{"" if key in required else "?"}: {typescript(value)}' for key, value in schema.get("properties", {}).items()]
        extra = schema.get("additionalProperties")
        if extra:
            items.append(f'[key: string]: {typescript(extra) if isinstance(extra, dict) else "unknown"}')
        return "{ " + "; ".join(items) + " }"
    if kind == "array":
        return "(" + typescript(schema.get("items", {})) + ")[]"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def main():
    root = Path(__file__).resolve().parents[1]
    output = root / "packages/contracts/src"
    output.mkdir(parents=True, exist_ok=True)
    schemas = {model.__name__: model.model_json_schema() for model in (HealthResponse,)}
    lines = ["// Generated by scripts/export_contracts.py; do not edit."]
    seen = set()
    for name, schema in schemas.items():
        for key, value in schema.get("$defs", {}).items():
            if key not in seen:
                lines.append(f"export type {key} = {typescript(value)};")
                seen.add(key)
        lines.append(f"export type {name} = {typescript(schema)};")
    (output / "generated.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (output / "schema.json").write_text(json.dumps(schemas, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Exported {len(schemas)} runtime schemas")


if __name__ == "__main__":
    main()
