import type { Conversation, UserSummary } from './chat-types';

export type GroupMember = { user: UserSummary; periodId: string; role: 'owner' | 'admin' | 'member'; joinedAt: number; mutedUntil: number | null };
export type GroupSettings = { announcement: string; announcementPinned: boolean; reviewRequired: boolean; inviteRole: 'managers' | 'members'; everyoneMuted: boolean; slowSeconds: number };
export type GroupTransfer = { id: string; conversationId: string; from: UserSummary; to: UserSummary; targetPeriodId: string; status: 'pending' | 'accepted' | 'rejected' | 'cancelled' | 'expired'; expiresAt: number; createdAt: number };
export type GroupDetail = { conversation: Conversation; version: number; settings: GroupSettings; capabilities: { canEdit: boolean; canInvite: boolean; canReview: boolean; canAssignRoles: boolean; canTransfer: boolean; canDissolve: boolean; canLeave: boolean }; transfer: GroupTransfer | null };
export type GroupInvite = { id: string; conversationId: string; groupName: string; kind: 'link' | 'direct'; creator: UserSummary; target: UserSummary | null; maxUses: number; used: number; reserved: number; remaining: number; expiresAt: number; createdAt: number; state: 'available' | 'expired' | 'revoked' | 'exhausted' | 'full' | 'unavailable'; canRevoke: boolean; application?: GroupApplication | null };
export type GroupApplication = { id: string | null; conversationId: string; groupName: string; inviteId: string; user: UserSummary; status: 'pending' | 'approved' | 'rejected' | 'cancelled' | 'expired' | 'already_member'; currentMember: boolean; expiresAt: number; createdAt: number };
export type InvitePreview = { inviteId: string; conversationId: string; name: string; description: string; memberCount: number; requiresApproval: boolean; expiresAt: number; maxUses: number; remaining: number; state: GroupInvite['state'] | 'already_member' | 'pending'; application: GroupApplication | null };
export type GroupAudit = { id: string; action: string; actor: UserSummary | null; reason: string; createdAt: number; details: Record<string, unknown> };
